### ISSUE TITLE
SAE läuft QNAP-Docker läuft, Konfig ändern/speichern nicht möglich

### ISSUE THREAD

**Issue by pwtanagit** [camueller/SmartApplianceEnabler#100]
- avanux/smartapplianceenabler-amd64:latest installiert, Netzwerk: bridge
- backend aufrufbar via 192.168.x.x:8080, aber error:
GET http://192.168.2.12:8080/sae/appliance?id=F-26091964-000000000011-00 404

- SAE im HM sichtbar (aber ohne Geräte)
- neue Geräte werden nicht gespeichert
- keine Konfig-Dateien (Device2EM.xml, Appliances.xml) in /opt/sae

**Comment by camueller** [comment]
Versuch bitte mal avanux/smartapplianceenabler-amd64:ci
Geht das bei Dir?

**Comment by pwtanagit** [comment]
danke für die sehr schnelle Antwort: "ci" probiert: leider gleiches Bild

im backend:
GET http://192.168.2.12:8080/sae/appliance?id=F-26091964-000000000012-00 404
bzw.
http-error-interceptor.ts:18 Backend error: code 404, error: null, message: Http failure response for http://192.168.2.12:8080/sae/appliance?id=F-26091964-000000000012-00: 404 OK

kann ich noch etwas testen?

**Comment by camueller** [comment]
Dann stimmt etwas mit Deiner Docker-Konfiguration nicht. Evtl. fehlt das sae-Volume.
Das ci.Image müßte auf jeden Fall funktionieren bei Dir, da dieses Image auch auf meiner AWS-Instanz läuft (http://ec2-18-221-3-23.us-east-2.compute.amazonaws.com) und dort im Rahmen der automatisierten Tests Konfigurationen angelegt wurden.
Ich schließe den Issue, da es sich nicht um ein Problem des SAE handelt.

**Comment by pwtanagit** [comment]
danke für den Hinweis. genau das war's: volume war nicht angelegt. nicht gut gelesen. sorry. kleine Anerkennung per paypal ist erfolgt.

**Comment by camueller** [comment]
Schön, dass es jetzt bei Dir geht! Ich würde Dir allerdings empfehlen, wieder auf Tag `latest` oder `1.5.4` zu wechseln, weil Du sonst jede Änderung sofort bekommst, nicht erst bei einem Release. Das passt dann oft nicht zur Dokumentation oder es funktionieren bestimmte Teile des SAE nicht.

Vielen Dank auch für Deine Unterstützung via Paypal!

**Comment by pwtanagit** [comment]
mach ich.

ich bin ganz froh, wie hübsch ich nun via SAE meine fibaro-welt (in
fibaro kann man alles per REST-api lesen oder schreiben) einbinden kann.

die KEBA-wallbox wird wohl noch etwas dauern, KEBA ist UDP (in fibaro
hab ich das zwar, aber immer nur per button)

super Projekt! danke!
schönes WE
Peter


Am 28.03.2020 um 11:05 schrieb Axel Müller:

**Comment by camueller** [comment]
Ich lade meinen Leaf fast nur mit Überschußenergie, aber das setzt voraus, dass man die Wallbox steuern kann. Es gibt eine größere Auswahl an Wallboxen mit "dem" PhoenixContact-Ladecontroller und es gibt den go-eCharger - damit könntest Du den SAE optimal nutzen für Dein Auto. Vielleicht kannst Du die Keba verkaufen und dann eine der o.g. Wallboxen kaufen.
