### ISSUE TITLE
Modbus Function "Read Holding Registers" ergänzen

### ISSUE THREAD

**Issue by chris-et** [camueller/SmartApplianceEnabler#101]
Einige Modbus-Zähler erwarten ein Auslesen der Daten über die Funktion "Read Holding Registers" (0x03) statt über "Read Input Registers" (0x04). In angehängter Spezifikation von modbus.org sind die Funktionen auf Seite 15 & 16 aufgeführt.
[Modbus_Application_Protocol_V1_1b.pdf](https://github.com/camueller/SmartApplianceEnabler/files/4399490/Modbus_Application_Protocol_V1_1b.pdf)
Ggfs. könnte man in der GUI bei den Modbus-Zähler-Eigenschaften ein Auswahlfeld in der Zeile mit Register-Adresse und Register-Typ zum Auswahl der Funktion 0x03 & 0x04 erstellen und als Standardwert 0x04 vorgeben?
Da sich im Modbus-Protokoll die Syntax beider Befehle nicht unterscheidet, müsste bei der Generierung des Modbus-Pakets im Falle der Auswahl von 0x03 lediglich das 8. Byte von einer 0x04 in eine 0x03 geändert werden.

**Comment by chris-et** [comment]
Register-Typ: Holding...

**Comment by phlupp** [comment]
Hallo @chris-et 

funktioniert das bei dir per FC 03 einen Zähler auszulesen? Ich habe hier einen der vom ioBroker und meinem Rechner problemlos via FC 03 ausgelesen werden kann. Nur der SAE macht kein mux... 

Was mir schon etwas komisch vor kommt ist das im Log genau NULL Ausgabe zu Modbus erscheint sobald man den Typ Holding wählt. Als ob der Modbus erst gar nicht angetriggert wird. 

Ich habe im Forum auch einen Eintrag gefunden bei dem es genau so ist, da geht aber auch nicht hervor wie das ausgegangen ist.

Der mbusd funktioniert, wie gesagt kann ja auch von anderen Geräten gelesen werden.

Hier die config:
`<ModbusRead address="0x001C" bytes="4" type="Holding">`

Vielleicht hast du noch einen Tip für mich.

Danke

**Comment by camueller** [comment]
@phlupp Mit welcher  Version hast Du getestet? Für Holding-Register gab es Anpassungen in 1.6.3, als ggf. nochmal mit der aktuellen 1.6-Version testen ...

**Comment by phlupp** [comment]
@chris-et danke für die schnelle Antwort, ich habe am freitag ganz frisch die 1.5.11 installiert. Dann werde ich wohl mal updaten und nochmal testen.

ich melde mich nochmal - Vielen Dank

**Comment by phlupp** [comment]
@chris-et jetzt die 1.6.5 installiert, jetzt passiert auch was im log bzgl Modbus. Allerdings kommt immer die Meldung `Error reading input register`
obwohl ich Holding auswählt habe.
Aber vielen Dank schon mal für die richtige Richtung. Ich teste weiter.

**Comment by camueller** [comment]
Der User-Support läuft eigentlich in 
https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet/?pageNo=460#post2137314
Da sind auch andere iobroker-User ...
