### ISSUE TITLE
Abweichender Soll-SOC bei Ampel-Klick

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#104]
Es sollte die Möglichkeit geben, im Ampel-Dialog zum Starten des Ladevorganges festzulegen, dass mit optionaler Energie geladen werden soll, aber ein anderer Soll-SOC verwendet werden soll, als in den Default-Einstellungen festgelegt.
Dazu könne über den Feldern für Wochentag/Zeit eine Checkbox "Optionale Energie" platziert weden.
Wenn diese markiert wird, werden die Felder für Wochentag7Zeit deaktiviert und die Beschriftung des Buttons "Start" wird in "SOC ändern"  geändert.

**Comment by premultiply** [comment]
Zusätzlich wäre es wünschenswert den Begriff "Optionale Energie" durch "Überschuss" oder etwas Anderes, besser Verständlicheres zu ersetzten.
In anderen Ladelösungen haben sich die Begriffe "Sofortladen", "Min+PV" sowie "Nur PV" etabliert.

**Comment by camueller** [comment]
Ich wüßte nicht, wofür steht "Min+PV" steht? Hast Du einen Link zu den Begriffen?

**Comment by camueller** [comment]
Implementiert für Version 1.6.4.
