### ISSUE TITLE
Sunny Home Manager gefundene Gerät mit der Seriennummer 963256817 ist bereits in einer anderen Einrichtung registriert

### ISSUE THREAD

**Issue by sw1002** [camueller/SmartApplianceEnabler#105]
Hi, 
SAE 1.4.19 läuft auf einem raspi mit debian 
ich bekomme, nachdem ich alles installiert habe im Sunnyportal folgende Fehlermeldung:
Das von Ihrem Sunny Home Manager gefundene Gerät mit der Seriennummer 963256817 ist bereits in einer anderen Anlage registriert und kann deshalb Ihrer Anlage nicht hinzugefügt werden.

**Comment by camueller** [comment]
Das ist kein Fehler im SAE. Ich habe aber die Dokumentation angepasst: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/SunnyPortal_DE.md

**Comment by rokoerner** [comment]
Lieber Herr Müller, 
leider kann ich das angegebene Dokument nicht finden. Bei mir kommt es zur gleichen Fehlermeldung. Können Sie die Änderung noch einmal kommunizieren? VR R. Körner

**Comment by camueller** [comment]
Habe den Link oben korrigiert.

**Comment by ZeroDown08152** [comment]
Hallo, ich habe heute abend den SAE installiert und seit dem bekomme ich die gleiche Fehlermeldung mit der gleichen Serialnummer:
Das von Ihrem Sunny Home Manager gefundene Gerät mit der Seriennummer 963256817 ist bereits in einer anderen Anlage registriert und kann deshalb Ihrer Anlage nicht hinzugefügt werden.
ich habe es bereits geschafft meine Wärmepumpe in das Sunnyportal zu übertragen

**Comment by rokoerner** [comment]
Hi ZeroDown08152, siehe: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Appliance_DE.md -->ID ist entscheidend, nicht die SN.

**Comment by PhEngemann** [comment]
Hallo!
Ich bekomme nach der Installation des SAE die selbe Fehlermeldung im SMA Portal mit der exakt selben SNR. Ohne das bereits im SAE Geräte aktiviert sind. 
3 Geräte habe ich nun eingerichtet und diese wurden auch korrekt im Portal erkannt. Trotzdem erscheint im Portal regelmäßig wieder diese Warnung.

**Comment by camueller** [comment]
Antwort steht direkt im voranstehenden Post.

**Comment by PhEngemann** [comment]
Danke für die schnelle Antwort.
Den Post/Thread/Doku habe ich gelesen. Trotzdem der Hinweis für dich, dass im SMA Portal die Fehlermeldung kommt, auch wenn im SAE kein Gerät eingerichtet ist! Und auch noch bestehen bleibt, wenn alle Geräte eingerichtet sind und funktionieren.

**Comment by premultiply** [comment]
Das ist aber eine Sache des SP bzw. des SHM.
Ggf. das Teil mal neustarten. Hilft oft.

**Comment by Clarion30** [comment]
Hallo, hab das gleiche Problem SHM 2.0 neu gestartet und reset. Problem besteht weiterhin. Hat jemand eine Lösung gefunden bzw. bei SMA angefragt ?

Fehlermeldung

"Das von Ihrem Sunny Home Manager gefundene Gerät mit der Seriennummer 963256817 ist bereits in einer anderen Anlage registriert und kann deshalb Ihrer Anlage nicht hinzugefügt werden."


Danke für die Hilfe

**Comment by camueller** [comment]
Bitte die Doku richtig lesen - insbesondere der 1. Satz im Kapitel "ID":
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Appliance_DE.md#id

Reset des SHM wird vermutlich nicht helfen.

**Comment by Clarion30** [comment]
Hallo danke für die Antwort,

 ja das habe ich schon mehrmals gelesen und die ID auch nicht doppelt vergeben der Fehler kommt auch wenn ich keinSAE laufen habe bzw. den Raspberry abgeklemmt habe ?

**Comment by Trunks1982** [comment]
Ich würde sagen das es an der machine id liegt.Kenne das vom evcc her da haben auch einige den fehler gehabt.Aber wo man diese im sae ändern kann keine Ahnung

**Comment by camueller** [comment]
Ist das mit dem Lesen wirklich so schwer??? 

Da steht "muss über alle von SMA verwalteten Sunny Home Manager hinweg eindeutig sein".

Die von Dir gewählte ID kann doch durchaus von einem anderen Nutzer eines Sunny Home Manager bereits verwendet werden.

**Comment by Clarion30** [comment]
AHHHH das Wort "ALLE" hab ich überlesen (bin nur von meinen SHM ausgegangen ) DANKE

**Comment by Clarion30** [comment]
Na dem reset und wieder hinzufügen zur Anlage des SHM2.0 ist die Meldung weg
