### ISSUE TITLE
Möglichkeit den auch SOC per HTTP Request abzufragen

### ISSUE THREAD

**Issue by nheuk** [camueller/SmartApplianceEnabler#108]
Ich stelle mir eine Auswahl wie bei den Zählern und Schaltern vor (Modbus/HTTP), dass man zwischen Script/HTTP auswählen kann. Da ich meine ganzen Daten eh im iobroker habe muss ich nicht über ein zusätzliches Script den SOC Abfragen und könnte ein ganz einfach API zum iobroker verwenden.

**Comment by camueller** [comment]
Die Schnittstelle für die SOC-Abfrage soll universell sein, d.h. auch mit HTTPS oder vom Hersteller gelieferte Bibliotheken soll eine SOC-Abfrage möglich sein. Für den Nissan Leaf beispielsweise nutze ich eine Python-Bibliothek.
Deshalb wird sich an der SOC-Abfrage nichts ändern.
