### ISSUE TITLE
Gibt es schon ein SOC Skript für den BMW i3?

### ISSUE THREAD

**Issue by GiK90** [camueller/SmartApplianceEnabler#110]
Wurde schon ein SOC Skript für den BMW i3 angelegt?
Ist die Frage hier richtig, oder soll ich diese in einem Forum etc. stellen?

**Comment by camueller** [comment]
Ich kann kein Script anlegen für ein Auto, das ich nicht kenne/habe. Aber ich kann ein Script hinzufügen, das Du bereitstellst inkl. Dokumentation.

**Comment by GiK90** [comment]
Dafür bin ich wohl leider nicht bewandert genug. Aber wenn ich das mal angehe, dann melde ich mich bei dir. Echt klasse, was du da erschaffen hast! Respekt!
