### ISSUE TITLE
Bedarfsanforderung ohne Anlaufstromerkennung

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#111]
Ich würde gerne meine Tasmota-Schalter so einsetzen, dass ich ohne die Anlaufstromerkennung eine Bedarfsanforderung stellen kann.

Bei manchen Geräten führt diese zu Problemen oder ist wegen des Strombezugsverhaltens nicht so richtig damit kompatibel. z. B. ist die Waschmaschine schon halb mit Wasser gefüllt wenn ihr der Strom abgestellt wird. Ändere ich die Schwellwerte funktioneren dann andere Sachen nicht mehr. Ausserdem ist es nervig und der Haltbarkeit ggf. auch nicht förderlich wenn spontan ein Gerät nutzen will dass dann immer erst der Strom abgestellt wird.

Lange Rede kurzer Sinn:

Ich möchte einen langen Tastendruck am Tasmota-Gerät dazu nutzen dem SAE eine Bedarfsanforderung zu signalisieren. Durch kurze Tastendrück wird das manuell Gerät ein- und ausgeschaltet.
Tasmota bietet ja die Möglichkeit für diesen Fall über Rules z. B. einen spezifischen HTTP-Request an den SAE zu stellen.

Ich weiss nicht ob eine solche (dokumentierte) Gegenstelle derzeit im SAE schon existiert?

Idealerweise würde ich mir vorstellen/wünschen dass man mit einer HTTP-Get-Anfrage die spezifische Bedarfsanforderung stellen kann und der SAE dann sofort das Gerät abschaltet.

Noch toller wäre wenn der SAE ebenfalls über HTTP-Requests seinerseits entsprechende Kommandos am Tasmota-Gerät ansteuern könnte um z. B. über die eingebaute LED den Zustand der Bedarfsanforderung zu signalisieren.

**Comment by camueller** [comment]
Die UNterscheidung zwischen kurzem und langem Tastendruck ist nicht möglich, weil der SAE periodisch (alles 20s) den Schalterzustand abfragt und nur Änderungen dieses Status erkennen kann. Bei aktivierer Anlaufstromerkennung nutzen wir diese Statusänderung bereits für einen Sofortstart (siehe #79 ).
Die Schalterauswertung ohne Anlaufstromerkennung mit entsprechenden Folge-Aktivitäten erfordert relativ viele Anpassungen im SAE und wird wohl in nächster Zeit nicht implementiert werden ...

**Comment by premultiply** [comment]
Was wird denn aufgerufen wenn man bei Geräten ohne Anlauferkennung die Ampel per Klick auf gelb schaltet?

**Comment by premultiply** [comment]
Die Unterscheidung seitens SAE wäre auch nicht notwendig, da diese von Tasmota selbst z. B. in Form eines HTTP-Requests an den SAE kommt.

**Comment by camueller** [comment]
zu 1) Klick auf gelb wird derzeit nicht unterstützt. 
zu 2) Der SAE empfängt keine HTTP-Request vom Tasmota, sondern er sendet welche umd empfängt die Response. Das funktioniert und es besteht aktuell kein Handlungsbedarf.

**Comment by premultiply** [comment]
zu 1) Gibt es tatsächlich im SAE keinerlei Möglichkeit eine Bedarfsanforderung ohne die Anlaufstromerkennung zu stellen???
zu 2) Das ist schon klar dass er das momentan nicht macht. Von Tasmota aus wäre das aber problemlos möglich und somit könnte man dazu von Pull- bzw. Polling auf Push-Betrieb umstellen. Man kann ja auch die grün/rot SEMP-Requests der Ampel von extern ansteuern.

**Comment by camueller** [comment]
zu 1) doch, über einen Zeitplan
zu 2) Umstellung auf Push-Betrieb ist nicht geplant

**Comment by premultiply** [comment]
Egal, ich würde jedenfall einen wie immer gearteten HTTP-Hook vorschlagen um externe Bedarfsanforderungen abseits der Anlaufstromerkennung zu stellen.

**Comment by camueller** [comment]
Das [`websend` command für Tasmota-Rules](https://tasmota.github.io/docs/Rules/#two-way-light-switches-without-mqtt) könnte verwendet werden, um mittels Button eine Bedarfanforderung an den SAE zu senden.

**Comment by camueller** [comment]
Implementiert für Version 1.6.8.
Keine Verwendung mit Analufstromerkennung und Zeitplänen.
Siehe https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Tasmota_DE.md#laufzeitanforderung-bei-tastendruck-erstellen

**Comment by premultiply** [comment]
Das sieht doch ganz gut aus! Danke!
Schaue ich mir bei nächster Gelegenheit mal an.

**Comment by camueller** [comment]
Siehe auch #129.

**Comment by premultiply** [comment]
Was ich hier noch nicht verstehe warum über eine Tasmota Laufzeit und eine Endzeit übergeben werden muss während bei der Anlaufstromerkennung diese Werte ja alle bereits intern bekannt bzw. konfiguriert sind. Sogar der manuelle "Ampelstart" braucht nur eine geplante Laufzeit. Eigentlich sollten sich die Anlaufstromerkennung und der Anforderungstastendruck dahingehend nicht unterscheiden.

**Comment by camueller** [comment]
Weil die Anlaufstromerkennung eine Schalterart ist und die Tasmota-Unterstützung nur ein "Hack".
Der manuelle Ampelstart ist aber keine Einplanung, sondern ein Sofortstart. So war versehentlich auch der Tasmota-Hack bisher implementiert. Im Rahmen des Bugfixes zu #129 wird das immerhin eine normale Einplanung über den SHM.

Wie in der Dokumentation schon geschrieben können beim Tasmota-Trigger keine Schaltzeiten konfiguriert werden, also ist keine Einstaltdauer oder von-bis-Zeit bekannt.
Ausser Dir hat noch nie jemand ein derartiges Feature gewünscht, deswegen wird es auch keine Erweiterung des Features über den aktuellen Stand hinaus geben.

**Comment by premultiply** [comment]
Letzteres dürfte aber stark damit zusammenhägen dass den meisten Leuten nicht bewusst ist dass Tasmota dieses Feature überhaupt bietet.
In der Diskussion und in Beobachtung z. B. des Verhaltens meiner Eltern im Seniorenalter ist mir aber sehr schnell bewusst geworden dass die "Anlaufstromerkennung" für unbedarfte Nutzer nur zur Verwirrung führt und genau kontraproduktiv ist.
Da wird nämlich schnell einfach wieder auf den Knopf gedrückt um die Maschine wieder anzuschalten. "Das blöde Ding geht immer aus!".
Andersrum funktioniert es viel besser: Jedes Gerät funktioniert erstmal wie gewohnt und wenn man den Knopf drückt schaltet man gezielt in den "Energiesparmodus". Das versteht jeder sofort und notfalls auch ohne Erklärung. Eigenverbrauchsoptimierung soll Spass machen und nicht die Nutzer "gängeln". Was höre ich die Hausbewohner manchmal mit der Anlaufstromerkennung fluchen wenn sie nur mal kurz was waschen oder schleudern wollten...

**Comment by camueller** [comment]
Genau dafür ist die Anlaufstromerkennung da. Funktioniert prima, wie immer wieder auch von anderen Usern bestätigt wird. Und ist viel einfacher, weil man sich um gar nichts kümmern muss (im Gegensatz zum Drücken eines Tasters an einer Steckdose).
Außerdem werden die meisten keine Lust dazu haben, auf irgendeinem Steckdosen-Adapter mittels Tasmota-Shell Regeln zu definieren.

**Comment by premultiply** [comment]
Mag sein, für Unbedarfte ist die UE mit Anlaufstromerkennung ganz objektiv in einigen Fällen eher bescheiden, insbesondere da sie erstmal keine Wahl lässt.
Wenn man sich native SEMP-Geräte mit Nutzerbedienung anschaut erkennt man dort auch eher das explizite "Button-Konzept".

Und nochmal, da ich mir auf Grund deiner dazu erstellen Doku nicht sicher bin ob du das schon selbst mal richtig konfiguriert hattest: Der lange explizite "Energiespar-Knopfdruck" ist optional.
Das Gerät funktioniert ansonsten wie vorher auch - im Gegensatz zur Anlaufstromerkennung, die implizit wirkt und ggf. aktiv nachträglich übersteuert werden muss.

Ich sehe für beide Fälle durchaus völlig berechtigte und sinnvolle Anwendungsszenarien, daher würde ich mit wünschen dass dies beides auf gleiche Weise implementiert werden könnte.

Wenn man dann noch über eine definierte API auf den jeweiligen Ampelstatus zugreifen könnte könnte man dem Benutzer sogar noch ein direktes optisches Feedback geben.

**Comment by camueller** [comment]
Wie ich bereitsgeschrieben hatte, will ausser Dir niemand Buttons an irgendwelchen Adapter drücken, wenn er eine Anlaufstromerkennung nutzen kann. Trotzdem hatte ich rudimentären Support dafür eingebaut, weil ich das Thema bis zu einem gewissen Grad interessant fand.
Da ich persönlich keine Verwendung für das Feature habe (und ausser Dir scheinbar auch niemand) bin ich nicht gewillt, eine der Anlaufstromerkennung gleichwertige Implementierung zu machen. Zumal es hier um etwas geht, dass *nur* für Tasmota-basierte Geräte relevant wäre.
Aber Du kannst die entsprechenden Anpassungen im Backend und Frontend machen und mir dann einen Pull Request senden. Wenn Dir das Thema wichtig ist, wirst Du sicher auch die Zeit dafür haben.

**Comment by premultiply** [comment]
Auch wenn ich über diese gefühlte Grundablehnung dieses Themas etwas verwundert bin:
Ich schaue es mir an - auch wenn ich Java auch grundsätzlich ablehne. Es gibt ja genug andere Sprachen... ;)

Und nein, das ist nicht nur für Tasmota-Geräte relevant sondern könnte über eine allgemein bekannte API auch für andere Zwecke interessant werden. ...könnte.

**Comment by camueller** [comment]
Dein Pull-Request müsste auch sämtliche Anpassungen im Frontend mit Angular umfassen. Ab das sehe ich ja dann beim Review.
