### ISSUE TITLE
HTTP Switch - Shutdown via URL not working

### ISSUE THREAD

**Issue by KingKahn123** [camueller/SmartApplianceEnabler#114]
I am using the new version 1.6.2 and have a dishwasher configured. Although I have a http switch configured for "on" and "off" defined, I cannot turn the dishwasher off. In the log files I can see that the http url request for switch "on" is triggered and executed. However if I click on the stop light the device is not turned off and I cannot see any entry in the log files that the http switch "off" url was triggered.

**Comment by camueller** [comment]
Bei aktivierter Anlaufstromerkennung wird das Gerät nur nach Erkennen des Anlaufstroms abgeschaltet. Wenn es auch nach Klick auf die rote Ampel abgeschaltet werden würde, könnte nachfolgend kein Alnaufstrom mehr erkannt werden. Insofern liegt hier kein Fehler im SAE vor.
