### ISSUE TITLE
GUI erzeugt ungültige Konfigurationen

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#117]
Der Versuch eine Ladesteuerung (EVCC) als "Lagegerät" an SAE anzubinden gleicht einem Hürdenlauf mit unsichtbaren Hürden.
Die SAE-GUI erzeugt nämlich teilweise Konfigurationen die SAE selbst als ungültig erachtet und dann sofort terminiert.
Somit kann man nur Schrittweise anhand der Logs auswerten was denn jetzt schon wieder angeblich falsch ist oder fehlt und ggf. muss dann ggf. den ganzen Abschnitt aus der Appliances.xml löschen und wieder von vorne anfangen.

Hier wäre es besser wenn die GUI solche ungültigen Konfigurationen gleich verhindern würde und andererseits Geräte auch mit weiteren optionalen Feldern zulässig wären, da nicht alle Geräte auch die vom SAE derzeit gewünschten Datenfelder bereitstellen oder einfach vom Anwender nicht gewünscht ist dass SAE dort bestimmte Eigenschaften steuert, da die Geräte das selber besser können aber die Verbrauchsdaten und Zustände importiert werden sollen.

**Comment by camueller** [comment]
Die SAE-Web-UI sollte nur gültige Konfigurationen erstellen, Falls das nicht so ist, liegt eine Fehler vor. Um den zu beheben, benötige ich eine reproduzierbare Fehlerbeschreibung. Ohne diese kann ich keinen Fix machen.
