### ISSUE TITLE
Sunny Home does not find any devices....

### ISSUE THREAD

**Issue by hoschult** [camueller/SmartApplianceEnabler#121]
thanks for providing such a great software. I used it by installing via docker-compose. However after defining a virtual device, I received the message "Es wurden keine Geräte gefunden." from sunny portal. I read the notes in respect to docker/multicast and ensured to use network: host. However, it doesn't work....

Any hints?

**Comment by camueller** [comment]
Please refer to the Documentation I updated today (it's only available in German …): https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md

**Comment by bubbagump24** [comment]
It is important that you define a device ID which is unique within the whole Sunny Portal. If you chose one which has already been taken, you will not see the device in your sunny portal device list, but instead find an entry in the log of the sunny portal, stating that the device is already registered to another environment. 
Try using a totally random ID (i.e. including your birthdate)

**Comment by hoschult** [comment]
thanks to your comments - now sunny portal is showing the sae devices... Using docker-compose file supplied by the new manual (camueller) solved my issues - I guess it is this "macvlan0" thing ;-)
