### ISSUE TITLE
Doppelte Geräte-ID verhindern

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#127]
Wenn man in der GUI aus versehen eine Geräte-ID doppelt vergibt z. B. für ein Neugerät kommt es zu seltsamen und über die GUI unkorrigierbaren Fehlern die man nur durch manuelle Korrektur der XML-Konfigurationsdateien beheben kann.

Hier wäre es sinnvoll die Vergabe bzw. das Abspeichern von bereits existierenden Geräte-IDs zu unterbinden.

**Comment by camueller** [comment]
Implementiert für 1.6.11
