### ISSUE TITLE
Gerätezustand beibehalten

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#128]
Wenn der SAE z. B. durch Konfigurationsänderungen neugestartet wird vergisst er den momentanen Zustand der angeschlossenen Geräte.
Hierbei werden insbesondere gerade aktive Programm-Geräte mit Anlaufstromerkennung (z. B. Waschmaschine) dann hart abgebrochen weil fälschlicherweise ein "Anlaufstrom" neu erkannt wird.

Wunschziel: Der SAE sollte insbesondere bei Konfigurationsänderungen den Zustand der Geräte beibehalten bzw. fortsetzen.

**Comment by camueller** [comment]
Dieses Feature würde ein sehr hohen Aufwand bedeuten und ist daher nicht geplant, zumal Konfiguratonsänderungen selten sind.
