### ISSUE TITLE
Bedarfsanforderung funktioniert nicht

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#129]
Ich habe nun ein Tasmota-Testgerät angebunden und mit der entsprechenden Rule wird bei einem langen Tastendruck eine Bedarfsanforderung an den SAE gestellt. Das funktioniert auch soweit, denn zumindest das Timeframe wird erstellt.

Es gibt aber mehrere Probleme:
1) Das Gerät wird vom SAE nach dem Tastendruck nicht abgeschaltet (vgl. Anlaufstromerkennung) um dann vom SHM später aktiviert zu werden.
2) Der SAE meldet EMSignalsAccepted: false an den SHM, so dass das Gerät auch nie angesteuert wird.

**Comment by camueller** [comment]
Sollte mit der nächsten Version gefixt sein.

**Comment by rolsch** [comment]
> Ich habe nun ein Tasmota-Testgerät angebunden und mit der entsprechenden Rule wird bei einem langen Tastendruck eine Bedarfsanforderung an den SAE gestellt. Das funktioniert auch soweit, denn zumindest das Timeframe wird erstellt.
> 
> Es gibt aber mehrere Probleme:
> 
> 1. Das Gerät wird vom SAE nach dem Tastendruck nicht abgeschaltet (vgl. Anlaufstromerkennung) um dann vom SHM später aktiviert zu werden.
> 2. Der SAE meldet EMSignalsAccepted: false an den SHM, so dass das Gerät auch nie angesteuert wird.

Kannst du hier mal die Rule für den langen Tastendruck reinstellen?
Bei zu langem Tastendruck wechselt Tasmota doch ein den Konfigurationsmodus...

**Comment by camueller** [comment]
Die Dokumentation wurde aktualisiert: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Tasmota_DE.md
