### ISSUE TITLE
Gerätekonfiguration "Nur Überschuss"

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#130]
Ich versuche gerade eine Konfiguration für ein Gerät anzulegen welches ausschließlich mit Überschussenergie betrieben werden soll.
Wenn keine Überschussenergie da ist kann es auch ganz ausbleiben, mit Überschuss bis theoretisch 24 Stunden am Tag laufen.
Ich brauche also eigentlich kein Zeitfenster bzw. ein sehr langes.

Leider klappt das noch nicht wirklich und ich frage mich ob es am SAE oder nur an meiner Konfiguration liegt.

Ich hab zum Test ein neues Device (erstmal nur eine Lampe) vom Typ "other" angelegt mit Max. Leistungsaufname 60W und Unterbrechung erlaubt. Ansonsten für den Tasmota-Zwischenstecker als entsprechend und wie gewohnt konfiguriert (an/aus/Zählerstand...).

Da ich ja zwingend ein Timeframe brauche habe ich also einen Zeitplan angelegt z. B. 21 Stunden von 2 bis 23 Uhr.

Jetzt kommt das große Problem: Anstatt sofort loszulaufen meldet SAE dass das der Startzeitpunkt noch nicht erreicht wurde weil er das bereits laufende Timeframe nicht erkennt. Ich müsste daher immer bis zum nächsten Tag warten und darf zwischendurch auch nichts an der Konfiguration ändern oder manuell schalten, da ich an diesem Tag nicht wieder in den Überschussmodus zurück kann.
Da fehlt somit auch eine Möglichkeit wieder manuell Überschussmodus zurückzukehren, womit man das Timerframe-Problem wenigstens umgehen könnte. Man müsste dazu bei Bedarf die Ampel wieder auf gelb schalten können.

**Comment by camueller** [comment]
Die Ampel dient nur zum Stoppen eines aktuellen Timeframe-Intervals (der aus einem Zeitplan resultiert) oder dem manuellen Anlegen eines Timeframe-Intervals. Diesbezüglich ist keine Änderung geplant. Ob ein Timeframe sich gerade im Überschussmodus befindet, hängt nur von den vorgegebenen Zeiten des Zeiplans vermindert um die bishere Laufzeit im aktuellen Timeframe-Interval ab. Auch hier ist keine Änderung plant.
Ob ein Timeframe-Interval mit Überschussenergie sofort starten kann, muss ich noch prüfen ...

**Comment by camueller** [comment]
Fall für eine Timeframe-Interval eine minmale Laufzeit angegeben ist (im Extremfall 0) wird diese bei der Berechnung des frühestmöglichen Intervals herangezogen. So wird das Verhalten ab der nächsten Version sein.

**Comment by rolsch** [comment]
> Ich versuche gerade eine Konfiguration für ein Gerät anzulegen welches ausschließlich mit Überschussenergie betrieben werden soll.
> Wenn keine Überschussenergie da ist kann es auch ganz ausbleiben, mit Überschuss bis theoretisch 24 Stunden am Tag laufen.
> Ich brauche also eigentlich kein Zeitfenster bzw. ein sehr langes.
> 
> Leider klappt das noch nicht wirklich und ich frage mich ob es am SAE oder nur an meiner Konfiguration liegt.
> 
> Ich hab zum Test ein neues Device (erstmal nur eine Lampe) vom Typ "other" angelegt mit Max. Leistungsaufname 60W und Unterbrechung erlaubt. Ansonsten für den Tasmota-Zwischenstecker als entsprechend und wie gewohnt konfiguriert (an/aus/Zählerstand...).
> 
> Da ich ja zwingend ein Timeframe brauche habe ich also einen Zeitplan angelegt z. B. 21 Stunden von 2 bis 23 Uhr.
> 
> Jetzt kommt das große Problem: Anstatt sofort loszulaufen meldet SAE dass das der Startzeitpunkt noch nicht erreicht wurde weil er das bereits laufende Timeframe nicht erkennt. Ich müsste daher immer bis zum nächsten Tag warten und darf zwischendurch auch nichts an der Konfiguration ändern oder manuell schalten, da ich an diesem Tag nicht wieder in den Überschussmodus zurück kann.
> Da fehlt somit auch eine Möglichkeit wieder manuell Überschussmodus zurückzukehren, womit man das Timerframe-Problem wenigstens umgehen könnte. Man müsste dazu bei Bedarf die Ampel wieder auf gelb schalten können.

Hi premultiply,
du müsstest aber im SunnyPortal in der Gerätekonfiguration für diesen Switch am dortigen Schiebeschalter Überschussenergie einstellen...

**Comment by premultiply** [comment]
Mit der 1.6.10 sieht es jetzt schon mal deutlich besser aus. Danke!
Leider ist wegen mangelndem Überschuss gerade noch kein wirklicher Funktiontest möglich.

Ein kleines Problem ist mir aber noch aufgefallen: Man muss im Zeitplan bei der Mindestlaufzeit wirklich explizit 00:00 eintragen damit das klappt. Wenn das Feld einfach intuitiv leer bleibt wird hingegen eine Mindestlaufzeit von MaxRunningTime - 1 angemeldet was zumindest nicht intuitiv meiner Erwartung entspricht.
Intuitiv hätte ich hier Feld leer = keine Mindestlaufzeit gewünscht = 00:00 erwartet.

Wenn man nach der Erstkonfiguration mit leerem Feld das Formular nochmal aufruft steht dann dort auch 00:00 im Feld und wenn man dann nochmal speichert passt es dann auch im /semp.

**Comment by camueller** [comment]
Deine Beobachtung Mindestlaufzeit = MaxRunningTime - 1 ist ein Workaround für einen SHM-Fehler und hat nichts mit dem Nichteingeben einer Mindestlaufzeit zu tun.
