### ISSUE TITLE
"Energiemenge" bei HTTP-Zählern aus GUI verschwunden

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#132]
Hallo Axel,
meine Tasmota-Geräte laufen alle über die Zählerstandsabfrage via "Energiemenge". Das ist insbesondere für die Anlaufstromerkennung die deutlich bessere Variante, da dabei die Energiemenge über das Abfrageintervall integriert wird während bei der Momentanleistung ja immer nur eine Momentaufnahme übermittelt wird.

Bisher war diese Option auch in der GUI in den HTTP-Zählereigenschaften im Dropdown für "Zustand" auswählbar.
Jetzt bei der 1.6.10 (vielleicht auch schon vorher, hab ich nicht drauf geachtet) ist bei allen vorhandenen Geräten das Feld leer und bei neuen Geräten ist "Energiemenge" nicht mehr anwählbar sondern nur noch "Leistung".
Zumindest in der Appliances.xml steht es aber zum Glück nocht korrekt drin.

```
            <HttpRead url="http://192.168.178.47/cm?cmnd=Status%208">
                <HttpReadValue name="Energy" path="$.StatusSNS.ENERGY.Total" extractionRegex=",\&quot;Total\&quot;:((\d*\.)?\d+)," factorToValue="1.0"/>
            </HttpRead>
```

Kannst du da mal bitte nach gucken?

**Comment by camueller** [comment]
Die Konfiguration der Energiemenge ist Geräten mit variabler Energieaufnahme (derzeit nur Wallboxen) vorbehalten.
Insofern ist das von Dir beobachtete Verhalten beabsichtigt, d.h. über die Web-Oberfläche ist eine Konfiguration nicht mehr möglich. In der XML-Datei geht es aktuell noch, aber diese wird bei jeder Konfigurationsänderung überschrieben. Es besteht die Möglichkeit, dass das irgendwann auch nicht mehr funktioniert aufgrund der eingangs genannten Restriktion.

**Comment by premultiply** [comment]
Warum? Das hat doch zuvor hervorragend funktioniert und tut es eigentlich auch weiterhin - bis auf die GUI-Auswahl.

Die momentane Leistungsaufnahme ist hingegen z. B. bei einer Waschmaschine mit "Knitterschutz" hingegen quasi unbrauchbar.

**Comment by camueller** [comment]
Die Möglichkeit, die Energiemenge zu konfigurieren, verwirrt die meisten User und sollte nicht notwendig sein.
Dass es überhaupt funktioniert ist nur der Tatsache zu verdanken, dass ich es für den go-eCharger implementiert habe, der nur die Energiemenge liefern kann, sodass ich daraus die Leistung berechnen muss.

Wir haben auch einen Trockner mit Knitterschutz. Die Lösung besteht darin, die Leistungsaufnahme für die Anlaufstromerkennung hoch genug zu setzen, damit das gelegentliche Drehen der Trommer keinen Neustart signalisiert (bei mir 40W). Eine andere Möglichkeit ist, das Messinterval auf einen Wert grösser 60s zu setzen.
Du siehst, es geht auch ohne Energiemenge.

**Comment by premultiply** [comment]
Gehen tut viel, aber ob das immer so sinnvoll ist ist eine andere Frage. :)

Erst relativ kompliziert aus gesampleten Momentanwerten eine Energiemenge zu interpolieren wenn man sie auch gleich abfragen könnte finde ich jetzt wirklich nicht optimal gelöst.

Insbesondere da ich mich als Anwender bei dem zugehörigen Code und den Einstellungsmöglichkeiten im SAE wirklich frage was da eigentlich wie genau berechnet wird. Das ist auch nicht wirklich nachvollziehbar dokumentiert. Es gibt eine Abfrageintervall, es gibt ein Messintervall. Aha. Und wie hängen die Zusammen? Guckt man in die Hilfe erfährt nur, dass das "Abfrageintervall" eigentlich das Messintervall ist (Sampling des Momentanverbrauchs). Für eine valide Durchschnittsermittlung anhand der Momentanleistung müsste dieses daher möglichst klein sein.

Beim Knitterschutz der Waschmaschine kommt man mit der von dir beschriebenen Maßnahmen nicht weit, da es Zufall ist, ob die Trommel zum Messzeitpunkt gerade dreht oder lange Pause ist. Und selbst wenn man hier mit kurzen Messintervallen (SAE-Ausdruck "Abfrageintervall") und langen Integrationszeiten arbeitet (SAE-Ausdruck "Messintervall") passt dann die Anlaufstromerkennung wieder nicht weil sie dann ewig träge wird und der Waschvorgang schon längst begonnen hat bis dann endlich der Anlaufstrom erkannt und abgeschaltet wird. Von dem durch das niedrige Intervall permanenten HTTP- und WiFi-Traffic mal ganz abgesehen.

Der SHM möchte mit jeder minütlichen Abfrage die Durchschnittsleistung über das vergangene Intervall wissen.
Hierzu berechnet man die gezählte Energie pro Zeitintervall (= Differenz des Zählerstands zwischen zwei Ablesungen).
Bei den S0-Zählern machst du es doch (hoffentlich) auch so, oder?

Kurz gesagt du machst es mit der Momentanleistung unnötig kompliziert, schwer nachvollziehbar und vom Ergebnis her durch die Stichproben auch noch ungenau.

Wenn einer der Modi gestrichen werden sollte dann eher genau die Momentanleistung mitsamt dem komplizierten Code.
Die "Energiemessung" würde ich dann noch in "Energiezählung" oder "Zählerstand" umbenennen um es eindeutig zu machen und die von dir beschriebene Verwirrung zu vermeiden. Wenn da eine Verwirrung da ist dann wahrscheinlich am ehesten durch die verwendeten Begrifflichkeiten.

Vorher war es gut mit Optimierungspotenzial für die Begrifflichkeiten, jetzt würde es mit deiner Ankündigung deutlich schlechter.

Vielleicht überlegst du dir das ja nochmal. Ich würde es sehr begrüßen da es die Messungen und Entscheidungen zuverlässiger und verständlicher macht.

**Comment by camueller** [comment]
Was genau soll an der Momentanleistung kompliziert sein? Der SAE fragt bei diesen Wert ab und berechnet aus mehreren Werten den Durchschnitt. Das wars und das versteht auch eine Nicht-Programmierer.
Wie schon geschrieben, ist die Energiemenge nur für Wallboxen relevant. Es kann nicht darum gehen, dass bei Dir zufällig die aus Energiemengendifferenzen berechnete Leistung genauer ist, als die direkt abgefragte Leistung.
In den allermeisten Fällen sollte es keine Notwendigkeit geben, andere Werte für Messintervall oder Abfrageintervall zu setzen. Ich stimme Dir zu, dass man diese besser dokumentieren oder vielleicht sogar umbenennen könnte.
Beim Knitterschutz stimme ich Dir nicht zu, weil es beim Messinterval von 60s keine Rolle spielt, wann die Rolle gerade mal kurz weiterdreht. Du musst nur in das Log schauen, welche (Durchschnittsleistung9 in dieser Zeit berechnet wird und die Leistungsschaltgrenze etwas höher setzen. Die Anlaufstromerkennung sollte dadruch nicht oder nur unwesentlich träger werden.
Der Default-Interval zur Abfrage von HTTP-Zählern ist 20s. Der HTTP-Traffic ist vernachlässigbar.
Ausser Dir hat niemand ein Problem, den SAE so zu verwenden, wie er gedacht ist. Wenn Deine Wünsche auch von anderen User geäussert würden, könnte ich manchem Vorschlag eher etwas Positives abgewinnen. Aber solange der SAE für die meisten User und mich korrekt funktioniert, habe ich wenig Anlass, etwas zu ändern. Da es Open-Source ist, kannst Du jederzeit einen Fork machen oder es mit Pull-Requests versuchen.

**Comment by premultiply** [comment]
Danke, jetzt bin jetzt überzeugt dass du da einen Denk- und damit Implementierungsfehler mit der punktuellen Leistungsmessung und der daraus resultierenden Durchschnittsleistung hast.

Beispiel:
Wenn du alle 30 Sekunden die Leistung misst und dann über 120 Sekunden mittelst und dabei von insgesamt 4 Messwerten einer 1000W (M1) zeigt und die anderen drei 0W (M2-M4) zeigen was ist dann die Durchschnittleistung bzw. wieviel Energie wurde in diesem Zeitraum verbraucht?

M1+M2+M3+M4 * 30s / 120s = 250W ?

Nein! Es gibt keine direkte Lösung da man durch die punktuelle Momentanleistungsmessung keine Aussage über den gesamten Integrationszeitraum treffen kann! Die 1000W könnten z. B. für nur 1 Sekunde genau zum Messzeitpunkt angelegen haben.

Korrekt:
Zählt man aber die Energiemenge im Intervall erhält man diese fehlerfrei direkt in Wh und kann sehr einfach durch Division durch die Zeit die durchschnittliche(!) Leistung im Intervall errechnen.

Reine Mathematik. Die direkte Leistungsmessung ist hier völlig fehl am Platz, da sie nur unbekannte Messfehler produziert und auch noch deutlich komplizierter in der korrekten Anwendung wäre. Aber das geht weit über die Möglichkeiten von asynchroner Software in Verbindung mit billigen Zwischensteckern & Co hinaus.
Mit Messintervallen im Sekundenbereich ist da ohnehin nichts zu machen, da diese gegen 0 gehen müssten um ein halbwegs gescheites Integral zu berechnen bzw. numerisch anzunähern und den verbleibenden Messfehler auf ein erträgliches Maß zu reduzieren.

**Comment by camueller** [comment]
Für stark schwankenden Geräte (oder solche die takten) kann es in der Tat besser sein, mit Energiemengen zu arbeiten. Insofern werde ich die Einschränkung in der Web-Oberfläche wieder aufheben und die Dokumentation anpassen, damit das Verhalten transparenter wird.

**Comment by premultiply** [comment]
Und für die Anderen ist es ausser bei sehr geringen Leistungen in Verbindung mit einem nur grob auflösenden Zähler auch kein Nachteil.

**Comment by camueller** [comment]
Tasmota liefert den Zählerstand ($.StatusSNS.ENERGY.Total)  in kWh mit 3 Nachkommstellen. Bezogen auf die Zeitdifferenz von 60s bedeutet das, dass keine kleinere Leistung als 60W gemessen werden kann! Damit ist die Berechnung der Leistung aus Änderung des Zählerstands wesentlich ungenauer, als die von Dir kritisierte direkte Abfrage mehrerer Leistungswerte mit anschliessender Durchschnittsberechnung.
Ich teste gerade mit einem Lötkolben, der 30W Leistungsaufnahme hat, aber bekomme via Berechnung 60W!
```
2021-02-03 16:51:42,011 DEBUG [http-nio-8080-exec-6] d.a.s.m.PollEnergyMeter [PollEnergyMeter.java:105] F-00000001-000000000002-00: Calculating power from energy: energy=13.518 previousEnergy=13.517 diffEnergy=0.0010000000000012221 diffTime=60
2021-02-03 16:51:42,012 DEBUG [http-nio-8080-exec-6] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:158] F-00000001-000000000002-00: average power = 60W
```

Beim go-eCharger hingegen funktioniert die Berechnung der Leistung aus dem Zählerstand hingegen gut, weil er den Zählerstand in Deka-Wattsekunden !! liefert.

**Comment by premultiply** [comment]
Ich glaube bei mir waren es 5 „Nachkommastellen“.
Ggf. muss man das auch erst konfigurieren.
Ich schaue gleich nochmal zuhause nach.

**Comment by camueller** [comment]
Du hast Recht, man kann mit `EnergyRes` die Genauigkeit auf 5 Nachkommstellen setzen. Default ist 3.

**Comment by premultiply** [comment]
Genau so ist. Du hast die Resolution vermutlich noch auf Standard stehen.
https://tasmota.github.io/docs/Commands/#power-monitoring
Tasmota hat viele verborgene Features...

Mit EnergyRes 5 konfigurierst du die Anzeige und Ausgabe entsprechend um.
Dann klappt das auch mit niedrigen Leistungen ;)

Bei der Gelegenheit kannst du auch VoltRes, AmpRes, PowerRes auch mit anpassen. Wobei ich bis auf CurRes 2 alle anderen auf 0 stehen hab.

Einbinden kannst du es dann direkt wie folgt:

![grafik](https://user-images.githubusercontent.com/4681172/106776741-a3fce000-6644-11eb-8a9d-9312e7e30c2c.png)

RegEx `,\"Total\":((\d*\.)?\d+),` holt dir quasi den Zählerstand ohne die Vorkommastellen in der richtigen Einheit (Faktor 1).
Vielleicht geht das auch noch schöner wenn man vielleicht den Datentyp anpasst. Aber da man hier nur mit der Differenz und Überlauf arbeitet dürften zwischen zwei Abfragen über eine handelsübliche Tasmota-Schokosteckdose wohl kaum mehr als 1 kWh geflossen sein. :)

**Comment by camueller** [comment]
Wobei das Interpretieren als JSON einfacher ist:
```
        <HttpElectricityMeter contentProtocol="JSON">
            <HttpRead url="http://tasmota/cm?cmnd=Status%208">
                <HttpReadValue name="Energy" path="$.StatusSNS.ENERGY.Total" />
            </HttpRead>
        </HttpElectricityMeter>
```
Möglicherweise sollte ich das auf der Tasmota-Seite noch dokumentieren ...

**Comment by premultiply** [comment]
Ach so funktioniert das auch mit dem Path! Ich hab mich schon immer gefragt was man da einträgt...
Ja, Doku und Beispiel dazu wäre sehr gut.

**Comment by camueller** [comment]
`path` wird nur interpretiert, wenn `ContentProtocol`=`JSON` ist. Andere Werte gibt es bisher nicht. Ist damals auch wegen der go-eCharger-Unterstützung entstanden. Man könnte aber auch an XPath oder ähnliches denken.

**Comment by camueller** [comment]
Mit 5 Nachkommstellen sieht die Sache schon besser aus:
```
2021-02-03 17:40:57,542 DEBUG [http-nio-8080-exec-10] d.a.s.m.PollEnergyMeter [PollEnergyMeter.java:114] F-00000001-000000000002-00: Calculating power from energy: power=19 energy=13.53436 previousEnergy=13.53403 diffEnergy=0.00033 diffTime=60
```

**Comment by premultiply** [comment]
Ich denke die Auflösung sollte jetzt reichen, oder? :)

**Comment by camueller** [comment]
Ja, die Auflösung ist ausreichend genau für die Leistungsberechnung :-)

**Comment by premultiply** [comment]
Das Eingabefeld für den JSON-Pfad dürfte bei der Gelegenheit in der WebUI gerne etwas größer werden.

Zu was dient das "Daten"-Feld? Braucht man bei JSON dann auch noch das Feld "Regex für Extraktion"
Auf was würde das wirken? Auf den uninterpretierten HTTP-Content oder auf die "JSON-Path-Value"?

**Comment by camueller** [comment]
Das `Daten`-Feld beinhaltet den Body, falls erforderlich.

Wenn JSON als Format angegeben ist, wird man meist keine Regex benötigen.
Die Regex wird erst angewendet, nachdem der Content-Handler (also hier JSON) den Wert extrahiert hat.

**Comment by camueller** [comment]
Die Auswahloption "Energiemenge" ist jetzt für alle HTTP/Modbus-Zähler verfügbar und in "Zählerstand" umbenannt.

Auch für Modbus-Zähler kann die Leistung aus Zählerstandsdifferenzen berechnet werden.

Das Messinterval gibt es nicht mehr, das `averagingInterval` ist intern fest auf 60s festgelegt entsprechend der Abfragehäufigkeit durch den SHM.

Beim Zählermodus "Zählerstand" erfolgt nur noch alle 60s eine Abfrage des Zählerstandes per HTTP (Poll-Interval fix und nicht konfigurierbar), wobei der SAE die Abfrage so taket, dass die kurz vor der erwarteten Abfrage durch den SHM fertig ist, damit SAE-Messungen und SHM-Messungen möglichst synchron sind. Dieser Zählermodus ist jetzt präferiert - ich habe meine Tasmota-Adapter jetzt alle auf diesen Modus umgestellt, nachdem ich deren Genauigkeit auf 5 Nachkommstellen erhöht habe.

Beim Zählermodus "Leistung" kann nach wie vor das Abfrageintervall vorgegeben werden, wobei die Leistung dann als Durchschnitt der Abfragewerte in den letzten 60s berechnet wird.

Doku muss noch angepasst werden: Tasmota und Zählerauswertung allgemein ...

**Comment by premultiply** [comment]
Klingt gut! Danke!
Im Tasmota-Doku-Teil könnte auch noch ein Hinweis auf den Tasmotizer https://github.com/tasmota/tasmotizer hilfreich sein um die unüberschaubare Masse an preiswerten Schalt-Mess-Steckdosen mit Tasmota zu beglücken.
Ich verwende übrigens überwiegend diese hier mit Tasmota: https://www.amazon.de/-/en/dp/B07TY2BHZM
Preiswert und gut und hält auch wirklich 16A aus.

**Comment by camueller** [comment]
Ich habe überall Gosund SP111, die noch etwas günstiger sind. Allerdings habe ich auch einige von denen an einem Gerät geschrottet (Pumpe vom Hauswasserwerk) - vermutlich wegen Anlaufstromspitzen. Seit einiger Zeit habe ich dort ein Sonoff-Pow ohne Probleme im Einsatz.

**Comment by premultiply** [comment]
Ja, die Anlaufströme von Hauswasserwerkspumpen sind schon nicht ohne.
Aber der letzte Druckschalter hat es auch über 30 Jahre ausgehalten und ist dann - wie sich leider erst nachträglich herausstelle nur durch interne Dreckablagerungen ausgefallen.

**Comment by camueller** [comment]
Implementiert für 1.6.11.
