### ISSUE TITLE
Ergänzung SOC Anleitung und Beispiel für SKODA Connect

### ISSUE THREAD

**Issue by bicaluv** [camueller/SmartApplianceEnabler#134]
Ich habe für unseren Skoda Citigo E iV das Auslesen des SOC umgesetzt.
Das ganze basiert auf https://pypi.org/project/skodaconnect/ mit etwas eigenem Python Code.
Würde diesen und eine Anleitung zur Installation (pip3 + skodaconnect) erstellen, wenn gewünscht.
Hinweis: SKODA Connect (MySkoda) ist bzgl. der Anmeldung etwas schwieriger als VW Connect, deshalb die Lösung über die skodaconnect lib.

**Comment by camueller** [comment]
Dokumentation übernommen.
