### ISSUE TITLE
modbus: Error reading input register

### ISSUE THREAD

**Issue by pwtanagit** [camueller/SmartApplianceEnabler#137]
ich versuche per modbus den Zähler einer KEBA P30c zu lesen.
mit "easymodbusTCP.net" (ein win-tool) geht das (Bsp. holding-register 1020, FC3):
Tx: 00 01 00 00 00 06 01 03 03 FC 00 01
Rx: 00 01 00 00 00 07 01 03 04 00 00 00 00
Register 1020 ist bei KEBA "aktuelle Leistung" 
im SAE gibt's immer ein "General exception - failed to read - Connection reset"
aus dem log:
2021-02-22 15:30:25,167 ERROR [Timer-0] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:273] F-26091964-000000000020-00: Error reading input register 1020
com.ghgande.j2mod.modbus.ModbusIOException: Executing transaction 03 FB 00 00 00 06 01 03 03 FC 00 01 failed (tried 5 times) General exception - failed to read - Connection reset
	at com.ghgande.j2mod.modbus.io.ModbusTCPTransaction.execute(ModbusTCPTransaction.java:182)
	at de.avanux.smartapplianceenabler.modbus.executor.ReadHoldingRegisterExecutor.execute(ReadHoldingRegisterExecutor.java:44)
	at de.avanux.smartapplianceenabler.modbus.ModbusSlave.executeTransaction(ModbusSlave.java:83)
	at de.avanux.smartapplianceenabler.meter.ModbusElectricityMeter.readRegister(ModbusElectricityMeter.java:256)
	at de.avanux.smartapplianceenabler.meter.ModbusElectricityMeter.pollPower(ModbusElectricityMeter.java:211)
	at de.avanux.smartapplianceenabler.meter.PollPowerMeter.addValue(PollPowerMeter.java:79)
	at de.avanux.smartapplianceenabler.meter.PollPowerMeter$1.runTask(PollPowerMeter.java:63)
	at de.avanux.smartapplianceenabler.util.GuardedTimerTask.run(GuardedTimerTask.java:57)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by camueller** [comment]
"Connection reset" klingt danach, dass die Wallbox die Verbindung einfach terminiert.
Ich selbst habe seit fast 2 Jahren eine Wallbox mit Modbus-Ansteuerung im Einsatz und auch der Zähler wird über Modbus ausgelesen.
Allerdings ist mir bisher auch niemand bekannt, der eine Keba-Wallbox mit dem SAE betreibt. Obwohl der SAE schon lange Modbus kann, hatten wir SAE-Interessenten von Keba-Walboxen abgeraten. Die genauen Gründe weiss ich aber nicht mehr.
Für die Modbus-Kommunikation nutze ich eine Bibliothek, d.h. ich habe relativ wenig Einfluss auf die Kommunikation selbst.

**Comment by premultiply** [comment]
Seit wann sprechen Keba-Boxen Modbus?
Die haben nur ein proprietäres UDP-Protokoll.

Nicht das Auslesen von externen Metern DURCH die Keba (als Master) mit dem Auslesen von Daten per Modbus AUS der Keba (als Slave) verwechseln!

https://www.keba.com/file/downloads/e-mobility/KeContact_P30_Datenblatt_DE.pdf
`Kommunikation mit einem externen Stromzähler über Modbus TCP`

**Comment by pwtanagit** [comment]
[kecontactp30modbustcp_pgen.pdf](https://github.com/camueller/SmartApplianceEnabler/files/6024601/kecontactp30modbustcp_pgen.pdf)
seit der letzten firmware 3.10.16 aus 08/2020 geht das

Dok ist in der Anlage.

ich scheitere im SAE bei der Anfrage ans register 1020 scheinbar am Zahlenformat der Antwort
bei KEBA antwortet 1020 als UINT32
in der Anfrage-Konfig hab ich 1/2/4 byte probiert:
1 byte: Fehler float ist 2 oder 4 byte
2 byte: geht, aber ungültige Übersetzung der Werte
4 byte: geht nicht

Peter

**Comment by camueller** [comment]
Dann sollte  der SAE auch mit der Keba-Wallbox funktionieren.
In der Doku steht auf 8, wie die Bytes aufgebaut sind.
UINT32 klingt nach einem 4-Byte -Wert ohne Vorzeichen, Du hast aber scheinbar "FLOAT" probiert.
Für Register 1020 solltest Du stattdessen "INPUTDECIMAL" einstellen und Umrechungsfaktor 1000, weil der Wert in Milliwatt kommt.

**Comment by pwtanagit** [comment]
ich hatte nicht float probiert, sondern bisher nur "Holding"
"holding" wäre der korrekte Registertyp FC3 (Anleitung von KEBA). Die korrekte Anfrage ist:
00 01 00 00 00 06 01 03 03 FC 00 01
wenn ich die Anfrage mit einem ext. Tool stelle, kommt die korrekte Antwort (initialer Post)
mit SAE lässt sich die Anfrage auch exakt so stellen (wenn register-typ = "holding"), nur wird die Antwort dann falsch interpretiert
###########
der Versuch mit "INPUTDECIMAL" war nicht erfolgreich. Die Anfrage ist jetzt bereits falsch:
08 E6 00 00 00 06 01 04 03 FC 00 04 (Registertyp ist 04, soll aber 03 sein)
Im Ergebnis kommt:
2021-02-23 08:41:26,710 ERROR [Timer-0] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:273] F-26091964-000000000020-00: Error reading input register 1020
com.ghgande.j2mod.modbus.ModbusSlaveException: Illegal Function

**Comment by pwtanagit** [comment]
Ich habe mich noch etwas durch die modbus-doku gequält:

ich glaube der Zusammenhang zwischen der Eingabe "bytes" in den SAE-Zähler-modbus-Parametern ist nicht korrekt:
- du hattest vermutlich vor, dort die Antwortlänge einzutragen
- mit Bytes=4 wird aber das letzte byte in der modbus-Anfrage gesetzt, was nicht korrekt ist (dort gehört die Anzahl der abzufragenden Register rein)
- wenn hier (quantity of registers) etwas > 1 steht und der Host dort gültige Register hat, dann geht es auf jeden Fall falsch (denn dann antwortet der Host auch mit den Werten aus mehreren Registern, was SAE kaum verstehen kann)
- die Länge der potentiellen Antwort muss man nicht vor-planen: steht in der modbus-Antwort drin (im Beispiel "04" = 4 byte)
- allerding bliebe das Zahlenformat offen (in der Antwort steht nur ein "byte count", kein Typ)

Vielleicht wäre es eine gute Idee die modbus Parameter zu entkoppeln:
- bytes in den SAE-Parametern umbenennen in "quantity of registers" oder weglassen (gleich mehrere register auslesen wird wohl eher nicht vorkommen bzw. macht es zu komplex)
- noch ein extra-Parameter (bei SAE-modbus), der angibt, welches Zahlformat die Antwort wohl hat (Länge kann man sich sparen, steht ja in der Antwort drin)

gemäß "modbus_application_protocol", Seite 15

(korrekte Anfrage: Quantity of Registers = 1)
Tx: 00 03 00 00 00 06 01 03 03 FC 00 01
Rx: 00 03 00 00 00 07 01 03 04 00 00 00 00

(nicht korrekte Anfrage: "Bytes" wird zu "Quantity of Registers" = 02)
Tx: 00 04 00 00 00 06 01 03 03 FC 00 02
Rx: 00 04 00 00 00 07 01 03 04 00 00 00 00

(nicht korrekte Anfrage: "Bytes" wird zu "Quantity of Registers" = "04")
Tx: 00 05 00 00 00 06 01 03 03 FC 00 04
Rx: 00 05 00 00 00 07 01 03 04 00 00 00 00

beim zweiten und dritten Beispiel gibt es zufällig die gleiche Antwort. Aber nur, weil im KEBA-Fall zufällig die Register 1021,2022,1023 nicht existieren.
[Modbus_Application_Protocol_V1_1b.pdf](https://github.com/camueller/SmartApplianceEnabler/files/6028868/Modbus_Application_Protocol_V1_1b.pdf)
[Modbus_Messaging_Implementation_Guide_V1_0b.pdf](https://github.com/camueller/SmartApplianceEnabler/files/6028869/Modbus_Messaging_Implementation_Guide_V1_0b.pdf)

**Comment by camueller** [comment]
Es sieht so aus, also ob Du richtig liegst. Da ist wohl tatsächlich die Bedeutung von "bytes" etwas durcheinandergeraten.
Ich werde das in den nächsten Tagen mal geradeziehen. Durch meine Wallbox und Modbus-Zähler kann ich dann schon mal erste Tests machen. Danach werde ich Dir dann eine Testversion bereitstellen, wenn Du möchtest.
Das habe ich in der Vergangenheit auch so gemacht mit Features, die ich nicht testen konnte. Das geht schneller, als immer neue Releases zu machen. Ich öffne den Bug hier wieder, da im SAE wohl doch etwas gefixt werden muss :-)

**Comment by pwtanagit** [comment]
schön. gern probiere ich jede frühe Testversion. Meine Umgebung ist docker auf QNAP (AMD64)

**Comment by camueller** [comment]
Ich habe vorhin den Code angepasst und getestet, dass es mit meiner Wallbox und meinem Zähler funktioniert.
Die Test-Version stelle ich Dir morgen nachmittag zur Verfügung.

Der Parameter "bytes" entspricht der Anzahl der Datenwörter, die gelesen werden sollen (den Namen ändere ich noch in "requestWords").
Die Anzahl der gelesenen Datenwörter wird jetzt aus der Modbus-Antwort extrahiert.
Basierend auf der Modbus-Beschreibung Deiner Wallbox habe ich mal die Konfiguration erstellt - die kannst Du in die `Appliances.xml` übernehmen - evtl. funktioniert sie auch direkt. Ich habe gesehen, dass die Wallbox auch einen integrierten Energiezähler hat - den habe ich nachfolgend mit konfguriert, Möglicherweise brauchst Du dann keinen separaten Zähler.
Die Appliance-ID und die Wert für das Fahrzeug musst Du natürlich durch Werte Deines Fahrzeugs ersetzen.
Auch die "idref" des Modbus bei Wallbox und Zähler musst Du durch den Namen ersetzen, den Du bei Dir konfiguriert hast.

```
<Appliance id="F-00000001-000000000002-00">
    <ElectricVehicleCharger>
        <EVModbusControl idref="wallbox" slaveAddress="255">
            <ModbusRead address="1000" bytes="2" type="InputDecimal">
                <ModbusReadValue name="VehicleNotConnected" extractionRegex="(0|1)"/>
                <ModbusReadValue name="Charging" extractionRegex="(3)"/>
                <ModbusReadValue name="Error" extractionRegex="(4)"/>
            </ModbusRead>
            <ModbusRead address="1004" bytes="2" type="InputDecimal">
                <ModbusReadValue name="VehicleNotConnected" extractionRegex="(0|1|3|5)"/>
                <ModbusReadValue name="VehicleConnected" extractionRegex="(7)"/>
            </ModbusRead>
            <ModbusWrite address="5014" type="Holding">
                <ModbusWriteValue name="StartCharging" value="1"/>
                <ModbusWriteValue name="StopCharging" value="0"/>
            </ModbusWrite>
            <ModbusWrite address="5004" type="Holding" factorToValue="1000">
                <ModbusWriteValue name="ChargingCurrent" value="0"/>
            </ModbusWrite>
        </EVModbusControl>
        <ElectricVehicle id="1" name="Nissan Leaf" batteryCapacity="40000" phases="1" maxChargePower="7400" chargeLoss="12"/>
    </ElectricVehicleCharger>
    <ModbusElectricityMeter idref="wallbox" slaveAddress="255">
        <ModbusRead address="1502" bytes="2" type="InputDecimal" factorToValue="1000">
            <ModbusReadValue name="Energy"/>
        </ModbusRead>
    </ModbusElectricityMeter>
</Appliance>
```

In der Datei `logback-spring.xml` solltest Du den Log-Level von "debug" auf "trace" setzen, damit alle Details zur Modbus-Kommunikation geloggt werden:
```
    <logger name="de.avanux" level="trace" additivity="false">
        <appender-ref ref="FILEROLLING" />
    </logger>
```

Die Log-Ausgabe sehen dann u.a. so aus:
```
2021-02-25 20:12:32,044 TRACE [Timer-0] d.a.s.m.e.ReadFloatInputRegisterExecutorImpl [ReadInputRegisterExecutor.java:42] F-00000001-000000000019-00: Reading input register=342 requestWords=2
2021-02-25 20:12:32,171 DEBUG [Timer-0] d.a.s.m.e.ReadFloatInputRegisterExecutorImpl [ReadInputRegisterExecutor.java:57] F-00000001-000000000019-00: Input register=342 value=[17675, 7971]
2021-02-25 20:12:32,173 DEBUG [Timer-0] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:267] F-00000001-000000000019-00: Float value=2225.946044921875
```

**Comment by camueller** [comment]
Ich habe jetzt doch auch die Web-Oberfläche schon angepasst - aus "Bytes" ist "Datenwörter" geworden.
Die `bytes` aus dem obenstehenden XML sollten automatisch in `words` konvertiert werden, d.h. nach einer Änderung in der Web-Oberfläche sollte das so auch in der `Appliances.xml` stehen.

Du kannst die Test-Version hier herunterladen: 
https://drive.google.com/file/d/1oGef7gi5hssGCuU5EYl8pVBGqVGvfxWk/view?usp=sharing

**Comment by pwtanagit** [comment]
(irgendwie klappt bei mir Antworten per email nicht, deshalb verspätet hier)
ich komme irgendwie nicht an die Datei ran?
angeblich im Papierkorb bzw. nicht downloadbar .
![no_download](https://user-images.githubusercontent.com/24277636/109559939-9ddf0f80-7adb-11eb-8da3-b0dd95373a5f.png)
![no_download_2](https://user-images.githubusercontent.com/24277636/109559942-9e77a600-7adb-11eb-98c0-0e52df60f4bd.png)

**Comment by camueller** [comment]
Ich hatte die Datei mehrfach geändert und den Link aktualisiert. Habe den Link auch gerade erfolgreich getestet.
Bitte nochmal probieren ...

**Comment by camueller** [comment]
Du kannst mir gern eine persönliche Mail im PV-Forum senden, dort können wir uns abstimmen und ggf. auf per Videokonferenz (Teams oder Google) und Screen-Sharing eventuelle Problem analysieren und lösen.

**Comment by pwtanagit** [comment]
(habe mich 'pwpv' gerade erst im PV-Forum angemeldet und kann deshalb wohl noch keine PN senden)
so richtig klappt das noch nicht mit modbus. 
die Abfrage ist erstmal sehr reduziert nur auf die aktuelle Leistung
    <Appliance id="F-26091964-000000000020-00">
        <MeterReportingSwitch/>
        <ModbusElectricityMeter idref="wallbox" slaveAddress="255">
            <ModbusRead address="1020" words="1" type="Holding" factorToValue="1000.0">
                <ModbusReadValue name="Power"/>
            </ModbusRead>
        </ModbusElectricityMeter>
    </Appliance>
bekomme immer noch einen Fehler
2021-03-02 15:32:38,991 DEBUG [Timer-0] d.a.s.m.e.ReadFloatHoldingRegisterExecutorImpl [ReadHoldingRegisterExecutor.java:53] F-26091964-000000000020-00: Input register=1020 value=[0, 0]
2021-03-02 15:32:38,991 ERROR [Timer-0] d.a.s.m.e.ReadFloatHoldingRegisterExecutorImpl [ReadFloatHoldingRegisterExecutorImpl.java:48] F-26091964-000000000020-00: Float has to be composed of 2 or 4 bytes!
2021-03-02 15:32:38,991 ERROR [Timer-0] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:273] F-26091964-000000000020-00: Error reading input register 1020
java.lang.NullPointerException: null

**Comment by camueller** [comment]
Ich hatte wohl nicht alles auf die Anzahl der Bytes der Response umgestellt - sollte jetzt gefixt sein.
​Habe die neue Test-Version auf meinen Wallbox-Raspi gespielt - sieht soweit gut aus.
Du kannst sie hier downloaden: https://drive.google.com/file/d/1OqL2aHv8roPoVbit722hGIeJHnVAXc-G/view?usp=sharing

**Comment by pwtanagit** [comment]
probiert. Fehler ist weg. Wert sieht aber noch "komisch" aus:
2021-03-03 18:24:49,722 DEBUG [Timer-0] d.a.s.m.ModbusSlave [ModbusSlave.java:76] F-26091964-000000000020-00: Connecting to modbus wallbox@192.168.2.120:502
2021-03-03 18:24:49,725 DEBUG [Timer-0] d.a.s.m.e.ReadFloatHoldingRegisterExecutorImpl [ReadHoldingRegisterExecutor.java:53] F-26091964-000000000020-00: Input register=1020 value=[63, 65275]
2021-03-03 18:24:49,725 DEBUG [Timer-0] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:267] F-26091964-000000000020-00: Float value=5.877105847056433E-36

wenn ich das manuell abfrage per tool kommt da 00403b33 = 4.209.459 = 4,2kW (und das stimmt: die wallbox steht auf 3x6A)
Tx: 00 01 00 00 00 06 01 03 03 FC 00 01
Rx: 00 01 00 00 00 07 01 03 04 00 40 3B 33

**Comment by premultiply** [comment]
Was glaube ich noch in der neuen Modbus Implementierung fehlt ist eine Konfigurationsmöglichkeit ob der Wert als Big-Endian oder Little-Endian geliefert wird und eine dazu passende Interpretation dazu.
Sieht ansonsten von der Beschreibung her ganz gut aus.

**Comment by camueller** [comment]
Doch, BigEndian/LittleEndian kann ausgewählt werden, sobald words>1 ist.

**Comment by camueller** [comment]
Die Doku aktualisere ich erst, wenn die Änderungen nicht mehr nur in einer Beta-Version sind.

Mit @pwtanagit hatte ich diverse Video-Sessions zwecks Testens von Test-Versionen, um nicht jedesmal eine Version zu releasen um diese dann zu testen. Ohne diese Erkenntnisse, würde es jetzt noch keinen Support für die Keba-Wallboxen im SAE geben.
Jedenfalls ist die Modbus-Ansteuerung im SAE jetzt bereit für weitere Modbus-Geräte, ohne das dafür an der Implementierung etwas geändert werden muss.

**Comment by camueller** [comment]
Gefixt mit 1.6.12.
