### ISSUE TITLE
REQUEST: Energie-Überschuss als S0 Signal an GPIO ausgeben

### ISSUE THREAD

**Issue by phlupp** [camueller/SmartApplianceEnabler#138]
Hintergrund: ich habe hier eine ältere Remko Wärmepumpe die noch nicht SG-Ready ist, aber die hat einen S0-Eingang. Laut Remko sollte man hier einen Zähler mit S0-Ausgang hinter dem Wechselrichter anbringen, die Wärmepumpe würde dann den Energiebedarf an die PV-Leistung anpassen.
Das ist aber, wie ich finde, eine sehr schlechte Lösung, da dabei alle anderen Verbraucher vernachlässigt würden und die Wärmepumpe die ganze Solarleistung abgreifen würde.

Daher die Frage: Überschüßige PV-Leistung als S0-Signal an einem GPIO ausgeben.  

Die MyPV Heizstäbe holen ja auch den PV-Überschuss aus dem SEMP Protokoll, dann müsste das doch hier auch gehen.

Danke
PS: Das ganze ist ein spitzen Projekt und läuft sonst auch tadellos, großes Lob!

**Comment by premultiply** [comment]
Die dazu notwendigen Echtzeitdaten stehen per SEMP quasi nur sehr indirekt zur Verfügung.
Man müsste dazu die Leistungsempfehlungen cachen und Minutenweise in schön gleichmäßig verstreute Impulse umwandeln.

Vermutlich bist du da mit einem kleinen Microcontroller (Arduino, ESP usw.) und direkter Nutzung der Speedwire-EM-Multicasts des SHM besser bedient. Dort kann man direkt den Erzeugungszählerstand des SHM als OBIS-Code in Echtzeit abgreifen um damit bei jeder neuen erzeugten Wh dann einen entsprechenden Impuls auszugeben.

**Comment by camueller** [comment]
Der SAE ist ein SEMP-Gateway. Dazu gehört nicht die Aufgabe, die PV-Leistung als S0-Signal bereitzustellen. Insofern schliesse ich dieses Issue.
