### ISSUE TITLE
dynamical update of timeframes

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#14]
It would be very important for me to have the opportunity to update the timeframes dynamically.
Especially for heatpumps the runtime have to be update very often depending on temperatures. Atm. I have to restart SAE every 30min until Heatpump starts.
Please make it possible to change timeframes without restarting SAE eg. sending a special kill signal to re-read Appliance.xml again. It is important that the Switch state is not changed during re-read.

**Comment by camueller** [comment]
Using a HTTP-Request is more flexible than re-reading Appliance.xml. The HTTP request would have to contain **all** timeframes of the appliance. They would replace the timeframes currently set.

**Comment by camueller** [comment]
Siehe auch
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1390712.html#p1390712
