### ISSUE TITLE
SAE Umzug

### ISSUE THREAD

**Issue by martinez81** [camueller/SmartApplianceEnabler#140]
Hi!

mein SAE läuft seit gut 9 Monaten auf meinen Raspberry, manuell istalliert, also nicht im Docker.
Ich bin total zufrieden.

Jetzt habe ich einen Intel NUC (Ununtu 20.04) wo ich nach und nach alle, oder so viele Anwendungen wie möglich, drauf packen möchte.
(Es haben sich einen Raspberry angesammelt, das kostet langsam richtig Strom :) )
Wenn ich den SAE auf meinen NUC installiere und meine beiden Config Dateien (Device2EM.xml und Appliances.xml) auf die neue Maschine kopiere, wird das Sunnyportal, oder vielmehr der HomeManager 2.0 das einfach so annehmen? Bleiben meine Geräte im Sunnyportal so wie vorher vorhanden?

Oder gibt es einen anderen Backup und Restore Ablauf?

Gruß
Martin

**Comment by camueller** [comment]
Einfach die beiden XML-Dateien auf das neue System kopieren. Der SHM und das Sunny Portal merken von dem Umzug nichts.
