### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Trunks1982** [camueller/SmartApplianceEnabler#142]
Hi Axel,
Ich versuche schon seid stunden deine standard installation, genauso vor.Er boot auch so wie er soll aber ne installation sehe ich da nicht bzw wird nichts installiert.
Kann es sein das sich da irgendwo nen Fehler eingeschlichen hat?

**Comment by camueller** [comment]
Dann hast Du irgendetwas anders gemacht, als in der Anleitung geschrieben. Mehr kann ich dazu leider nicht sagen.
An der Installation hat sich seit der Dokumention nichts geändert und es gab bisher nur positives Feedback.

**Comment by Trunks1982** [comment]
Hi leider nein.Ich probiere gerade die manuelle installation mal aus.Die standard installation ist ja eigentlich total simple.

Gruß Christoph
