### ISSUE TITLE
Add possibility to add custom HTTP header fields

### ISSUE THREAD

**Issue by nanosonde** [camueller/SmartApplianceEnabler#144]
Some Restful APIs require additional HTTP header fields, e.g. for authorization.

An example: https://developers.home-assistant.io/docs/api/rest/

Besides the` Content-Type` it requires "`Authorization: Bearer <myToken>`" to be set to be able to successfully authenticate.

**Comment by camueller** [comment]
SAE does only support basic authentication.
You can use a HTTP proxy to handle other authentication schemes or supply these additional header fields.

**Comment by henne49** [comment]
Hi, I had the same idea to use http to trigger switches in Home-assistant, which would make the Smart Appliance Enabler able to trigger pretty much any IoT Device supported in home-assistant, as well as sensor information. I know the topic is closed, but can you comment on how to use a http proxy with sae outbound from sae to an iot broker like home-assistant?

Any hint would be very much appreciated.

**Comment by camueller** [comment]
Using an HTTP proxy is not related to SAE. I'm afraid you have to do the research yourself ...
