### ISSUE TITLE
Neue Geräte lassen sich nicht speichern

### ISSUE THREAD

**Issue by JensNK** [camueller/SmartApplianceEnabler#147]
Ich habe kürzlich den SAE installiert. Er läuft in einem Container eines QNAP-NAS. Es handelt sich um die Version 1.6.12. Wenn ich ein neues Gerät anlegen will kann ich zwar auf speichern klicken, jedoch tut sich nichts weiter, außer dass der Button ausgegraut wird. Im Status erscheint das Gerät auch nicht. Ich habe bereits versucht die Adblocker zu deaktivieren und verschiedene Browser ausprobiert.

Beim Container-Abbild handelt es sich um  _avanux/smartapplianceenabler-amd64:latest_

Der Netzwerkmodus steht auf Bridge, so dass der SAE seine eigene IP-Adresse bekommt.

Ein neues Anlegen des Container half auch nicht weiter.

Mein Ziel ist es, einen Sonoff Pow R2 mit Tasmota, im Sunny Portal einzubinden, um die Poolpumpe steuern zu können.
Im Anlagenlogbuch wird der SAE offenbar gefunden: 

_24.05.2021 01:42:26 | Home Manager 2 450 | EM-Gateway gefunden: SEMP, Name: SmartApplian_

Ich bitte um Hilfe :)

**Comment by camueller** [comment]
Was soll denn noch passieren? Das Gerät wurde gespeichert und deshalb wir der Button ausgegraut.
Im Status erscheinen nur Geräte, die steuerbar sind. Dazu muss für das Gerät ein Schalter angelegt werden.

**Comment by JensNK** [comment]
Es erscheint kein neues Gerät nach dem Speichern, für das ich einen Schalter, Zähler oder Sonstiges anlegen könnte. Ich klicke auf Speichern, das Feld wird ausgegraut (so wie es sein soll), aber mehr passiert eben nicht. Auch nicht nach Aktualisieren der Oberfläche.

![grafik](https://user-images.githubusercontent.com/26568599/120099532-4123dd00-c13c-11eb-80d4-c6fa0d2d74f5.png)

So schaut es nach Anlegen eines Gerätes weiterhin aus. Als wären keine Eingaben getätigt worden.

**Comment by camueller** [comment]
Es gibt automatische Tests, die das Anlegen von Geräten via Browser testen. Der Fehler liegt also nicht im SAE, sondern in Deinem Setup.
Ich vermute, dass der SAE keine Schreibrechte hat für das Verzeichnis, in dem er die XML-Dateien anlegen will. Aber das kannst Du in den Log-Dateien prüfen.

**Comment by stevoboy** [comment]
@camueller @JensNK Gibt es mittlerweile eine Lösung für das Thema? Ich stehe aktuell gerade vor dem gleichen Problem.
Der Container läuft als Bridge oder Host und referenziert auf einen Ordner auf der Synology:

![image](https://user-images.githubusercontent.com/84937873/187093362-ef71898c-4ecf-4c1c-8cb0-91f5ee24335c.png)

Dem Ordner habe ich alle möglichen Berechtigungen gegeben:
![image](https://user-images.githubusercontent.com/84937873/187093471-c87dd776-9112-4f82-a8ee-fd9a4671e13f.png)
 
Trotzdem werden Geräte nicht gespeichert und es tauchen auch keine Konfigurationsdateien auf:
![image](https://user-images.githubusercontent.com/84937873/187093493-5b2c4978-3966-4db9-966e-1d79d5abcea8.png)

![image](https://user-images.githubusercontent.com/84937873/187093524-551252f6-8bd1-48a6-a079-d51973fced9a.png)

Die Log Dateien würde ich gerne prüfen, wenn ich wüsste, wie ich an sie herankomme. Evtl. über das Terminal?

Für Eure Hilfe bedanke ich mich.

**Comment by camueller** [comment]
Es gibt SAE-seitig (1.6.20 und 2.0.5) kein Problem mit dem Speichern. Wenn Du andere Erfahrungen machst, dann liegt das an Deinem Setup.

**Comment by stevoboy** [comment]
Ja, das vermute ich auch. Ich habe  wenig Erfahrung, wie man das speichern von Konfigurationsdateien außerhalb eines Containers umsetzt. Ich vermute es liegt am Pfad oder Ordnertyp. 
Daher wäre die Hilfe von Jens wertvoll, leider hat er nicht geschrieben, wie er es gelöst hat.

**Comment by camueller** [comment]
Das steht doch in der [Docker-Dokumention](https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md), wie das Volume erstellt und verwendet wird.

**Comment by stevoboy** [comment]
Ok, die habe ich erst nicht angeschaut, weil ich das Docker Image direkt aus der Synology starten konnte.

Ich bin jetzt beim Schritt SAE via Systemd beim Systemstart zu starten. Da komme ich nicht weiter - das Create command wird nicht erkannt:

![image](https://user-images.githubusercontent.com/84937873/187250972-322056fd-af3d-4372-ab17-beadb3775272.png)

Der Punkt hinter dem Befehl in Github ist ein Typo, oder?

P.S. Ich probiere parallel noch mal den Ansatz "Direkte Interaktion mit Docker-compose" aus.

**Comment by camueller** [comment]
Meine Dokumentation bezieht sich auf `docker` und `docker-compose`. Ob und wie man das mit Synology & Co. zum Laufen bringt muss der User selbst rausfinden.

**Comment by stevoboy** [comment]
Kennst du jemanden, der das schon mal erfolgreich geschafft hat? Das würde mir schon mal weiterhelfen.

**Comment by camueller** [comment]
Ich verfolge nicht, wer welches Nicht-Standard-Setup hat, da ich nur Standard-Setup supporte.

**Comment by stevoboy** [comment]
Okay, trotzdem danke.

**Comment by stevoboy** [comment]
@camueller Hallo Axel, gestern Nacht bin ich ein gutes Stück schlauer geworden und zum Glück weitergekommen. Ich habe allerdings den Portainer Docker für die Einrichtung genommen. Das war für mich irgendwann einfacher - meine MS DOS Zeiten sind lange vorbei und mit Linux habe ich mich noch nicht intensiv beschäftigen können.
Ich kann nun Geräte anlegen, die vom SHM erkannt werden und in der SHM Energy App angezeigt werden.
Ich schreibe auch gerne eine Doku für die Iobroker User, falls Du Interesse hast. 

Jetzt soll testweise der Verbrauch einer Fritzsteckdose ausgelesen und im SHM erkannt werden.
Dazu verwende ich Simple API im Iobroker um die Datenpunke per HTTP Json bereitzustellen. 

Unter der NAS IP (192.168.x.y) kann ich die Wattzahl per Get-Befehl "http://192.168.x.15:8087/get/0_userdata.0.0_Test" anzeigen:

`{"val":5,"ack":true,"ts":1662269569377,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1662269392800,"common":{"name":"0_Test","desc":"Manuell erzeugt","role":"state","type":"number","read":true,"write":true,"def":0},"type":"state","native":{},"_id":"0_userdata.0.0_Test","acl":{"object":1636,"state":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}`

Im SAE (IP http://192.168.x.100:8087) habe ich Folgendes gepflegt:
Typ: HTTP
Format: JSON
URL: http://192.168.x.15:8087/get/0_userdata.0.0_Test
Parameter: Zählerstand
Methode: Get
Pfad für die Extraktion: $.val

Leider sehe ich in der SMA Energy App keinen Verbrauch. hast Du spontan eine Idee, woran es liegt?
Ich habe das Beispiel noch einmal vereinfacht.

**Comment by camueller** [comment]
Du schreibst, dass obiger GET-Befehl die "Wattzahl" liefert, aber als Parameter konfigurierst Du "Zählerstand". Schon beim Lesen merkt man, dass das so nicht stimmen kann. Wenn Du also die Wattzahl bekommst, dann musst Du als Parameter auch "Leistung" einstellen anstatt "Zählerstand"!

Ansonsten solltest Du im Log prüfen, was der SAE mit dem Wert Deines Zählers macht. Siehe https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/HttpMeter_DE.md#log

**Comment by stevoboy** [comment]
> Du schreibst, dass obiger GET-Befehl die "Wattzahl" liefert, aber als Parameter konfigurierst Du "Zählerstand". Schon beim Lesen merkt man, dass das so nicht stimmen kann. Wenn Du also die Wattzahl bekommst, dann musst Du als Parameter auch "Leistung" einstellen anstatt "Zählerstand"!

Stimmt, aber das Verhalten bei der Eingabe von "Zählerstand" und "Leistung" ist identisch - es wir immer 0 W angezeigt.

Gerätwechsel auf Geschirrspüler bringt bisher auch nichts. 

Das Protokoll wird auch nicht gefunden mit folgendem Befehl:
grep 'Http' /tmp/rolling-2022-09-04.log | grep F-19820110-000000000002-00

Ich schaue noch mal, ob ich irgendwo einen Ordner mit den Protokollen finde, aber in der Nähe der Konfigurationsdateien, die in /volume2/@docker/volumes/sae/_data liegen, konnte ich sie bisher nicht entdecken.

Gerade habe ich auch noch einmal die Variante mit dem regulären Ausdruck versucht, leider erfolglos:
![image](https://user-images.githubusercontent.com/84937873/188318701-d6a3d834-196e-4834-971f-1b6521a0b35b.png)

![image](https://user-images.githubusercontent.com/84937873/188318751-b2890a85-6d26-4438-aeb9-8bb78f43c1a1.png)

![image](https://user-images.githubusercontent.com/84937873/188318867-29ebafb0-8dfe-447c-a42e-bd14f511c043.png)

![image](https://user-images.githubusercontent.com/84937873/188318953-57d00a12-54e6-4ac0-b27f-1f8a7f683958.png)

**Comment by camueller** [comment]
Wenn man den SAE im Container alufen lassen will, sollte man sich auch etwas mit Containern auskennen. Der SAE schreibt seine Log-Files nach /tmp, Du brauchst also nicht im SAE-Volume zu suchen. Mach doch einfach eine Shell im SAE-Container auf und schau Dir das Log-File an. Steht alles in der Docker-Dokumentation zum SAE ...

**Comment by stevoboy** [comment]
Okay, sorry für meine Unfähigkeit. Zu diesen Details in Sachen Docker bin ich noch nicht gekommen. Dein Tipp hat aber geholfen. Ich habe das Log im Portainer gefunden. Dies sind die 3 Log-Einträge, die sich ständig wiederholen (IP-Adresse anonymisiert):

```
2022-09-04 20:53:13,877 DEBUG [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:78] F-19820110-000000000005-00: HTTP request: method=GET url=http://192.168.x.x:8087/get/0_userdata.0.0_Test data=null
2022-09-04 20:53:16,884 ERROR [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:114] F-19820110-000000000005-00: Error executing GET request.
2022-09-04 20:53:16,884 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:90] F-19820110-000000000005-00: url=http://192.168.x.x:8087/get/0_userdata.0.0_Test method=GET data=null path=$.val
```

**Comment by camueller** [comment]
Die zweite Zeile ist eine ERROR-Eintrag, da solltest Du prüfen, was da schief läuft.

**Comment by stevoboy** [comment]
Also ich habe jetzt mal einen Fall mit einem Internet Json Server hinbekommen, wo es läuft. Im SEMP Protokoll wird der Wert angezeigt ebenso in der SMA App.
Vom gleichen Server aber andere Seite wiederrum klappt es nicht. 

**Klappt:**
https://httpbin.org/response-headers?key=val
![image](https://user-images.githubusercontent.com/84937873/188512088-44de27ea-6cc0-4179-a000-d85c2bc0576a.png)
![image](https://user-images.githubusercontent.com/84937873/188512114-f015f6ba-e18c-4425-8ac0-4cf96e618425.png)

**Klappt nicht**
https://httpbin.org/get
![image](https://user-images.githubusercontent.com/84937873/188512143-e1ca8024-d3c7-40f3-a38f-4747e726138e.png)
![image](https://user-images.githubusercontent.com/84937873/188512184-7536d9ff-8199-456b-8518-f6a4310b5373.png)

**Comment by camueller** [comment]
Ich bezweifle, dass die 85 Watt bei "Klappt" der korrekte Wert für die Leistung ist, wenn Du es als  "Content-Length" aus der Response extrahierst.

**Comment by stevoboy** [comment]
Wie meinst Du das? Das ist doch nur ein fixer Testwert, mit dem ich nachweisen konnte, dass der SAE JSON Werte bei mir erfolgreich importieren kann und an den SHM erfolgreich weiterreicht.
