### ISSUE TITLE
Support: Zeitpläne über REST-API werden nicht eingeplant

### ISSUE THREAD

**Issue by nheyser** [camueller/SmartApplianceEnabler#149]
Hallo zusammen,

ich verwende Version 1.6.13 mittels Docker. Das planen von Zeitsplänen mittels WebUI funktioniert sehrt gut, ich würde die Zeitpläne jedoch gerne dynamisch mittels REST von OpenHAB übergeben:

Wenn ich z.B. die folgenden Request via REST abschicke:

`<Schedules xmlns="http://github.com/camueller/SmartApplianceEnabler/v1.6" enabled="true">`
`<Schedule enabled="true">`
`                <RuntimeRequest min="2700" max="10320"/>`
`                <DayTimeframe>`
`                    <Start hour="7" minute="17" second="0"/>`
`                    <End hour="10" minute="9" second="0"/>`
`                </DayTimeframe>`
`            </Schedule>`
`            [... 3 weitere]`
`</Schedules>`

Erhalte ich folgende DEBUG-Log Einträge:

`DEBUG [http-nio-192.168.1.4-8082-exec-1] d.a.s.w.SaeController [SaeController.java:449] F-xxxxxxxx-100000000001-00: Received request to activate 4 schedule(s)`
`DEBUG [http-nio-192.168.1.4-8082-exec-5] d.a.s.w.SaeController [SaeController.java:166] Received request for ApplianceHeaders`
`DEBUG [http-nio-192.168.1.4-8082-exec-5] d.a.s.w.SaeController [SaeController.java:176] Returning 4 ApplianceHeaders`
`DEBUG [http-nio-192.168.1.4-8082-exec-2] d.a.s.w.SaeController [SaeController.java:963] Received request for Info`
`DEBUG [http-nio-192.168.1.4-8082-exec-3] d.a.s.w.SaeController [SaeController.java:854] Received request for ApplianceStatus`

In der Web-UI kann ich die neuen Zeitpläne sehen, d.h. die kommen im SAE an.

In der SEMP-XML steht aber "EMSignalsAccepted" weiterhin auf false und die PlanningRequests sehe ich auch nicht.

`<DeviceStatus>`
`<DeviceId>F-xxxxxxxx-100000000001-00</DeviceId>`
`<EMSignalsAccepted>false</EMSignalsAccepted>`

VG Niklas

**Comment by camueller** [comment]
Ich nutze das Feature nicht selbst und weil dafür offensichtlich keine Unit-Tests existieren, ist das schon vor längerer Zeit kaputt gegangen. Habe es gefixt für Version 1.6.15.
