### ISSUE TITLE
Subdevice Handling

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#15]
The handling of subdevice works fine, except the power reporting.
It would be great to report the power  measured by "energymeter" to the main or sub device which is switched on. Currently it is possible to configure the SubDevice to a "estimated" power but if both devices are "on", the power will be doubled. It means if the main and subdevice is on, the SAE needs to report the power on the main device an 0 for the subdevice.

**Comment by camueller** [comment]
Siehe
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1371073.html#p1371073
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1371130.html#p1371130
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1390025.html#p1390025
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1390870.html#p1390870
- http://www.photovoltaikforum.com/geraete-mit-home-manager-koppeln-via-semp-ethernet-p1390928.html#p1390928
