### ISSUE TITLE
Bei dem speichern von Änderungen werden alle Geräte abgeschaltet 

### ISSUE THREAD

**Issue by rolsch** [camueller/SmartApplianceEnabler#150]
Hallo,
ich beschreibe hier mal einen Umstand der nicht so ideal realisiert wurde.

Ich nutze einige Tasmota-Schalter die u.a. Waschmaschine/Trockner usw. schalten.

Wenn ich nun bei einem der Geräte eine Konfigurationsänderung vornehme
werden beim speichern der Änderungen ALLE Geräte abgeschaltet.

Dies ist unschön da z.B. der Trockner nicht mehr selbstständig anläuft
wenn dessen Schalter manuell über die Ampel aktiviert wird.

Vielleicht könne dieses Verhalten in einer zukünftigen Version angepasst werden.

**Comment by camueller** [comment]
Da ist leider so. Da Änderungen an der Konfiguration eher die Ausnahme sind, lohnt sich der Aufwand nicht, dafür alles umzubauen.
