### ISSUE TITLE
Anlaufstromerkennung funktioniert für HTTP Zähler vom Typ "Zählerstand" nicht

### ISSUE THREAD

**Issue by Nightstalker81** [camueller/SmartApplianceEnabler#151]
Das Gerät startet, wird aber nicht nach der definierten Anlaufstromerkennung aber nicht unterbrochen.

Habe den Quellcode vom "StartingCurrentSwitch" einmal quer geprüft und es scheint mir so, dass die Methode "onPowerUpdate" (und somit auch das Hinzufügen von Strommessungen über die Methode "addPowerUpdate") nicht aufgerufen wird.
Dies führt in Folge dazu, dass keine Einträge in der Variable "powerUpdates" des "StartingCurrentSwitch" vorhanden sind und somit der Anlaufstrom niemals erkannt wird.

**Comment by camueller** [comment]
Gefixt für 1.6.17.

Voraussetzung dafür ist allerdings, dass die Genauigkeit des Zählerstandes ausreichend hoch ist. Bei Adaptern mit Tasmota-Firmware muss dazu die Genauigkeit auf 5 Nachkommastellen erhöht werden (siehe https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Tasmota_DE.md).
