### ISSUE TITLE
Unterstützung für HTTP Meters/Switches für einfache BEARER Authentifizierung mittels "Long Running Tokens"

### ISSUE THREAD

**Issue by Nightstalker81** [camueller/SmartApplianceEnabler#152]
Ich gehe davon aus, dass ein Großteil der Nutzer, die den SAE einsetzt auch eine "Home Automation" Zentral (z.B. Home Assistant, OpenHAB, FHEM, etc.) einsetzt.
Bei diesen Systemen werden die Sensoren/Schalter teilweise über APIs zur Verfügung gestellt, für die eine BEARER Authentifizierung notwendig ist.
Dies lässt sich aktuell im SAE leider nicht umsetzen.

Konkretes Szenario ist wie folgt:
Ich besitze eine "Home Assistant" Installation, die über eine API (siehe [REST API](https://developers.home-assistant.io/docs/api/rest/)  und [AUTH API](https://developers.home-assistant.io/docs/auth_api/)) diverse Funktionen zur Interaktion mit der "Home Automation Zentrale" ermöglicht.
Hierfür ist es allerdings notwendig, dass ein "Long Running Token" mittels BEARER Authentifizierung mitgegeben wird.
Diese Konfiguration lässt sich aktuell nicht durchführen, sodass beim Aufruf eines Request der "Home Assistant" mit 401 (Unauthorized) antwortet.

**Comment by camueller** [comment]
Die meisten User verwenden keine Home-Automation - ich auch nicht.
Für Dein Szenario kann man einen Reverse-Proxy vorschalten.
Oder die Security deaktivieren.
Spezielle Authentifizierungen sind nicht Bestandteil des SAE.
