### ISSUE TITLE
Wallbe ECO Box mit Energiezähler - aktuelle Leistung

### ISSUE THREAD

**Issue by TGuybrush** [camueller/SmartApplianceEnabler#153]
Ich versuch die aktuelle Ladeleistung der Wallbe Wallbox ECO mit angeschlossenem Energiezähler zu lesen.
Die richtigen Modus Parameter sind:
- unsigned int 32 bit big endian word swap
- Länge 2
- Adresse 120

Bei deen Zähler Einstellung kann ich zwar integer wählen aber bei Byte Reihenfolge nur litle oder Big endian.
Ist die Konfiguration unter diesen Umständen möglich?

**Comment by camueller** [comment]
Falls noch nicht geschehen, solltest Du unbedingt auf die aktuelle Beta-Version des SAE 1.6.15 wechseln, weil ich den Modbus-Code nach der letzten "offiziellen" Version komplett konsolidiert habe. Damit sollte das Auslesen des Zählers klappen. Zunächst musst Du den richtigen "Function Code" einstellen. Danach kannst Du mit den anderen Parametern "spielen", bis die richtige Ziffernfolge ausgelesen wird. Danach kannst Du ggf. noch mit dem Umrechnungsfaktor das Komma verschieben, bis es passt.

**Comment by TGuybrush** [comment]
Danke für die schnelle Antwort :-) 
Ich habe die neuste Version installiert 1.6.15, ( da steht aber nichts von Beta). 

Laut Logfile wird der richtige Wert, circa 3500 vom Modus Register 120 empfangen. 
Leider erscheint als Leistung aber immer 0W? Als Format ist "integer" eingestellt, d.h. irgendwie scheint er den Wert nicht zu verstehen oder richtig zu übernehmen?

> 2021-06-24 20:36:28,564 DEBUG [Timer-0] d.a.s.m.ModbusSlave [ModbusSlave.java:77] F-10000000-000000000001-00: Connecting to modbus MB_Wallbe@192.168.178.27:502
> 2021-06-24 20:36:28,590 DEBUG [Timer-0] d.a.s.m.e.ReadInputRegisterExecutor [ReadInputRegisterExecutor.java:56] F-10000000-000000000001-00: Input register=120 value=[3550]
> 2021-06-24 20:36:48,566 DEBUG [Timer-0] d.a.s.m.ModbusSlave [ModbusSlave.java:77] F-10000000-000000000001-00: Connecting to modbus MB_Wallbe@192.168.178.27:502
> 2021-06-24 20:36:48,594 DEBUG [Timer-0] d.a.s.m.e.ReadInputRegisterExecutor [ReadInputRegisterExecutor.java:56] F-10000000-000000000001-00: Input register=120 value=[3530]
> 2021-06-24 20:36:56,459 DEBUG [http-nio-8080-exec-1] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:173] F-10000000-000000000001-00: average power = 0W
> 2021-06-24 20:37:08,566 DEBUG [Timer-0] d.a.s.m.ModbusSlave [ModbusSlave.java:77] F-10000000-000000000001-00: Connecting to modbus MB_Wallbe@192.168.178.27:502
> 2021-06-24 20:37:08,605 DEBUG [Timer-0] d.a.s.m.e.ReadInputRegisterExecutor [ReadInputRegisterExecutor.java:56] F-10000000-000000000001-00: Input register=120 value=[3513]
> 2021-06-24 20:37:10,388 DEBUG [http-nio-8080-exec-4] d.a.s.m.ModbusElectricityMeter [ModbusElectricityMeter.java:173] F-10000000-000000000001-00: average power = 0W

**Comment by camueller** [comment]
War denn die Ladeleistung zu dem Zeitpunkt ca. 3,5 kW? Irgendwie kann ich aus Deinem Log gar nicht erkennen, dass der Zahlenwert interpretiert wird ...

**Comment by TGuybrush** [comment]
Ja richtig z.B. 3513 am Ende des Logs  aus dem Register 120.
Ich sehe das der richtige Wert aus dem Modus Register gelesen wird, aber nicht richtig umgerechnet wird.

**Comment by camueller** [comment]
Bei Dir findet aus irgendwelchen Gründen keine Wert-Transformation statt. Das muss im Log eigentlich so aussehen (bei Dir fehlt die zweite Zeile):
```
2021-05-05 00:00:53,738 TRACE [Timer-0] d.a.s.m.e.ReadInputRegisterExecutor [ReadInputRegisterExecutor.java:42] F-00000001-000000000019-00: Reading input register=342 requestWords=2
2021-05-05 00:00:53,791 DEBUG [Timer-0] d.a.s.m.e.ReadInputRegisterExecutor [ReadInputRegisterExecutor.java:56] F-00000001-000000000019-00: Input register=342 value=[17691, 4690]
2021-05-05 00:00:53,792 DEBUG [Timer-0] d.a.s.m.t.FloatValueTransformer [FloatValueTransformer.java:32] F-00000001-000000000019-00: transformed value=2481.14501953125
```
Was hast Du denn als "Wert-Typ" eingestellt? Kannst Du mal aus der `Appliances.xml` den Abschnitt `<Appliance ...` für Deine Wallbox posten?

**Comment by TGuybrush** [comment]
Ich hatte "integer" eingestellt. Wenn ich "float als integer" wähle scheint es zu gehen. Mir ist allerdings nicht klar was das bedeuten soll, da ich auch in der Doku dazu nichts finden kann.
