### ISSUE TITLE
overnight planning broken

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#16]
It is not possible to plan devices for nightly use (e.g. for night electricity tariff)
If you plan a device from 6pm to 8am SAE report only a Internal Error 500

**Comment by Maverick78de** [comment]
Reopen, see http://www.photovoltaikforum.com/sma-anlagenueberwachung-f48/geraete-mit-home-manager-koppeln-via-semp-ethernet-t104060-s620.html

**Comment by camueller** [comment]
Using LocalTime/LocatDateTime instead of Instant.
