### ISSUE TITLE
Standard Installation wird nicht ausgeführt

### ISSUE THREAD

**Issue by Flo2kk** [camueller/SmartApplianceEnabler#161]
Hallo Herr Camueller, 

ich habe heute versucht über die Standart Installation die Applikation zu installieren ,leider funktioniert dies nicht.

Image wurde geschrieben mit Pi Imager
Raspberry  4 Startet  danach wird der usb Stick mit den drei Dateien eingesteckt Raspberry Startet neu und Rote LED leuchtet konstant.

anbei ein Bild vom Bildschirm dieser ist nach dem Boot Vorgang dauerhaft zu sehen. 
 
![de7fc3e3-00e7-4a8b-82d8-bdc5b09ab7c4](https://user-images.githubusercontent.com/91492723/134958988-99195566-27cb-4126-bde3-3952add2b081.jpg)

die install.config install.sh install2.sh lade ich mit Rechtsklick und verknüpfte Dateien herunterladen auf meinen MAC 
 
Dateien zum Testen in Original aufgespielt dies macht keinen unterschied.

was mache ich falsch oder liegt dort ein Problem vor ? 

Danke für Ihre Hilfe

**Comment by camueller** [comment]
Die Installation wurde intensiv getestet und seitdem nicht verändert. Insofern liegt das Problem nicht an der Installation sondern an Ihrem Setup oder SD-Karte. Ggf. die manuelle Installation durchführen. Oder im Forum nachfragen.

**Comment by camueller** [comment]
Java wird nicht installiert ...

**Comment by camueller** [comment]
Ich habe ein neues RaspiOS-Image erstellt, mit dem die Installation wieder funktioniert:

https://github.com/camueller/RaspiOSImageAutorunUSBShellScript/releases/tag/2021.05.07-lite
