### ISSUE TITLE
HttpElectricityMeter verwendet GET anstatt POST

### ISSUE THREAD

**Issue by bunnu** [camueller/SmartApplianceEnabler#162]
SAE läuft bei mir als Docker-Container auf einem Ubuntu-Server. Aktuell setze ich das Image avanux/smartapplianceenabler-amd64:1.6.16 ein.

Im Sommer (ungefähr) August habe ich sowohl das Betriebssystem, als auch das Docker-Image aktualisiert. Seit diesem Zeitpunkt funktioniert bei mir nicht mehr die Anlaufstromerkennung. Ich hatte nun Zeit mir das genauer anzuschauen.

Der Zähler ist folgendermaßen konfiguriert:
![image](https://user-images.githubusercontent.com/5147219/135679150-88c3d5e8-2165-4cff-8889-d2b5096d711f.png)

Die Abfrage via Postman funkioniert problemlos.

Im Log von SAE finde ich nun folgendes:

```
sae    | 21:59:53.417 [Timer-0] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request GET /smartplug.cgi HTTP/1.1
sae    | 21:59:53.418 [Timer-0] DEBUG org.apache.http.headers - http-outgoing-141 >> GET /smartplug.cgi HTTP/1.1
sae    | 21:59:53.418 [Timer-0] DEBUG org.apache.http.wire - http-outgoing-141 >> "GET /smartplug.cgi HTTP/1.1[\r][\n]"
sae    | 21:59:53.460 [Timer-0] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request GET /smartplug.cgi HTTP/1.1
sae    | 21:59:53.461 [Timer-0] DEBUG org.apache.http.headers - http-outgoing-141 >> GET /smartplug.cgi HTTP/1.1
sae    | 21:59:53.461 [Timer-0] DEBUG org.apache.http.headers - http-outgoing-141 >> Authorization: Digest username="admin", realm="SP2101W", nonce="2a2ef9185c647ee05785cc7840191269", uri="/smartplug.cgi", response="db542e8d497754d3a7fbb16af1ad2fa0", qop=auth, nc=00000001, cnonce="ebdd7508f3b6c06a", algorithm=MD5
sae    | 21:59:53.461 [Timer-0] DEBUG org.apache.http.wire - http-outgoing-141 >> "GET /smartplug.cgi HTTP/1.1[\r][\n]"
sae    | 21:59:53.461 [Timer-0] DEBUG org.apache.http.wire - http-outgoing-141 >> "Authorization: Digest username="admin", realm="SP2101W", nonce="2a2ef9185c647ee05785cc7840191269", uri="/smartplug.cgi", response="db542e8d497754d3a7fbb16af1ad2fa0", qop=auth, nc=00000001, cnonce="ebdd7508f3b6c06a", algorithm=MD5[\r][\n]"
``` 

Wieso schickt SAE statt POST- einen GET Request? 

Ich habe noch einen älteren Log-Auszug aus dem letztem Jahr, in dem SAE mit der gleichen Konfiguration POST-Requests geschickt hat:
```
2020-11-27 11:30:05,763 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:86] F-20130830-000000000002-00: url=http://192.168.178.4:10000/smartplug.cgi httpMethod=POST data=<?xml version="1.0" encoding="UTF8"?><SMARTPLUG id="edimax"><CMD id="get"><NOW_POWER><Device.System.Power.NowCurrent></Device.System.Power.NowCurrent><Device.System.Power.NowPower></Device.System.Power.NowPower></NOW_POWER></CMD></SMARTPLUG> path=null

```

**Comment by camueller** [comment]
Bei der Konsolidierung des Codes habe ich wohl verdrängt, dass man auch beim Lesen des Zählerstandes über HTTP andere HTTP-Methoden als GET verwenden könnte. Man kann das jetzt entsprechend konfigurieren.
Ich habe das gefixt und eine Version zum Testen für Dich gebaut:

https://drive.google.com/file/d/17LWxRSqJqxMtkSSPlYSUayHej_6jaUd7/view?usp=sharing

Bitte Rückmeldung, ob das für Dich funktioniert ...

**Comment by bunnu** [comment]
Vielen Dank! Ich habe die war-Datei im Container ausgetauscht. Die Anlaufstromerkennung funktioniert nun, nachdem ich in den Einstellung das Verb von GET auf POST geändert habe 👍

**Comment by camueller** [comment]
Danke für die Info. Der Fix ist dann in der nächsten Version enthalten.
