### ISSUE TITLE
Adapter for ioBroker on NAS & Virtuell Device

### ISSUE THREAD

**Issue by stevoboy** [camueller/SmartApplianceEnabler#169]
Dear Axel

thanks a lot for creating this very promising adapter. 
I was recommended to it when searching for a solution on how to get energy consumption values into Sunny Home Portal when using Fritz DECT 200 in combination with a 3-phase heat pump/stove. Today this is impossible as the Fritz does not know the actual power consumption, as the energy consumption is not going through it directly.

From the photovoltaikforum I learned that your SAE plus S0- oder Modbuszähler might be the solution.
However, I am running iobroker on a Synology NAS and would not want to build up an Raspberry PI in addition and secondly, I have the approximate power consumption in my NAS already from Siemens Homeconnect and other sources. Is there a way in you adapter to create virtual device that can be fed with the power consumption instead of using any hardware?

Thanks a lot for your help

Steffen

**Comment by camueller** [comment]
Yes, you may configure a "HTTP Meter" in Smart Appliance Enabler in order to retrieve enery meter counter or power value and feed it as power consumption via SEMP for Sunny Home Manager.
Smart Appliance Enabler provided a localized User Interface for English, but only if you don't have US locale set in your browser.

**Comment by stevoboy** [comment]
Hello Axel,

So this Http meter can be fed with values from data points and can also be triggered by shm switch on/off commands?

Is your sae only available on raspberry pi or also on docker Iobroker? I would not want to start up a rp infrastructure in addition to our NAS.

**Comment by stevoboy** [comment]
Hello Axel,

So this Http meter can be fed with values from data points and can also be triggered by shm switch on/off commands?

Is your sae only available on raspberry pi or also on docker Iobroker? I would not want to start up a rp infrastructure in addition to our NAS.

**Comment by camueller** [comment]
The HTTP meter only reports to SHM. If you want  SHM to control a dvice you have to configure a Control in Smart Appliance Enabler.

SAE is available as docker container for AMD64 and ARM32.

I'm afraid you have to use Google translator or something similar in order to translate the documentation from German since there was no use for an english translation so far.

**Comment by stevoboy** [comment]
Hallo Axel,

ich spreche Deutsch habe nur aus Gewohnheit bei GIT Hub in Englisch gepostet.

Also den Container habe ich jetzt gefunden und im Docker meiner NAS installiert, soweit alles okay.
Ich bin noch nicht ganz durch mit der Durchsicht der Dokumentation und anderen Posts, daher evtl. zwei blöde Fragen...
a) Wie stellt der SAE den Kontakt zum Sunny Home Portal Konto her? Dazu müssen doch irgendwo Zugangsdaten des Portals eingegeben werden damit der SAE bidirektional mit dem Sunny Home Portal / SHM kommuniziert.
b) Die relevanten Datenpunkte (Verdichter=Wärmepumpe an/aus, SG Green Modus an/aus, SG Red Modus an/aus) liegen in meinem ioBroker Container. Wie kann der SAE darauf zugreifen?

Das Gerät Wärmepumpe ein/aus im SAE wird im ioBroker ja über den Datenpunkt SG Green ein/aus repräsentiert und muss angesteuert werden können. In die andere Richtung, wenn Verdichter an dann Stromverbrauch = 4 kwh >>> Anzeige im Sunny Home Portal.
Das Ganze müsste also in die beide Richtungen funktionieren - Ansteuerung des SG Green Datenpunkts im ioBroker und Rückmeldung des Stromverbrauchs  im Sunny Home Manager wenn der Verdichter läuft.

**Comment by camueller** [comment]
Ich nutze ioBroker nicht. Bitte alle Fragen zu SAE im Forum stellen: https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet

**Comment by stevoboy** [comment]
In diesem Thema ist meine Basisfrage wohl zu sehr Off-Topic. Wo wird das Erstsetup über einen Docker Container denn beschrieben?

**Comment by camueller** [comment]
Auf der Projekt-Seite hier bei Github findet sich ein grosse Docker-Logo. Wozu ist das wohl dort platziert?
Für persönlichen Support fehlt mir die Zeit, insofern werde ich hier auf keinen weiteren Post vor Dir antworten.
Falls Du kommerziellen Support von mir wünschst, können wir gern darüber reden.

**Comment by stevoboy** [comment]
Danke, ich werde mir selbst helfen.
