### ISSUE TITLE
Allow for post-processing of data sent to SHM

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#17]
Dabei hat man Zugriff auf alle Variablen (Verbrauch, Schaltzustand etc.) und kann auch das Gerät schalten.

Mein Ziel bei der Entwicklung von SAE besteht darin, kommunikationsunfähige Geräte via SEMP in den SHM zu integrieren. Bislang kann der SAE lediglich messen und schalten, aber keine höherwertigen Konzepte des Gerätes an den SHM kommunizieren. Das möchte ich verbessern, damit meine 12 Jahre alten Wärmepumpe (ca. 4 kW Stromaufnahme) ohne SmartGrid-Features trotzdem meinen Solarstrom (9,4 kWP) bestmöglichst nutzt. Die WP wurde bisher mit WP-Tarif betrieben und konnte vom EVU über ein Schütz abgeschaltet werden. Diese Abschaltmöglichkeit möchte ich vom SAE aus nutzen, d.h. wenn der SHM den Befehl "DeviceControl=On" schickt, dann soll der SAE via Schütz die E-Sperre aufheben. Umgekehrt soll die E-Sperre aktiviert werden, wenn der SHM den Befehl "DeviceControl=Off" schickt.
Derzeit taktet die WP nicht häufig (was gut für die Lebensdauer des Kompressors ist), d.h sie ist immer ca. 45-60 Minuten an und danach für ca. 30-60 Minuten aus. Die Kontrolle über die Laufzeit des Kompressors möchte ich bei der WP-Steuerung belassen, d.h. während die WP an ist, soll der SHM auch keinen Abschaltbefehl schicken. Das kann ich durch Senden von "EMSignalsAccepted=false" erreichen. Dazu muss der Raspberry aber erkennen, wann die WP läuft. Das will ich durch ein kleines USB-Netzteil lösen, das mit Strom vom Kompressor-Schütz versorgt wird, d.h. es liefert 5V, solange der Kompressor läuft. Diese 5V kann ich von einem GPIO-Eingang des Raspberry auswerten und darauf basierend den Wert von "EMSignalsAccepted" setzen.
Für die Wärmepumpe würde ich einen "PlanningRequest" bestehend aus EINEM Timeframe mit earliestStart=8:00 und latestEnd=23:00 sowie minRunningTime=maxRunningTime=8h erstellen. Ab 8 Uhr würde der SHM dann ein DeviceControl=On senden, falls genug PV-Strom vorhanden ist. Wegen "EMSignalsAccepted=false" würde die WP bis zur Abschaltung durch die WP-Steuerung laufen, unabhängig davon, ob durchgängig genug PV-Strom da ist. Nach der Abschaltung durch die WP-Steuerung kann der SHM wieder ein DeviceControl=on/off schicken. Falls er DeviceControl=on schickt, kann die WP entsprechend der WP-Steuerung nach 30-60 Minuten wieder anlaufen usw..
Falls den ganzen Tag über kein PV-Strom vorhanden ist, würde der SHM spätestens um 15 Uhr ein DeviceControl=On schicken, damit die Wärmepumpe bis 23 Uhr ihre 8 Stunden Laufzeit hatte.

**Comment by Maverick78de** [comment]
Mache es doch wie ich, übergehe die komplette interne Steuerung der WP. 
OneWire Temperatursensor in die WP und an den Raspi. Über den Leistungsfaktor usw die benötigte Laufzeit zum erreichen der Ziel Temperatur berechnen und einplanen inkl 1x die Woche Legionellenaufheizung. Das Schalten machst du dann ganz einfach über ein Relais. Alle 5min läuft die Temperaturabfrage/-Berechnung bis zum Start durch den SHM.
Ich habe eine MinRuntime von 1h und dann 20min Off in SAE definiert. funktioniert tadellos.
