### ISSUE TITLE
Keine Telegram Notifications in 2.0.1 Docker

### ISSUE THREAD

**Issue by c0ldtech** [camueller/SmartApplianceEnabler#171]
Ich übernehme einfach mal mein Problem, das ich schon im Forum beschrieben habe:

Ich bin bei Version 2.0.1. Seit Update auf 2.0.0 bekomme ich keine Benachrichtigungen in Telegram mehr. Das notifyWithTelegram.sh Script liegt weiterhin am korrekten Ort und ist auch so in der Oberfläche von SAE einbgepflegt. Chat ID und Absender stimmen (haben sich ja auch nicht geändert). Ein manueller Aufruf des curl Befehls im Script führt auch zum Versand einer Nachricht, so weit passt also eigentlich alles.

Nur der Versand bei Ein- oder Ausschalten eines Gerätes funktioniert nicht, obwohl er in den Einstellungen des Gerätes weiterhin aktiviert ist.

Zurück auf 1.6.18 funktionieren die Benachrichtigungen sofort wieder.

Das sind die letzten Einträge, die vom NotificationHandler habe:

```
2022-01-22 17:35:07,213 DEBUG [Thread-4] d.a.s.n.NotificationHandler [NotificationHandler.java:53] F-xxxxxxxx-000000000005-00: command=/opt/sae/data/notifyWithTelegram.sh senderId=xxxxxxxxx:xxxxxxxxxxxxxxxx maxCommunicationErrors=10

2022-01-22 17:35:07,213 DEBUG [Thread-4] d.a.s.n.NotificationHandler [NotificationHandler.java:66] F-28091980-000000000005-00: enabled notifications [CONTROL_ON, CONTROL_OFF]
```

Wenn ich Version 1.6.18 benutze, kommen über 200 Zeilen später im Log noch die Einträge

```
2022-01-22 17:45:20,182 DEBUG [http-nio-8080-exec-4] d.a.s.n.NotificationHandler [NotificationHandler.java:100] F-28091980-000000000002-00: Checking notification preconditions: errorCountPerDay=0

2022-01-22 17:45:20,184 DEBUG [http-nio-8080-exec-4] d.a.s.n.NotificationHandler [NotificationHandler.java:107] F-28091980-000000000002-00: Executing notification command: /opt/sae/data/notifyWithTelegram.sh

2022-01-22 17:45:20,404 DEBUG [http-nio-8080-exec-4] d.a.s.n.NotificationHandler [NotificationHandler.java:122] F-28091980-000000000002-00: Notification command exited with return code 0

```

Die fehlen mir in Version 2.0.1

**Comment by camueller** [comment]
Wie schon im Forum geschrieben, funktionieren bei mir die Notifications über Telegram unverändert auch in SAE 2.x (ohne Docker).
Du betriebst ja den SAE im Docker-Container und das bedeutet, dass sich die Images unterscheiden zwischen SAE 1.6 und SAE 2.0! Schau Dir doch mal die Container an - irgendwo muss ein Unterschied sein.
Ich werde in die nächste 2.x-Version ein paar zusätzliche Log-Meldungen einbauen, aber das wird für Dich erstmal nichts ändern. Ansonsten hat das Thema kurzfristig für mich keine hohe Prio, weil die Funktionalität gegeben ist, wie ich bereits geschrieben habe.

**Comment by c0ldtech** [comment]
Das ist in Ordnung, ich wollte es nur der Vollständigkeit halber hier mal vormerken. Eventuell findet sich ja noch jemand, der das Problem auch hat(te). 

Das Docker Image ist natürlich das Offizielle, und wurde komplett neu gezogen. Ich könnte natürlich auch versuchen, nur das WAR file zu tauschen? Oder handele ich mir da ein anderes Problem ein?

An sich hat es ja auch für mich keine hohe Priorität, da mit 1.6.x ja (noch) alles läuft.

Danke nochmal für die viele Mühe! Und mehr Logging ist immer gut.

**Comment by c0ldtech** [comment]
Noch ein Nachtrag: mit der 2.0.1 (in Docker) habe ich auch das Phänomen, dass die Ampel nicht den tatsächlichen Zustand widerspiegelt. Die Anlaufstromerkennung hat zum Beispiel gegriffen und die Ampel ist auf gelb. Klicke ich nun auf grün und starte das Gerät, startet das Gerät auch tatsächlich (nur eben ohne Telegram Benachrichtigung), aber die Ampel steht weiterhin auf gelb.

Hilft das eventuell? Hast Du noch eine Idee, in welche Richtung ich noch schauen könnte?

Ich habe auch schon einen anderen MQTT Server verwendet, weil das ja auch noch eine große Änderung zwischen den beiden Versionen ist - leider ohne Änderung.

Ich kann auch gerne mal mein Log schicken, falls Du da mal draufschauen willst und Zeit hast. Da ja die 1.6.18 bei mir ohne Probleme auch in Docker läuft, ist es aber nicht dringend.

**Comment by camueller** [comment]
Das von Dir beschriebene Ampel-Verhalten habe ich nicht in der 2.0.1 - die Ampel zeigt normal grün an nach dem Klick auf Start. Auch die Anlaufstromerkennung funktioniert normal.

Versuche doch erstmal die 2.0.1 ohne Docker, wenn sie nicht in Docker bei Dir funktioniert. Ich habe die 2.0.1 produtiv laufen für 10 Geräte, das sollte also auch bei Dir so sein. Wenn man Probleme hat, sollte man immer erstmal unnötige Komplexitätsgrade (Docker) rausnehmen. Wie schon geschrieben, hat das Problem für mich keine hohe Prio und ich habe wenig Lust dazu, mir immer wieder vermeintliche SAE-Probleme anzusehen, die eigentlich auf die Umgebung und nicht den SAE selbst zurückzuführen sind.

**Comment by c0ldtech** [comment]
Ich will damit gar nicht drängeln - als letzte Lösung werde ich mit 2.0.1 auch auf dedizierte Hardware gehen, falls es nicht anders läuft. Ich hatte nur Infos beisteuern wollen, die eventuell einen Hinweis geben woran es liegt.

Deine Arbeit ist super und ich bin froh dass es den SAE gibt - dass ich dich damit anscheinend nerve, war nicht beabsichtigt.

Die Docker Lösung finde ich sehr elegant, da sie eben keine extra Hardware erfordert und leicht auf- und abzubauen und zu updaten ist. Raspberrys habe ich aber auch noch ein oder zwei herumliegen, die ich für eine dedizierte Installation benutzen könnte. Es ist also wie gesagt nicht dringend.

Sobald ich mal etwas Zeit habe, werde ich die Installation auf dedizierter Hardware schon allein deshalb ausprobieren, um Probleme mit meinem MQTT Server (oder Anderes) auszuschließen.

**Comment by camueller** [comment]
Du brauchst keine extra Hardware kaufen, dafür baue ich ja die Docker-Images für arm32 und amd64. Mein Problem ist, dass ich kaum noch Zeit für echte Weiterentwicklung habe, weil so viel Zeit für Support draufgeht. Deshalb muss ich priorisieren und hoffe, dass mir User auch mal konkrete Lösungsvorschläge machen und nicht nur ihr Problem und ihre Logs rüberwerfen.

Du hast ein funktionierendes 1.6-Setup und ein nicht funktionierendes 2.0-Setup. Das ist perfekt geeignet zum Analysieren, aber dafür muss man Zeit investieren. Da würde ich mir wünschen, dass Du das machst, weil ich denke, dass Du das vom Know-How her kannst. Meine Zeit ist auch knapp und deshalb kümmere ich mich in erster Linue um Probleme, die alle betreffen (ist bei Docker nicht der Fall) oder die mich persönlich betreffen (da muss ich gleich nach dem Schreiben dieses Post an eines ran, das aktuell auf meinem Pre-2.0.2-Stand dazu führt, dass falsche Leistungswerte berechnet werden, wenn der HTTP-Request zum Zähler fehlschlägt).

**Comment by c0ldtech** [comment]
Ist alles nachvollziehbar - wie gesagt, ich wollte nicht damit nerven. Hätte ja sein können, Du hast direkt einen heißen Tip oder jemand Anderes hat das Problem auch.

Wenn es Arbeit und Familie zulassen, setze ich mich mal dran und versuche, dem Ganzen auf die Schliche zu kommen. Muss mich dann erstmal einarbeiten, wie ich das Projekt selbst bauen kann um zu testen, und wie ich ggfs. ein Docker Image neu erstelle.

**Comment by camueller** [comment]
Du brauchst nicht das Projekt bauen. Es reicht, wenn Du von jedem der beiden Images einen Container erzeugst. Dann kannst Dir ja in jedem der beiden Container eine Shell erzeugen und Dich dort umsehen. Welche Files liegen da? Welche Permissions haben die? ...

**Comment by c0ldtech** [comment]
Ich hab mir jetzt erstmal angesehen, was auf dem Mqtt Broker so passiert. Ich sehe dort topics wie "sae/DeviceID/Meter" für jede meiner Tasmota Steckdosen, aber ansonsten nur "sae//will" mit Inhalt "unexpected error".
Du hattest ja im release geschrieben, dass die interne Kommunikation jetzt über Mqtt läuft, da wäre es vermutlich fatal, wenn mit Mqtt etwas nicht passt. Ich wollte mir mal die im Log oft auftauchende "MqttClient.java" anschauen - aber die finde ich nicht im Repo. Ich nehme an, die ist nicht von dir? Könnte es eventuell sein, dass dem Docker Image schlichtweg eine Bibliothek oder Ähnliches fehlt? Dagegen spräche allerdings, dass im Log keine entsprechenden ClassNotFound Exceptions zu sehen sind...
Das ist jetzt auch nur ins Blaue geraten, aktuell fehlt mir noch der Einblick um da auch nur annähernd qualifizierte Kommentare abgeben zu können.

**Comment by c0ldtech** [comment]
Einen Schritt bin ich weiter, zumindest was den "unexpected error" angeht. Ich hatte einen meiner Tasmota Stecker, den ich nur zum Auslesen des Stromverbrauchs verwendet habe, folgendermaßen konfiguriert:

```
<HttpRead url="http://tasmotaplug07/cm?cmnd=Status%208">
<HttpReadValue name="Power" extractionRegex=".*&quot;Power&quot;:(\d+).*"/>
</HttpRead>
```

Das hatte bisher zu keinen mir bekannten Problemen geführt. Jetzt führt es aber zu den genannten Einträgen im Broker, und im Log zu einer NumberFormatException, da das Parsen des Strings nicht funktioniert. Ich hab das jetzt umgestellt auf JSON (hatte ich für alle Anderen Tasmota Plugs schon länger gemacht). Ich konnte das in der GUI nicht machen (speichern funktionierte dann auch nicht), musste es direkt in der XML erledigen.

Seitdem ist das Ampel-Verhalten anscheinend auch wieder korrekt. Eine Benachrichtigung bekomme ich leider trotzdem noch nicht, aber eins nach dem Anderen. :)

Edit: Leider zu früh gefreut, nach einer Weile werden die "unexpected error" wieder mehr und sind irgendwann die Mehrheit der meldungen im Broker, und Änderungen speichern in der GUI kann ich immer noch nicht. Ich suche weiter...

**Comment by camueller** [comment]
Die "sae/will" fallen in der nächsten Version wieder raus und haben nichts zu sagen.

Sämtliche Java-Bibliotheken sind im `SmartApplianceEnabler*.war` enthalten, auch die für die MQTT-Kommunikation. 

Bei Tasmota solltest Du den "Zählerstand" auslesen, und nicht "Leistung". Außerdem solltest Du das als JSON auslesen und nicht mit Regex. Steht alles in der [Doku und gilt für SAE 1.6.x und 2.x](https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Tasmota_DE.md).

**Comment by c0ldtech** [comment]
Das mit "Zählerstand" habe ich gestern Abend auch noch geändert - JSON war schon eingestellt, bis auf einen Tasmota Stecker (wie weiter oben beschrieben). Ich musste die Änderungen unter 1.6 machen, da Drücken des "Speichern" Knopfes in der GUI von 2.0.1 bei mir keinen Effekt hatte.
Das hat zu einem (für mich) interessanten neuen Verhalten geführt. Während mit den Änderungen 1.6 weiterhin normal funktioniert hat und ich im Log auch schön die neue Berechnung der Durchschnittswerte beobachten konnte, klappte das in 2.0.1 nicht. Dort hat sich SAE jede Minute beschwert, dass der "Energy Cache" leer wäre (ich vermute, da werden die ausgelesenen Zählerstände zur Berechnung abgelegt?). Anscheinend kann er sich also die ausgelesenen Werte nicht merken, und dadurch natürlich auch keinen Mittelwert/Leistung ermitteln.
Ich vermute dass alle meine Probleme eine gemeinsame simple Ursache haben, aber zu dem Zeitpunkt war es schon spät und leider habe ich heute einen langen Kundentermin...

**Comment by camueller** [comment]
Ich habe das Problem analysiert: Bei HTTP-Schaltern werden bei SAE 2.0.x tatsächlich keine Benachrichtigungen verschickt, unabhängig von Docker! Mir war es nicht aufgefallen, weil ich die Geräte, von denen ich Benachrichtigungen bekomme, nicht mit HTTP schalte, sonder via GPIO.
Habe den Fix sogar in Docker getestet - kommt mit SAE 2.0.2.

**Comment by c0ldtech** [comment]
Super, danke! Ich konnte leider bisher nicht nochmal selbst danach schauen, danke dass Du Dir die Zeit genommen hast.
