### ISSUE TITLE
build SmartApplianceEnabler-*.jar 

### ISSUE THREAD

**Issue by TexHex23** [camueller/SmartApplianceEnabler#19]
Beim bauen der SmartApplianceEnabler-*.jar bekomme ich mit maven immer wieder einen Fehler.
Der Fehler taucht auf beim surefire in der Datei webservice.SaeController.xml
die Datei habe ich angehangen, wäre sehr dankbar wenn mir jemand das Problem erklären könnte bzw mir sagt was ich falsch mache, Danke.

[de.avanux.smartapplianceenabler.webservice.SaeControllerTest.txt](https://github.com/camueller/SmartApplianceEnabler/files/845814/de.avanux.smartapplianceenabler.webservice.SaeControllerTest.txt)

[surefire report.txt](https://github.com/camueller/SmartApplianceEnabler/files/845827/surefire.report.txt)

**Comment by camueller** [comment]
Der SAE lässt sich fehlerfrei bauen, was durch https://travis-ci.org/camueller/SmartApplianceEnabler überwacht wird.
