### ISSUE TITLE
Make ip adress configurable

### ISSUE THREAD

**Issue by bunnu** [camueller/SmartApplianceEnabler#24]
My host  has several ip addresses. Make the the ip address on which SAE is listening for requests configurable.

**Comment by camueller** [comment]
Ich antworte mal auf Deutsch ...
Was genau meinst Du mit "my host"? Das Raspberry Pi hat nur ein Netzwerkinterface (= 1 IP-Adresse).
Der SAE "lauscht" ja nur auf Requests vom Web-GUI, bei Schaltern und Zählern initiiert er die Verbindung (kein Listen).

**Comment by bunnu** [comment]
Hi Axel,

ich habe bei mir zu Hause einen Linux-Server laufen, auf dem nun auch SAE läuft. Da ich rein über Edimax SP-2101W messe und schalte, reicht mir das. Dieser Host hat mehrere Interfaces. SempDiscovery "detektiert" in der Methode findMyIpAddress() eine für meinen Fall falsche IP-Adresse.
Wenn man als Alternative zum detektieren auch eine Setting verwenden könnte, wäre das wahrscheinlich auch der erste Schritt um UPnP im Docker zum Laufen zu bekommen.

Übrigens: Entgegen der Doku (https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/EdimaxSP2101W_DE.md) funktioniert SAE bei mir mit der Firmware 2.08 und Digest-Authentifizierung einwandfrei.

**Comment by camueller** [comment]
Dazu ist keine Code-Änderung notwendig: Du kannst in der Datei /etc/default/smartapplianceenabler einfach die folgende Zeile hinzufügen und die IP-Adresse entsprechend setzen:

JAVA_OPTS="${JAVA_OPTS} -Dserver.address=192.168.178.33"

Die Dokumentation werde ich entsprechend anpassen.

**Comment by camueller** [comment]
Die SempDiscovery hatte ich in der Tat übersehen. Allerdings bedingt das eine Code-Änderung, aber jetzt sind IP-Adresse und Port konfigurierbar: https://github.com/camueller/SmartApplianceEnabler/compare/ev...server_port_configurable?expand=1

Über die Weihnachtstage werde ich das offizielle 1.3er-Release bauen und diese Änderung wird darin enthalten sein.
