### ISSUE TITLE
Unterstützung "Erzeugungsgeräte"

### ISSUE THREAD

**Issue by asonkel** [camueller/SmartApplianceEnabler#250]
Ist es angedacht evtl. auch zukünftig Geräte zu unterstützen welche Strom erzeugen?
Bsp. BHKW oder auch Wechselrichter ?
Da das ganze im SMA Verbund gesehen über das Sunny Portal teilwese Sinn machen würde wenn z.B, eine bereits installierte Anlage erweitert wird oder alte Komponenten ausgetauscht werden.
So wäre die korrekte Erzeugungs- und Verbrauchsübersicht sowie Steuerung der Verbraucher im SMA Portal gewährleistet.

**Comment by camueller** [comment]
Nein, der SAE ist darauf beschränkt, was das SEMP-Protokoll von SMA bietet.
