### ISSUE TITLE
Feature Request -  SmartApplianceEnabler als ioBroker Adapter

### ISSUE THREAD

**Issue by Tombra1889** [camueller/SmartApplianceEnabler#257]
Verlagerung des Projekts in einen ioBroker Adapter.

Vorteile wären:
 - Integration in die Backup Prozesse
 - Einfacheres Update des Adapters
 - ggf. einfachere Verknüpfung mit Datenpunkten in den Objekten

Nachteile stelle ich gerne zur Diskussion :)

**Comment by camueller** [comment]
SAE wir keinen dedizierten Support für eine spezielle Integrationsplatform wie iobroker bereitstellen.
