### ISSUE TITLE
Projekt Überschussladen

### ISSUE THREAD

**Issue by Call777** [camueller/SmartApplianceEnabler#267]
### Discussed in https://github.com/camueller/SmartApplianceEnabler/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **Call777** May 12, 2022</sup>
Hallo,
ich heiße Stefan und ich möchte mehr Strom aus meiner PV Anlage nutzen, deshalb würde ich gerne folgendes Projekt umsetzten.
Ein Schichtpeicher mit 2 stufenlosen, regelbarer Heizstäben und einer Leistung von jeweils maximal 3KW soll bei Überproduktion der PV Anlage das Wasser erhitzen.
Ebenso soll ein E-Auto bei Überproduktion geladen werden.
Das Ganze am besten Vollautomatisch oder bei Bedarf manuell steuerbar. Ich habe bereits Kontakt zu einer Installationsfirma aufgenommen und basieren auf meinem Wechselrichter von SMA wurde auch eine Lösung, die auf dem Home Manager aufbaut, aufgezeigt.
Die Firma baut auf dem Übertragungsprotokoll  SEMP auf, was die Auswahl der Hardware (Heizstab und Wallbox) doch sehr einschränkt und zudem noch recht teuer ist.
Bezüglich des E-Autos wird sich die Hardware in absehbarer Zeit wieder ändern, weil ich auf das Bidirektionale Laden von VW setzte, was auch ausschlaggebend  für den Kauf des Fahrzeugs war.
VW hat mir zugesichert das dies 2022 startet aber ein ganz anderes Equipment erfordert als es heute am Markt üblich ist.
Da ich nicht weiß wann es schlussendlich losgeht und diese Hardware kosten wird, das E-Auto aber im August/September eintrifft,  suche ich nach einer Übergangslösung fürs Auto und einer Lösung für die Heizstäbe.
Da bin ich auf dieses Forum gestoßen und es ließt sich so, als sollte das funktionieren.
Den Home Manager von SMA werde ich auf jeden Fall einbauen lassen.
Ich bin leider, was Linux angeht, vollkommener Laie und bin mir auch nicht sicher ob ich das so ans Laufen bekomme wie einige hier im Forum.
Benötigen tue ich als erstes wahrscheinlich ein Raspberry, mein Nas von Synology kann die Aufgabe nicht übernehmen?
Die Ersteinrichtung erfolgt wahrscheinlich direkt über das Rapberry, kann man nach der Installation dann über das Netzwerk darauf zugreifen oder muss man immer vor Ort an dem Raspberry arbeiten?
Als Heizstab ginge ja dann ein Model was PWM gesteuert ist und direkt an das Raspberry angeschlossen wird?
Ich dachte an die Version EHS-R von der technischen Alternative oder ginge auch ein normaler Heizstab und die Regelung übernimmt die Steuerung?
Welche Wallbox wäre am geeignetsten um stufenlos zu laden? 
Wie gesagt bin ich kein PC Neuling aber habe doch Respekt vor diesem Projekt und möchte Fragen ob ich hier im Forum Unterstützung bekommen kann oder es besser lassen sollte?
Wenn jemand aus dem Postleitzahlengebiet 666 hier unterwegs wäre und sich damit auskennt wäre das natürlich super.
Ich hätte kein Problem eine Firma damit zu beauftragen aber erstens ist es sehr schwierig überhaupt jemanden zu finden, der dieses Jahr noch Zeit hat aber was viel schwieriger ist, das sich jemand mit solchen Steuerungen auskennt.
Vielen Dank vorab und Gruß Stefan.

</div>

**Comment by camueller** [comment]
Fragen werden via Support gelöst.
