### ISSUE TITLE
Jährlicher Gültigkeitsbereich für Tages-Zeitpläne

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#27]
Die Möglichkeit, Schedules zu (de)aktivieren ist ja schon sehr schön, noch schöner wäre aber eine Erweiterung mit einem Zeitraum, während dem ein Schedule aktiv ist (Start- und Endedatum).

Nutzanwendung:
Ich lasse meine BWWP Morgens und Abends jeweils eine Stunde laufen, um Warmes Wasser zum Duschen etc. sicher zu stellen. Die komplette Aufheizung erfolgt ab dem späten Vormittag. 
Meine BWWP ist bivalent, ich kann sie also auch mit der Gasheizung aufheizen. In den dunklen Monaten möchte ich nun die Aufheizung am Morgen und an Abend über die Gasheizung laufen lassen und tagsüber über den dann (hoffentlich) vorhandenen PV-Strom.
Ich habe schon ein Gerät im SAE angelegt, mit dem ich die Heizung ansteuern kann.
Wenn ich also die Schedules am Morgen und am Abend bei der BWWP z.B. auf den Zeitraum 1.3. ... 31.10. eingrenzen könnte und die der "Heizung" vom 1.11. ... 28.2., hätte ich einen vollautomatischen Betrieb über das ganze Jahr.

**Comment by ok64sh** [comment]
**Ergänzung zu Deiner Idee mit den Gültigkeitsbereichen der Tages-Zeitpläne.**

Idee:
Zeitpläne mit Namen und Aktivierung/Deaktivierung per REST-Schnittstelle.

Nutzung:
Ich nutze den SAE für meine (Sole-)Wärmepumpe, eine 15 Jahre alte Viessmann Vitocal 300G mit 1000ltr Heizungswasser-Pufferspeicher, die bisher immer störungsfrei und ohne Wartungskosten lief und im monovalenten Betrieb das Haus mit Warmwasser und Heizung versorgt.
Die Ansteuerung der WP mache ichüber den EVU-Sperrkontakt, der ansonsten nicht benötigt wird, da ich mit ganz normalem Tagstrom heize und daher auch  keine Sperrzeiten vom EVU auferlegt bekomme.

Um Strom zu sparen und den Eigenverbrauch der PV-Anlage (19kWPeak) zu optimieren, schalten diese Schedules die Heizung von abends bis morgens früh komplett aus (also WP und zwei Heizungkreis-Umwälzpumpen). Als erstes läuft dann morgens in der Früh die Heizungspumpe für die Bäder wieder an (mit Rest-Wärme aus dem Pufferspeicher). Die Wärmepumpe darf dann erst später dazu, meist gemeinsam mit der zweiten Heizkreispumpe (für Wohnzimmer/Essbereich). Die Wärmepumpe wird auch meist vor den Heizungs-Pumpen wieder gesperrt.

Das funktioniert natürlich je nach Witterung unterschiedlich gut, weshalb ich für die drei Komponenten (WP und beide Pumpen) jeweils mehrere Zeitprofile definiert habe (für extreme Minusgrade bleibt alles fast über die ganze Nacht an, in der Übergangszeit nur Morgens bis Abends, im Sommer nur für Brauchwasser im reinen Überschussbetrieb.
Bei Witterungswechsel suche ich mir dann für alle drei Schaltvorgänge das jeweils am besten zur erwarteten Aussentemperatur passende Zeitprofil aus und aktiviere es.

Cool wäre daher jetzt, wenn man...

1. Den Zeitprofilen Namen geben könnte
2. Das "Sahnehäubchen" wäre nun, wenn die Aktivierung der Zeitprofile unter Angabe des Namens über die REST-Schnittstelle möglich wäre.
 
Dann könnte ich das abhängig von der Aussentemperatur in den Abendstunden automatisch ansteuern, anstatt es manuell zu machen...
Gleiches ginge natürlich auch für Urlaubszeiten, etc.

Ansonsten nochmal großes Lob an Dich für die tolle Arbeit, die Du da für uns leistest!

Viele Grüße,
Olaf Korte

**Comment by camueller** [comment]
Warum nutzt Du zum Setzen der Zeitpläne nicht die vorhandene REST-Schnittstelle?
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/REST_DE.md

Diese Zeitplänen werden nicht gespeichert, d.h. Du könntest einimal am Tag den Zeitplan setzen, den Du haben möchtest.

**Comment by camueller** [comment]
Die Kriterien für dei An/Aus-Zeitpunkt sind meist wetterbedingt nicht jedes Jahr am selben Datum. Deshalb erscheint es nach wie vor nicht sinnvoll, ein solches Feature zu implementieren.
