### ISSUE TITLE
Steuerung per MQTT

### ISSUE THREAD

**Issue by christoph-ng** [camueller/SmartApplianceEnabler#277]
Gibt es die Möglichkeit Aktivitäten per MQTT zu steuern?

* Schaltzeiten ändern bzw. aktivieren
* manuellen Start auslösen
* Stop auslösen

**Comment by camueller** [comment]
Nein, aktuell nicht und ist auch nicht geplant.

Geplant sind ein MQTT-Schalter (Steuern eines Schalters per MQTT durch den SAE) und eine MQTT-Zähler (Ermittlung des Zählerstandes oder der Leistung per MQTT)

**Comment by christoph-ng** [comment]
kann man anders von extern Aktivitäten auslösen, Z.B. per URL?

**Comment by camueller** [comment]
Klar, das macht ja auch das Web-Frontend so. Die Aufrufe kann man ja im Browser verfolgen in den Dev-Tools.
Ist nicht dokumentiert und kann sich ändern, da keine offizielle Schnittstelle.

**Comment by christoph-ng** [comment]
Könnten Sie Aufrufe evtl. hier abbilden?

**Comment by camueller** [comment]
Wie schon gesagt: Es ist keine offizielle Schnittstelle und es gibt keinen Support dafür, also auch bewusst keine Dokumentation.
Wer sich auskennt mit dem Thema weiss, was zu tun ist.
