### ISSUE TITLE
Wert für Gesamtverbrauch wird auf 0 gesetzt wenn Gerät nicht erreichbar

### ISSUE THREAD

**Issue by c0ldtech** [camueller/SmartApplianceEnabler#293]
Hallo,

alle paar Tage kommt es mal vor, dass die Prüfung des Zählerstandes fehlschlägt, weil der Host (Tasmota Plug) aus irgendwelchen Gründen in dem Moment nicht erreichbar ist. Laut Log wird dann anscheinend der Wert des Zählerstandes auf 0 gesetzt, so dass bei der nächsten erfolgreichen Prüfung natürlich ein (immens hoher) Stromverbrauch erkannt und das Gerät eingeplant wird. Ist es eventuell möglich, bei der Prüfung ein Error Handling ainzubauen, damit in so einem Fall einfach der vorherige Zählerstand als erkannter Wert gesetzt wird?
Die Gründe für die Nichterreichbarkeit konnte ich noch nicht ausmachen, Tests mit kontinuierlichem Ping ergeben einen Paketverlust von nur 0,01-0,05 Prozent, ein grundsätzliches Problem im Netzwerk scheint es also nicht zu geben.

Gruß
Hendrik

**Comment by camueller** [comment]
Problem ist bekannt und ist bereits für die nächste Version gefixt - siehe https://github.com/camueller/SmartApplianceEnabler/discussions/269

**Comment by c0ldtech** [comment]
Super, danke!

**Comment by c0ldtech** [comment]
Wird es den Fix auch für Version 1.6.xx geben?

**Comment by camueller** [comment]
Ja, ich warte aktuell noch auf Feedback für eine andere Änderung. Sobald ich das habe wird es eine 1.6.21 geben. Kann aber August werden ...

**Comment by c0ldtech** [comment]
Gibt es hier etwas Neues zum Fix für die 1.6 Version? Ich hatte in dem anderen Issue leider jetzt erst gesehen, dass Du eine Testversion gebaut hattest - könntest Du die eventuell nochmal hochladen? Hier häufen sich aus mir unbekannten Gründen die Fälle in denen der Zähler mal nicht erreichbar ist, und ständig werden die Geräte eingeplant.

Gerade gesehen, dass es jetzt die 1.6.21 gibt - ausgerechnet heute schaue ich nicht nach ob es ein Update gibt, bevor ich schreibe...hat sich also (hoffentlich) erledigt, danke!
