### ISSUE TITLE
Issue #171 eventuell wieder da - keine Telegram Notifications

### ISSUE THREAD

**Issue by c0ldtech** [camueller/SmartApplianceEnabler#296]
Hallo,

ist Issue #171 eventuell wieder da? Damals wurden wohl keine Notifications versendet, wenn der Schaltertyp ein HTTP Schalter war. Ich habe seitdem nur 1.6.xx Versionen eingesetzt, da ich dort keine Probleme hatte. Aufgrund des aktuellen Problems mit dem Zurücksetzen des Zählerstandes bei Nichterreichbarkeit des Gerätes habe ich es heute mal mit Version 2.0.5 versucht, und es scheint alles zu funktionieren - bis auf den Versand von Notifications (ich habe nur HTTP Schalter). 
Ich habe es sowohl in meiner üblichen Docker Umgebung, als auch auf einem "echten" frisch installierten Raspberry Pi 2 versucht. Ich habe sogar die Gerätekonfiguration neu angelegt, alles ohne Erfolg. Ist da etwas bekannt?

Gruß
Hendrik

**Comment by camueller** [comment]
Bei mir kommen nach wie vor Notifications. Es gab auch keine Änderungen diesbezüglich von 2.0.4 auf 2.0.5. Eventuell hat irgendetwas bei Deinem Wechsel von 1.6  auf 2.0 nicht geklappt.
