### ISSUE TITLE
Schalter HTTP PUT schickt keine Daten

### ISSUE THREAD

**Issue by profigriller** [camueller/SmartApplianceEnabler#308]
ich brauche für meinen Schalter HTTP PUT. Leider klappt das Kommando nicht.
Als PUT konfiguriert sieht man beim Kommando data=null
Wenn ich das als POST konfiguriere sieht man beim Kommando data=ON
17895	2022-08-16 19:50:51,681 DEBUG [MQTT Call: F-20005634-000000005678-00-HttpSwitch-11] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:78] F-20005634-000000005678-00: HTTP request: method=PUT url=http://192.168.123.10:8080/rest/items/eHzg1000WFreigabeSHM/state data=null

18656	2022-08-16 19:51:27,988 DEBUG [MQTT Call: F-20005634-000000005678-00-HttpSwitch-12] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:78] F-20005634-000000005678-00: HTTP request: method=POST url=http://192.168.123.10:8080/rest/items/eHzg1000WFreigabeSHM/state data=ON

Mache ich einen Fehler?
	
![Screenshot 2022-08-16 200248](https://user-images.githubusercontent.com/12680457/184948161-a701923d-5cb4-4bf4-9938-bb23aa89c7f5.png)

![Screenshot 2022-08-16 200828](https://user-images.githubusercontent.com/12680457/184949101-7229f4e4-4176-429f-af8b-7f19a73436b4.png)

**Comment by camueller** [comment]
Ich habe gerade im Code nachgesehen: aktuell wird der Wert nur für HTTP POST mitgegeben. Ich hatte das eigentlich bereinigt, aber leider eine Stelle übersehen. Ich werde das fixen und stelle Dir eine Test-Version bereit, damit Du den Fix testen kannst.

**Comment by profigriller** [comment]
Super, danke.

**Comment by camueller** [comment]
Hier die modifizierte 2.0.5 zum Download: https://drive.google.com/file/d/10hO42pNilIRaSyOfwKswt8m2Qo2jUZnE/view?usp=sharing

Bitte testen und Ergebnis hier dokumentieren.

**Comment by profigriller** [comment]
Ich habe die datei mittels dockerfile in das docker image kopiert.
Das PUT Kommando sieht jetzt gut aus. Leider versteht Openhab das Kommando nicht. Response code is 415.
Da kann jetzt aber SAE nix für. Komisch. Mit eine REST client gehts. Ich forsche weiter. Sobald SAE Schalter MQTT unterstützen hat sich das mit http erledigt.

2022-08-24 19:42:37,230 DEBUG [MQTT Call: F-19640203-000000000010-00-HttpSwitch-1] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:78] F-19640203-000000000010-00: HTTP request: method=PUT url=http://192.168.123.10:8080/rest/items/eHzg1000WFreigabeSHM/state data=ON
2022-08-24 19:42:37,233 DEBUG [MQTT Call: F-19640203-000000000010-00-HttpSwitch-1] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:150] F-19640203-000000000010-00: Response code is 415

**Comment by camueller** [comment]
HTTP 415 ist "Unsupported media type". Schau doch mal, was der REST-Client als Content-Type schickt. Un dann setze diesen auch im SAE. Dann sollte es klappen.

**Comment by profigriller** [comment]
Ich weiß jetzt nicht genau wonach Du suchst. Der Rest Client gibt ein Beispilehaftes Kommando mit aus.

curl -X 'PUT' \
  'http://192.168.123.10:8080/rest/items/eHzg1000WFreigabeSHM/state' \
  -H 'accept: */*' \
  -H 'Content-Type: text/plain' \
  -H 'Authorization: Bearer eyJraWQiOm51bGwsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJvcGVuaGFiIiwiYXVkIjoib3BlbmhhYiIsImV4cCI6MTY2MTM2NjM4MiwianRpIjoiNlpTSWlMa3BUTllER0dCM3FnQWVaZyIsImlhdCI6MTY2MTM2Mjc4MiwibmJmIjoxNjYxMzYyNjYyLCJzdWIiOiJhZG1pbiIsImNsaWVudF9pZCI6Imh0dHA6Ly8xOTIuMTY4LjEyMy4xMDo4MDgwIiwic2NvcGUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW5pc3RyYXRvciJdfQ.tq8Ygxzs-fGXcGlzZrz9iwY_81Sn7B-kjtcV0xiZoE0RFDpA4pOGf2ehldGYuPQ14F5YAUzgnxD3D0QaYbhQamNLC_ViKjihCE6VZC4DHCwiJJvYwJcvw4xscmtiHe2Pds6T5oye3fIM4NMe0Hk7szy-I_WQcmxvqf8gnCNcpw6lbvUlhHJFO6C6taZ-VjGzyXV9U44XMbX39-FSWqnibWUMChyAT9qjprM2epZovwbjWt1Y6U43saMNPlYtM5lFUUrh8Hd3dbloxad0W-va_LSruTzMhYTlNtP1kxQx1zptSRgZ_SuZAbeoH5pE_q9Gw0VTLKl5nT7J_L-WXJLYlA' \
  -d 'OFF'

**Comment by camueller** [comment]
Entsprechend des obigen Befehls solltest Du den Content-Type für den Schalter im SAE auf `text/plain` setzen.
Obiger Befehl enthält allerdings auch einen Bearer-Token. Der SAE unterstützt bei HTTP nur Basic Authentication. Im Zweifel die Authentication abschalten ...

**Comment by profigriller** [comment]
geht. :-) 
Vor lauter testen hatte ich die Option übersehen.
