### ISSUE TITLE
Feature: add stop funktion at light

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#33]
Bitte ein Stop Funktion in der Ampel einbauen.
z.b. 
auf rot klicken = Stop inkl löschen des Timers
auf gelb klicken = Stop ohne löschen des Timers (Manuelle Pause)

**Comment by camueller** [comment]
Durch Klick auf die rote Ampel-Leuchte wird das Gerät sofort ausgeschaltet und dem SHM bis zum Ende des Timeframes mitgeteilt, dass keine Steuerbefehle akzeptiert werden. Der Timeframe selbst bleibt aktiv, um das Wiedereinschalten innerhalb des Timeframes zu ermöglichen.

**Comment by camueller** [comment]
Implemented in version 1.4.16.
