### ISSUE TITLE
Priorisierung eines Gerätes

### ISSUE THREAD

**Issue by rubale33** [camueller/SmartApplianceEnabler#331]
Hallo, gibt es eine Möglichkeit zur Priorisierung eines steuerbaren Gerätes? Beispiel: Gerät funktioniert mit 400 Volt Es hat 3 Heizwendel, Heizstab1,2 und 3. Kann Heizstab 1 priorisiert werden?

**Comment by camueller** [comment]
Die Priorisierung der Geräte erfolgt durch den SHM.

Wenn Du den SAE 2.0 mit dem neuen Stufenschalter verwendest, kannst Du die 3 Heizwendeln zu einem Gerät zusammenfassen. Siehe: https://github.com/camueller/SmartApplianceEnabler/blob/2.0/doc/LevelSwitch_DE.md

**Comment by rubale33** [comment]
Vielen Dank für die schnelle Hilfe. Ich werde die Konfiguration entsprechend einrichten. Es spart 2 Relais für das Schalten der Umwälzpumpe, die ja immer mitlaufen muss, wenn ein Heizwendel des Heizstabes läuft.

**Comment by camueller** [comment]
Wenn Du den Stufenschalter testen willst, verwendet bitte folgende modifizierte Version 2.0.5: https://drive.google.com/file/d/1XD43fclGFpeUMnLy5l-i1uiqC2Ade9Za/view?usp=sharing

Ich teste aktuell mit einem anderen User den PWM-Schalter, wobei Fehler identifiziert und gefixt wurden, die auch den Stufenschalter betreffen.

**Comment by rubale33** [comment]
Leider funktioniert der o.g. Downloadlink zur modifizierten Version 2.0.5 nicht mehr. Kann den jemand nochmal aktivieren? Mit der normalen 2.0.5 läuft der Stufenschalter nicht. Danke.

**Comment by camueller** [comment]
Du kannst diesen Link für eine aktualisierte 2.0.5 verwenden: https://drive.google.com/file/d/1gK5A9TAtb3WdEn92caQbFmJnkVuVmzeO/view?usp=sharing

Achtung: Du musst den Dateinamen ändern, da ist eine Ergänzung an der Versionsnummer, die Du entfernen solltest.

**Comment by Tombra1889** [comment]
Ich habe in den letzten Tagen festgestellt, dass die Priorisierung / Einplanung der Geräte nicht korrekt funktioniert.
Z. B. habe ich eine Teichpumpe, die eine Mindestlaufzeit von 5 Stunden und 30 Minuten hat. Um 07:30 Uhr war heute noch kein Photovoltaikstrom vorhanden, trotzdem wurde das Gerät direkt um 07:30 Uhr eingeschaltet. Eigentlich hätte dies erst später gestartet werden dürfen.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/60692414/195025220-3636fa78-b93f-4be9-9694-f898c2d5cc1f.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/60692414/195025483-328c9619-816d-4e65-9fbf-23c5567e4049.png">

Bei anderen Geräten habe ich das Verhalten festgestellt, dass diese eingeschaltet werden, obwohl die Priorisierung niedriger ist als bei anderen Geräten. Hat schon jemand ein ähnliches Verhalten feststellen können? Generell ist mir der SHM bei vielen Geräten zu zögerlich mit den Einschaltbefehlen:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/60692414/195026429-57c3083c-c8d1-462a-bfdb-7cceb7368f68.png">

Das Gerät mit hoher Priorität und 800 Watt, einer Mindestlaufzeit von 20 Minuten ist immer noch nicht eingeschaltet.

**Comment by camueller** [comment]
Einplanung und Priorisieurung von Geräten ist Aufgabe des SHM.

**Comment by rubale33** [comment]
Hallo Axel,
ich freue mich über die schnelle Antwort von dir und werde diese bei der
Konfiguration berücksichtigen. Ich gehe davon aus, dass nach dem
hochschalten Stufe 1-2-3, das runterschalten 3-2-1 genau so stattfindet.
Das spart Hardware ;-) .
Nochmals vielen Dank.
Gruß von Rudolf aus Lemgo

Axel Müller ***@***.***> schrieb am So., 4. Sept. 2022, 08:14:

**Comment by rubale33** [comment]
Hallo Axel, der SAE läuft mittlerweile einwandfrei bei mir. Ich hatte vor
ein kleines Weihnachtsgeschenk über den Donate-Button zu überweisen. Das
funktioniert aber nicht so, wie ich es mir vorstellte. Wie bekomme ich das
hin?
Freundliche Grüße
Rudolf Bartneck, Lemgo

Axel Müller ***@***.***> schrieb am Di., 11. Okt. 2022, 10:10:

**Comment by camueller** [comment]
Hallo Rudolph,

freut mich sehr, wenn der SAE Dir im Alltag hilft. Ich nutze ihn ja auch ständig (wenn auch nicht alle Features).

Danke für den Hinweis - der "Button" war bisher nur eine Grafik und der Link war hinter dem Wort "Paypal". Weil nichts dagegen spricht, den Button selbst in einen Link zu konvertieren, habe ich das jetzt gemacht.

Viele Grüsse und frohe Weihnachten,

Axel
