### ISSUE TITLE
Add Docker-Support

### ISSUE THREAD

**Issue by thezepter** [camueller/SmartApplianceEnabler#37]
Moin Moin

Ich hab schon diverse Docker Container auf meiner Synology Diskstation am laufen, scheitere aber gerade daran deinen zum laufen zu bringen. Vielleicht hat jemand ein Tip für mich ?

Eigentlich muss ich doch nur ein Order erstellen und diesen auf den internen Docker Pfad linken....
**/volume1/docker/smartapplianceenabler/:/usr/bin**

Start:
`sudo docker run --name SAE -p 8080:8080/tcp -d -v /volume1/docker/smartapplianceenabler/:/usr/bin avanux/smartapplianceenabler-de:latest`

Ergebnis
`docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/bin/entry.sh\": stat /usr/bin/entry.sh: no such file or directory".`

**Comment by camueller** [comment]
Ich habe Docker bisher nur zweimal kurz getestet und dabei folgende Doku erstellt:

https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md

Bei meinen Tests mit Docker hatte der SAE keine Probleme! Sobald ich etwas Zeit habe, werde ich einen meiner Raspis auf Docker umstellen. Nach Möglichkeit werde ich Dir helfen, den SAE in Docker zum Laufen zu bringen.

**Comment by thezepter** [comment]
Schau ich mir noch mal an. Danke !
Ist auch absolut nicht eilig, da ich dein sae ersteinmal auf dem PI installiert habe. Falls ich weiter kommen meld ich mich natürlich.

**Comment by camueller** [comment]
Für jedes Release wird ein Docker-Image für Raspberry Pi bereitgestellt (x86 fehlt noch).
Leider geht GPIO-Zugriff nicht, aber ansonsten sollte das Docker-Image einsetzbar sein.
Dokumentation ist aktuell: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md

**Comment by camueller** [comment]
Für jede Version werden automatisch Docker Images für arm32 und amd64 bereitgestellt.

**Comment by KingLuy** [comment]
Hallo alle zusammen,

ich bin auf das Projekt hier gestoßen und würde es gerne im Docker Container auf meiner Synology laufen lassen. Komme da aber irgendwie nicht weiter. Kann mir jemand eine kurze Hilfestellung geben wie das funktioniert. 
Geüsse King Luy

**Comment by camueller** [comment]
Diese Issue ist closed und hier wird Dir niemand helfen.
Aber heir gibt es eine Diskussion zu Deinem Thema: https://github.com/camueller/SmartApplianceEnabler/discussions/446
