### ISSUE TITLE
go-eCharger Anbindung

### ISSUE THREAD

**Issue by posert** [camueller/SmartApplianceEnabler#40]
Hallo
ich möchte den offenen go-eCharger mit dem SmartApplianceEnabler verbinden. Geht das ?
Der go-eCharger ist eine sehr gute mobile Wallbox mit offener API.
Kann ich ohne weiteres diesen mit Hilfe des SmartApplianceEnabler (SAE) und dem Raspberry Pi an meinen SHM anbinden?

**Comment by camueller** [comment]
Bitte die Frage im Forum stellen, damit die anderen auch etwas davon haben: https://www.photovoltaikforum.com/thread/104060-geräte-mit-home-manager-koppeln-via-semp-ethernet
