### ISSUE TITLE
Upate Spring Boot / JDK / Raspbian

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#41]
Spring Boot 1.3 used in SAE has end of life in August 2019 (https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019).
Updating Spring Boot might require Updating JDK and therefore Raspbian!

**Comment by camueller** [comment]
Fully enable unit tests in FileHandlerTest.java which are causing NPE if executed on JDK 1.8.0_151 used by Travis CI. Tests run perfectly on JDK 1.0.8_65.

**Comment by camueller** [comment]
Beim aktuellen Raspian "Buster" ist das Oracle-JDK nicht mehr direkt installierbar, da es durch OpenJDK ersetzt wurde.

Anleitung zur manuellen Installation von Oracle JDK auf Raspbian Buster:
https://tecadmin.net/install-oracle-java-on-debian-10-buster/

**Comment by F-L-0** [comment]
Ich habe aktuell 2 RPI4 hier die mittelfristig auch den SAE betreiben sollen. Falls du also jemanden zum Testen einer aktualisierten SAE-Version (aktuelles OpenJDK 9 auf Buster, aktuellen Springboot/TomCat Unterbau) brauchst kannst du dich gerne an mich wenden.

**Comment by camueller** [comment]
Umgesetzt mit Release 1.5.1.
