### ISSUE TITLE
Hilfetext Schalter/Einschaltfunktion / V 2.1.0

### ISSUE THREAD

**Issue by Exo84** [camueller/SmartApplianceEnabler#414]
![image](https://user-images.githubusercontent.com/116544659/209841087-78ac9b28-d454-453f-aca4-f4dca37eabfa.jpeg)

**Comment by camueller** [comment]
Ist bei der Vereinheitlichung für die Englische Dokumentation kaputtgegangen. Wird für die nächste Version gefixt.
Hier ist der Link zur gesuchten Seite: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/SwitchOnOption_DE.md
