### ISSUE TITLE
Wallbox: geplante Energie steigt

### ISSUE THREAD

**Issue by JoernHei** [camueller/SmartApplianceEnabler#416]
Hallo camueller,

ich habe einen go-e Charger V2 mit einem VW Passat Hybrid. Von Batterie ganz leer bis Batterie ganz voll sind es 8000 Wh.
Im Logbuch wird richtig errechnet, dass es zum Laden von 40% bis 100% Akkustand 4800 Wh braucht.
In der folgenden Zeile wird errechnet, dass es von 41% bis 100% Akkustand ebenfalls 4800 WH braucht. Korrekt wären 4720 Wh.
Die Status Anzeige spiegelt das Gleiche wieder: Die geplante Energie steigt in gleichem Maße wie die geladene Energie.
Anscheinend wird die geladene Energiemenge nicht richtig verrechnet. Angezeigt wird die geladene Energiemenge auf der Statusseite und im Sunny Portal jedoch korrekt nur die geplante Energie weicht ab (in diesem Fall ist sie geladene Energie + 4,8 kWh).

Könnten Sie mir bitte helfen das Problem weiter einzugrenzen oder gar ganz zu beheben?
Ich nutze den SAE in der Version 2.1.0 mit der Version 1.6 hatte es zuvor korrekt funktioniert.
Hier ist das Logfile mit den kalkulierten Werten:
[Status.txt](https://github.com/camueller/SmartApplianceEnabler/files/10316540/Status.txt)
Hier das gesamte Logfile:
[Status komplett.txt](https://github.com/camueller/SmartApplianceEnabler/files/10316595/Status.komplett.txt)

Mit freundlichen Grüßen
JoernHei

**Comment by camueller** [comment]
Ich prüfe das ...

**Comment by camueller** [comment]
Hast Du zwei E-Autos? Kannst Du Deine `Appliances.xml` mal posten (gerne auch mit anonymisierten "F-"-IDs ...). Irgendwie sind bei Dir Überschußladen und normales Laden für zwei verschiedene Fahrzeuge zeitgleich aktiv. Das sollte so nicht sein.

Die eigentliche Ursache für das Nicht-Herunterzählen der verbleibenden Energie liegt aber daran, dass Du für das gerade mit der Wallbox verbundene Fahrzeug im SAE keine Batteriekapazität konfiguriert hast.

Kannst Du das mal prüfen, korrigieren und testen, ob Du dann immer noch Probleme hast?

**Comment by JoernHei** [comment]
Vielen Dank für Deine schnelle Antwort!

Ich habe 1 E-Auto. Für das Überschussladen habe ich jedoch das gleiche Auto nochmal mit hoher Batteriekapazität angegeben, weil ich beobachtet habe, dass der SHM bei guten Ertragserwartungen am nächsten Tag auch gerne Mal das Laden verschiebt und heute lieber ins Netz einspeist. Das "2." Auto ist eine Krücke mit der ich das vermeiden möchte. Zielführender wäre wahrscheinlich dem SHM gar keine Kapazität sondern eher einen ganz normalen Kann Verbraucher zu übermitteln (für das Überschussladen) aber das würde vermutlich gegen das Konzept des SAE gehen. Vermutlich kann der SHM Wallboxen auch nur mit konkretem Energiebedarf ansteuern. Daher habe ich mir so geholfen. Meistens steht ja der nächste Abfahrtstermin schon fest und es wird entsprechend optimiert geladen.

Wie werden dann die 4800Wh errechnet? Von dem "anderen" Fahrzeug mit 100 kWh kann es ja nicht kommen.
Gibt es mehrere Stellen, wo ich die Kapazität angeben kann?

Ich bin heute Abend erst wieder zu Hause und prüfe das dann.
Ich bin mir ziemlich sicher, dass ich eine Batteriekapazität angegeben habe. Allerdings habe ich die Ladeverluste auf 0% gestellt, da ich nur die Gesamtenergie von 0% auf 100% feststellen kann (gemessen von der Wallbox) und nicht weiß welcher Anteil davon Verlust ist. VW hat es mit den Anzeigen zur Batterie nicht so. % Gibt es auch nicht, nur 10 Balken. Wegen dem kleinen Akku macht das aber nichts. Eine automatische SOC Ermittlung habe ich auch nicht, die hätte mein Problem wahrscheinlich abgefangen.

**Comment by camueller** [comment]
Dein Pseudo-Workaround mit 2 Autos macht die Sache nur unnötig kompliziert und bringt keinen Vorteil. Ich würde Dir also raten, mit einer richtigen Konfiguration zu arbeiten.

> Wie werden dann die 4800Wh errechnet? Von dem "anderen" Fahrzeug mit 100 kWh kann es ja nicht kommen.
Gibt es mehrere Stellen, wo ich die Kapazität angeben kann?

Wie schon gesagt, Du hast mit Deinen zwei Konfigurationen irgendwie einen kaputten Zustand erzeugt. Das werde ich nicht untersuchen aus den o.g. Gründen.

> Eine automatische SOC Ermittlung habe ich auch nicht, die hätte mein Problem wahrscheinlich abgefangen.

Du kannst ja den SOC bei Ladebeginn manuell angeben.

**Comment by JoernHei** [comment]
> Dein Pseudo-Workaround mit 2 Autos macht die Sache nur unnötig kompliziert und bringt keinen Vorteil. Ich würde Dir also raten, mit einer richtigen Konfiguration zu arbeiten.

Ok, ich werde die beiden Autos löschen und nur eines anlegen. Danach das Auto anstecken und optimiertes Laden einstellen.
Ist das so korrekt?

> Du kannst ja den SOC bei Ladebeginn manuell angeben.

Den SOC gebe ich bei Start ein.

Das mit dem Überschussladen ist hier ja nicht so von Bedeutung, ich werde dann immer das optimierte Laden einstellen.

**Comment by camueller** [comment]
Achte darauf, dass die Batteriekapazität in der Fahrzeugkonfiguration angegeben ist. Da es eigentlich ein Pflicht-Parameter ist, muss dieser Wert eingegeben werden, um Speichern zu können.

Bitte vom nächsten Ladevorgang ein Log bereitstellen, falls immer noch Problem auftreten.

**Comment by JoernHei** [comment]
Ich danke nochmal für die schnelle Hilfe. Wenn´s nochmal Probleme gibt, werde ich den issue wieder öffnen.

**Comment by JoernHei** [comment]
Das Verhalten des SAE hat sich leider auch nach dem Neuanlegen des Verbrauchers nicht geändert.
Hier LOG und appliances.xml:
[LOG.txt](https://github.com/camueller/SmartApplianceEnabler/files/10320352/LOG.txt)
[Appliances.xml.txt](https://github.com/camueller/SmartApplianceEnabler/files/10320358/Appliances.xml.txt)

**Comment by camueller** [comment]
Wenn Du willst, dass ich den Fehler finde, dann schicke mir bitte ein vollständiges, normales Log ohne Rückwärts-Sortierung oder Ähnliches. Bis dahin mache ich erstmal nichts.

**Comment by JoernHei** [comment]
Sorry für das umgedrehte, habe es aus dem System Logs Viewer kopiert und nicht direkt aus der Datei.
Das Auto wurde um 2022-12-29 16:37:53,069 als verbunden erkannt.

[LOG.txt](https://github.com/camueller/SmartApplianceEnabler/files/10320518/LOG.txt)

**Comment by camueller** [comment]
Ich denke, dass ich den Fehler gefixt habe. Hier ist eine modifizierte 2.1.0-Version mit dem Fix:

https://drive.google.com/file/d/1rPzlrsDuQ7b5daknky_FwXm6N6Ham0xQ/view?usp=share_link

Kannst Du bitt testen, ob das Problem damit behoben ist?

**Comment by JoernHei** [comment]
Ja klar. Ich teste das dann morgen Abend. Das Auto ist ja jetzt schon voll.

**Comment by JoernHei** [comment]
Hallo, heute hat es geklappt.
Hier noch ein Screenshot der entsprechenden Ampel.
Der Wert, der per Semp übertragen wird sinkt entsprechend ab.

[Screenshot](https://user-images.githubusercontent.com/113467542/210091105-50c6079d-bfdd-437b-bd40-4825fbe40446.png)

Problem ist für mich damit behoben - vielen Dank!

**Comment by camueller** [comment]
Am Screenshot ist mit gerade bewusst geworden, dass Du mit der Testversion auch schon die neue Anzeige des SOC erhalten hast :-) Die kommt auch mit der nächsten Version.

**Comment by JoernHei** [comment]
Ja, ich habe den erstellt, weil mir die Änderung aufgefallen ist.Falls es bei Wallboxen noch etwas zu testen gibt, kannst Du gern noch einmal auf mich zukommen. Am 30.12.22, 18:08 schrieb "Axel Müller" ***@***.***>:

   
  Am Screenshot ist mit gerade bewusst geworden, dass Du mit der Testversion auch schon die neue Anzeige des SOC erhalten hast :-) Die kommt auch mit der nächsten Version.
