### ISSUE TITLE
RedNode lehnt Zugriff ab

### ISSUE THREAD

**Issue by StefanSauensiek** [camueller/SmartApplianceEnabler#417]
Hallo,

ich bin absoluter Novize in Linux und bin über SmartApplianceEnabler gestolpert um einzelne Verbraucher im SMA Sunnyhomemanger darzustellen. Die Automatische Installation und die Beschreibung sind super und ich bin wirklich begeistert. Danke dafür schon mal.
Nun habe ich festgestellt das, wenn ich auf den RedNode Mode umschalten will, verweigert der Raspberry den Zugriff. Auch kann ich die nachgerüstete Festplatte nicht mounten, weil wohl ein Modul nicht installiert ist.
Blöde Frage. Liegt es an dem benutzten LiteImage?

**Comment by camueller** [comment]
NodeRED ist optional und daher für das Funktionieren des SAE nicht entscheidend.

Bei der Installation udn Verwendung von NodeRED kann man viele Dinge falsch machen, insbesondere, wenn man sich mit Linux nicht auskennt. Weil es sich nicht um einen grundsätzlichen Fehler im SAE handelt, den ich beheben kann, schliesse ich diesen Issue.
