### ISSUE TITLE
Speichern nach Ändern eines Tasmota „Zählers“ nicht möglich 

### ISSUE THREAD

**Issue by Elektron79** [camueller/SmartApplianceEnabler#449]
Hallo,

ich beobachte das folgende Verhalten schon länger, also schreibe ich jetzt mal einen Issue.
Wenn ich einen neuen Tasmota Zwischenstecker als Zähler anlege, kopiere ich immer die URL und auch den Pfad von einer anderen Tasmota im Webinterface. (Natürlich ändere ich die IP-Adresse)

da ich ja immer nur einen der beiden Parameter in die Zwischenablage kopieren kann, müsste ich das in zwei Schritten machen. Aber egal in welcher Reihenfolge ich die beiden Felder fülle, nach der Änderung kann ich den Speichern Button nicht drücken.
Der Button ist aktiv, macht aber nichts und wenn ich links auf ein anderes Gerät klicke bekomme ich eine Warnung, dass die Änderung nicht gespeichert ist.

ich verwende den SAE in der Version 2.1.0 
Als Browser verwende ich Safari unter iOS.

Vielen Dank und Grüße Michael

**Comment by camueller** [comment]
Du hast den Ablauf ja schon relativ gut beschrieben. Um sicherzugehen, dass ich alles richtig verstanden habe, beschreibe ich jetzt nochmal genauer die Schritte:

## Ausgangssituation:
Gerät, für das aktuell kein Zähler konfiguriert ist

## Schritte
1. Klick auf `Zähler` im Seitenmenü
1. Klick auf `Typ` mit Wert `HTTP`
1. Klick auf `Format` mit Wert `JSON`
1. Einfügen einer URL aus der Zwischenablage
1. Klick auf `Paramer` mit Wert `Zählerstand`
1. Einfügen eines `Pfad für Extraktion` aus der Zwischenablage
1. Speichern-Button ist blau, d.h. Speichern ist mögllch
1. Klick auf `Speichern`
1. Speichern-Button ist grau, d.h. Speichern ist nicht mögllch

Bei diesem Ablauf wird bei mir alles korrekt gespeichert.

Allerdings habe ich für diesen Test eine SAE-Version verwendet, welche sich zwar noch als 2.1.0 meldet, aber bereits der demnächst kommenden Version 2.2.0 entspricht. Du kannst diese hier schon mal herunterladen und testen, ob der Fehler damit auftritt: 

https://drive.google.com/file/d/1fqj_2WmZngoGW1lZgvQez8lTPebtUeRB/view?usp=share_link

Falls der Fehler damit immer noch auftritt, würde ich Dich bitten zu testen, ob der Fehler auch unter Chrome auftritt.

**Comment by Elektron79** [comment]
Hallo Alex,

ich hatte Dir heute früh schon geantwortet, aber irgendwie ist das hier nicht angekommen.
Also ein neuer Versuch…

So wie Du es beschreibst, geht es. Also alles in einem Rütsch. Aber in Etappen geht es leider nicht.

Ich war vielleicht nicht ganz präzise, daher hier noch einmal gemäß Deiner Beschreibung.

Ausgangssituation:

Gerät, für das aktuell kein Zähler konfiguriert ist

Schritte

1.) Klick auf Zähler im Seitenmenü
2.) Klick auf Typ mit Wert HTTP
3.) Klick auf Format mit Wert JSON
4.)Einfügen einer URL aus der Zwischenablage

5.) auf Speichern klicken
6.) in eine einer (Tasmota) Komponente wechseln und da den Pfad für die Extraktion in die Zwischenablage kopieren.
7.) zurück auf dem angefangen Zähler wechseln.

8.) Klick auf Parameter mit Wert Zählerstand
9.) Einfügen eines Pfad für Extraktion aus der Zwischenablage
10.)Speichern-Button ist blau, d.h. Speichern ist mögllch
11.) Klick auf Speichern
Speichern-Button ist noch immer blau, d.h. Speichern hat nicht geklappt 
12.) wenn ich links dann etwas anderes Auswähle, kommt die Warnung, dass die Änderung nicht gespeichert wurde und verloren geht.

Der gleiche Fehler tritt auf, wenn ich bei einem funktionierenden Device die IP-Adresse ändern möchte.

Das Abfrageintervall lässt sich jedoch ohne Probleme ändern…

**Comment by camueller** [comment]
Die Seite kann nur gespeichert werden, wenn alle Pflichtfelder gefüllt sind. Aus diesem Grund ist der Speichern-Button augegraut, solange das nicht der Fall ist. Nach dem Speichern einer Konfiguration, bei der alle Pflichtfelder ausgefüllt sind, kann man weitere Felder eingeben und jeweils den Sepichern-Button drücken, wenn man möchte.

Jedenfalls liegt hier kein Fehlverhalten des SAE vor, deshalb schliesse ich den Bug.

**Comment by Elektron79** [comment]
Hallo Alex,

Schade, dass Du nicht gelesen hast was ich geschrieben hatte.
1.) Das Speichern Button IST BLAU also aktiv, aber speichert nicht.
2.) das Feld Pfad ist kein Pflichtfeld, zumindest nicht als solches gekennzeichnet.
3.) warum tritt dann das Problem auch beim Ändern der URL (Ich hatte einen Zahlendreher in der IP-Adresse) auch auf?

vielleicht findest Du noch einmal die Zeit genauer zu lesen / zu prüfen.

viele Grüße Michael

**Comment by camueller** [comment]
Der Schritt 5 in Deiner Liste ist nicht ausführbar, weil ohne Schritt 8 der Speichern-Button ausgegraut und nicht klickbar ist. Sobald man Schritt 8 ausgeführt, kann man Schritte 9, 10, 11 ausführen, wobei nach nach Letzterem der Button wieder ausgegraut ist, da die Änderungen gespeichert wurden.

Auch das nachträgliche Ändern der URL oder IP-Adresses bewirkt, dass der Speichern-Button blau wird und nach dem Klick darauf wieder grau, da die Änderungen gespeichert wurden.

Ich kann also nach wie vor kein fehlerhaftes Verhalten der Version, die demnächst als 2.2.0 releast wird, feststellen. Hast Du denn überhaupt mit der Version aus dem Download-Link getestet?

**Comment by Elektron79** [comment]
Hallo Alex,

dann konkretisiere ich noch einmal:

1.) Klick auf Zähler im Seitenmenü
2.) Klick auf Typ mit Wert HTTP
3.) Klick auf Format mit Wert JSON
4.)Einfügen einer URL aus der Zwischenablage
4a.) Parameter „Leistung“

5.) auf Speichern klicken
6.) in eine einer (Tasmota) Komponente wechseln und da den Pfad für die Extraktion in die Zwischenablage kopieren.
7.) zurück auf dem angefangen Zähler wechseln.

8.) Klick auf Parameter mit Wert Zählerstand
9.) Einfügen eines Pfad für Extraktion aus der Zwischenablage
10.)Speichern-Button ist blau, d.h. Speichern ist mögllch
11.) Klick auf Speichern
Speichern-Button ist noch immer blau, d.h. Speichern hat nicht geklappt
12.) wenn ich links dann etwas anderes Auswähle, kommt die Warnung, dass die Änderung nicht gespeichert wurde und verloren geht.

in dem Fall geht es!

Werde dann am nächsten Wochenende mal mit der 2.2.0 Testen.

viele Grüße Michael

**Comment by camueller** [comment]
Mit der von Dir gegenannte Schrittfolge gibt es keinen Fehler, d.h. falls es einen Fehler gab, ist der in 2.2.0 behoben.
Allerdings kann ich nur für Chrome sprechen, ob das auch für Safari gilt, wird sich zeigen. Falls das Problem nur in Safari auftritt, kann ich leider nichts machen. Vielleicht solltest Du dann eine neuere Browser-Version verwenden oder einen besseren Browser.

**Comment by Elektron79** [comment]
Hallo Alex,

ich habe es heute noch einmal mit der „normalen“ 2.1.0 getestet aber einen „normalen“ PC benutzt. damit klappt das Ändern der IP-Adresse ohne Probleme. Ich vermute mal, dass mit dem PC auch das nachträgliche Pflegen des Pfades möglich ist.

Es scheint also an Safari bzw. iOS zu liegen.

viele Grüße Michael
