### ISSUE TITLE
Änderung Schaltertyp auf "Zählerbasierter Zustandsmelder" nicht möglich

### ISSUE THREAD

**Issue by J0EK3R** [camueller/SmartApplianceEnabler#450]
Hallo Axel :)

Mir ist noch aufgefallen, dass eine (nachträgliche) Änderung des Schalter-Typs (bei mir: von "Immer eingeschaltet") auf "Zählerbasierter Zustandsmelder" in der Web-Oberfläche nicht möglich ist - **der "Speichern"-Knopf bleibt ausgegraut**.

Möchte ich dann beispielsweise wieder auf die Konfigurationsseite für "Zähler" wechseln, kommt ein Dialog-Box "Änderungen verwerfen?" - also eigentlich wird erkannt, dass eine Änderung stattgefunden hat, ich kann sie nur nicht speichern.

Ausgangssituation:
Ich habe Geräte angelegt, deren Zähler-Typ "HTTP" ist (-> Shelly) und deren Schalter-Typ "Immer eingeschaltet" ist.
Nun würde ich den Schalter-Typ gerne ändern.

**Comment by camueller** [comment]
Fehler wurde behoben für SAE 2.2.0.
