### ISSUE TITLE
Keine Aktualisierung im Sunny-Portal nach MQTT-Broker Down/Up

### ISSUE THREAD

**Issue by J0EK3R** [camueller/SmartApplianceEnabler#451]
Hallo Axel - hab erfolglos versucht, den Bug #447 nochmal zu öffnen, deshalb ein neuer:

Ich habe mir die Änderung mit dem Zwischenspeichern der Subscriptions in der map **messageHandlerForSubscribedTopic** nochmal in Ruhe angeschaut...

Ich denke, Put und auch Remove von Topic und Handler sollten nicht von connect() abhängig sein, also auch im disconnect-Zustand in/aus der map gepackt/gelöscht werden können.
Deshalb sollten die Aufrufe also aus dem if(connect())-Block raus.

Dann ist mir noch was aufgefallen: kann es sein, dass das "messageHandlerForSubscribedTopic.put" eher in die private Methode subscribe gehört? Also die, die auch client.subscribe aufruft?!

Beste Grüße
Jochen

**Comment by camueller** [comment]
Diskussion wird in https://github.com/camueller/SmartApplianceEnabler/issues/447 fortgesetzt.
