### ISSUE TITLE
Shell Execute Schalter

### ISSUE THREAD

**Issue by lotharwerner** [camueller/SmartApplianceEnabler#46]
Einen Shell Execute Schalter fände ich auch toll im SAE.

Da könnte ich dann Python auf dem Raspberry worauf Smart Appliance Manager läuft installieren und ich könnte die Scripte dann von diesem aus mit Smart Appliance Manager und einem Shell Execute Schalter starten wie in meiner Pimatic Hausautomation.

Wie auch im Betirag im Forum 
#2.206 beschrieben wurde.

https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet/?pageNo=221

**Comment by F-L-0** [comment]
Hi,

als Workaround bis es diese Feature gibt könntest du einen kleinen Webserver laufen lassen der dann deine Scripte antriggert - oder da es eh ein python ist das du aufrufen willst gleich in einem Script.

Vielleicht hilft dir das hier als Start - hab ich beim googeln gefunden und schonmal verwendet um einfache Dinge zu testen, ist ein minimaler python-Webserver:

[https://gist.github.com/bradmontgomery/2219997](url)

Oder du machst es wie ich und verwendest deine Hausautomation zum Schalten als Gateway.
Ich kenne Pimatic zwar nicht, aber sowas sollte doch gehen, oder?
http://[IP-Adresse]/api/device/nachtlamp-wiebe/turnOn
[https://forum.pimatic.org/topic/46/trigger-by-url](url)

VG
Flo

**Comment by camueller** [comment]
Ab Version 1.6.7 gibt es die Möglichkeit, Benachrichtigungen bei Ereignissen (dazu gehören auch "Einschalten" und "Ausschalten") zu versenden. Zum Versenden wird ein Shell-Script aufgerufen. Das entspricht damit einem Shell Execute Schalter, wenn der neue Default-Switch `Zählerbasierter Zustandsmelder" verwendet wird.
