### ISSUE TITLE
SAE-Service startet nicht

### ISSUE THREAD

**Issue by kht1011** [camueller/SmartApplianceEnabler#468]
Hallo,

Ich habe mich die Tage auch ein wenig mit dem SAE versucht. Ich habe leider ein kleines Problem. Wenn der Server auf dem der SAE läuft neustartet, funktioniert der SAE Service nicht mehr.

![pasted-from-clipboard](https://user-images.githubusercontent.com/125148195/218271951-fa2b1f8e-41c6-413a-8383-e8980969ddef.png)

Die ersten 60 Sekunden "läuft" der Service noch

![pasted-from-clipboard](https://user-images.githubusercontent.com/125148195/218271968-b95024f2-4909-41c7-9801-bf3c0d292c88.png)

Und nach 60 Sekunden wird der Service dann beendet.

![pasted-from-clipboard](https://user-images.githubusercontent.com/125148195/218271978-d3dc18ec-ebd8-43d4-a2ea-bb2d11000002.png)

Was mich etwas verwundert ist, dass wenn ich den Service jetzt per Hand starte, alles funktioniert

![pasted-from-clipboard](https://user-images.githubusercontent.com/125148195/218271986-b2724af6-10f2-4e04-80c2-36a9371a7a99.png)

![pasted-from-clipboard](https://user-images.githubusercontent.com/125148195/218271994-f215ace3-324f-4e9a-9de8-632b773f5503.png)

Kann mir jemand helfen, und mir sagen, was ich falsch mache.

Ja, es handelt sich um eine manuelle Installation, da der SAE auf einem Ubuntu 22.04 Server läuft.

Gruß

**Comment by camueller** [comment]
Die Screenshots sind leider unbrauchar von der Auflösung.

Wenn ein manueller Start des Service funktioniert, aber nicht der Start im Rahmen des Bootens, wird der SAE möglicherweise zu zeitig gestartet, z.B. bevor das Netzwerk verfügbar ist. Die bereitgestellten Scripts sind für Raspberry Pi. Für andere Systeme müssen diese möglicherweise angepasst werden.

Da hier kein Fehler des SAE vorliegt, schliesse ich diesen Issue.

**Comment by kht1011** [comment]
Entschuldige die schlechten Screenshots, ich hatte sie auf einer anderen Seite gepostet und nicht mehr in der Originalqualität. Ich habe inzwischen einen Workaround gefunden. 
Durch Veränderung des smartapplianceenabler.service. Ich habe Restart=on-failure hinzugefügt. 
Ich weiß zwar immernoch nicht was der Grund für den Fehler ist, aber es funktioniert jetzt. Der Service startet ein erstes mal und stürzt nach 60 Sekunden ab, danach startet er neu und funktioniert 😀
