### ISSUE TITLE
Docker Anleitung

### ISSUE THREAD

**Issue by maggu2810** [camueller/SmartApplianceEnabler#470]
Hallo und vielen Dank für all deine Mühen und deine Software.

Ich folgte eben der Anleitung zur Docker basierten Installation und möchte dir ein paar Anmerkungen zur Anleitung da lassen.

# Tippfehler

Die YAML Datei URL ist nicht
https://github.com/camueller/SmartApplianceEnabler/raw/master/run/etc/docker/compose/docker-compose.yaml
sondern
https://github.com/camueller/SmartApplianceEnabler/raw/master/run/etc/docker/compose/docker-compose.yml

Die Dateierweiterung muss von yaml in yml geändert werden, ansonsten geht der wget Befehl nicht.

# Dateirechte Systemd Service

Funktioniert auch so, ist aber formal nicht richtig.

```
chmod 755 /lib/systemd/system/smartapplianceenabler-docker-compose.service
```

Es ergibt keinen Sinn, das executable flag für eine Systemd Service Datei zu setzen. Diese Datei ist nicht für sich ausführbar.
Die Rechte müssten eher 0644 lauten.

# Pfad Service File

Anstatt /lib/... würde ich /etc/... vorschlagen.
Wenn man eine manuelle Dockerinstallation wählt, dann sollte man auch nicht in /lib/... des Systems schreiben, sondern dies in der vollen Verantwortung des Paketmanagers lassen.

**Comment by camueller** [comment]
Vielen Dank für die Hinweise. Ich habe sie alle übernommen.
