### ISSUE TITLE
Zähler: Umrechnungsfaktor

### ISSUE THREAD

**Issue by maggu2810** [camueller/SmartApplianceEnabler#472]
Ist hier nicht ein Fehler drin bezüglich Multiplikation vs. Division?

Für den Parameter `Zählerstand` wird der Wert in kWh und für den Parameter `Leistung` in W benötigt. Falls die Werte in anderen Einheiten geliefert werden, muss ein muss ein `Umrechnungsfaktor` angegeben werden, der mit dem gelieferten Wert multipliziert wird, um ihn in die benötigte Einheit umzurechnen. Wird beispielsweise der Parameter `Leistung` in mW geliefert, muss als `Umrechnungsfaktor` der Wert `1000` angegeben werden.

Wenn wir mW haben und diesen mit dem Faktor multiplizieren, dann muss ich doch mit 0.001 multiplizieren um W zu erhalten.
1000 Wäre doch, wenn wir kW hätten und in W umrechnen.

**Comment by camueller** [comment]
Auch hier hast Du Recht mit Deinem Hinweis. Habe die Dokumentation aktualisiert.
