### ISSUE TITLE
go-e http API v2 usage

### ISSUE THREAD

**Issue by humi208** [camueller/SmartApplianceEnabler#474]
Die neue API V2 ist ab HW V3 verfügbar. Der Vorteil ist, dass die API V2 den Energiewert nicht in 0,1kWh, sondern 0,001 kWh liefert. Wäre es möglich abhängig von der HW Version die neue API V2 zu verwenden?

v1:
https://github.com/goecharger/go-eCharger-API-v1/blob/master/go-eCharger%20API%20v1%20DE.md
v2:
https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md

**Comment by camueller** [comment]
Der SAE liefert nur Vorlagen für Wallboxen. Wenn sich APIs ändern oder neue APIs verfügbar sind freue ich mich über entsprechende Pull-Requests.
