### ISSUE TITLE
<Status> not updated if Meter receives impulses

### ISSUE THREAD

**Issue by tho-wa** [camueller/SmartApplianceEnabler#5]
Status field is not set to "Online" if meter receives impulses, so consumption is not displayed in Sunny Portal. 

`<DeviceStatus><DeviceId>F-11223344-112233445598-00</DeviceId><EMSignalsAccepted>false</EMSignalsAccepted><Status>Offline</Status><PowerConsumption><PowerInfo><AveragePower>5220</AveragePower><MinPower>831</MinPower><MaxPower>836</MaxPower><Timestamp>0</Timestamp><AveragingInterval>60</AveragingInterval></PowerInfo></PowerConsumption></DeviceStatus>`

**Comment by camueller** [comment]
DeviceStatus refactored by https://github.com/camueller/SmartApplianceEnabler/commit/6694fe90f01504b7d670282288a5ed04e3ff6905
