### ISSUE TITLE
Missing URL in HTTP switch

### ISSUE THREAD

**Issue by normanth** [camueller/SmartApplianceEnabler#507]
Guten Tag, wirklich tolle Lösung - vielen, vielen Dank dafür!

Beim HTTP-Schalter finde ich entgegen der Anleitung zum Ein- und Ausschalten nur ein URL-Eingabefeld und keine Möglichkeit, einen Parameter o.ä. mitzugeben. Insofern ist nur ein Wechsel zwischen den Zuständen als HTTP-Aufruf möglich. Ist das so gewünscht? Wert und Umrechnungsfaktor verstehe ich in diesem Zusammenhang nicht - ich finde dazu auch nichts in der Anleitung.

Link zur Anleitung: https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/HttpSwitch_DE.md

Lieben Gruß, Norman

![screenshotHttpSchalter](https://user-images.githubusercontent.com/25548025/227807699-b116ec81-2953-44b8-9f20-942eb87e0c19.png)

![screenshotHttpSchalterAnleitung](https://user-images.githubusercontent.com/25548025/227807703-345944ae-1cf7-4049-8f63-4592d547c080.png)

**Comment by normanth** [comment]
Eine Ergänzung: Wert und Umrechnungsfaktor verstehe ich auch in diesem Zusammenhang nicht - ich finde dazu auch nichts in der Anleitung.

**Comment by normanth** [comment]
Und noch eine Info auch wenn Offtopic: Die in der Anleitung beschriebene manuelle Docker Installation von avanux/smartapplianceenabler (Docker Hub) installiert die alte Version mit dem alten War-File (2.1.0) - und das War-File lässt sich dann anscheinend auch nicht einfach wie unter Update beschrieben austauschen - zumindest startete mein Dockercontainer dann nicht mehr.

Anleitung:
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md

Dockerfile Docker Hub:
https://hub.docker.com/layers/avanux/smartapplianceenabler-arm32/latest/images/sha256-b3bfa160f4dbb5247eec579e577bf445bcdcb7191443c596524088638f03e284?context=explore

**Comment by camueller** [comment]
Bei HTTP GET sind die Parameter Teil der URL.

Umrechungsfaktor ist eigentlich nicht relevant.

Im Docker-Container wird die eine War-Datei ausgetausch, sondern Du musst das Image in der richtigen Version verwenden. Du verwendest das "alte" Repository - das neue ist `avanux/smartapplianceenabler` (ohne `arm32`).

**Comment by normanth** [comment]
Hi,

danke für die Antwort, aber es gibt ja nur ein Feld zum Eintragen einer URL für das Ein- UND Ausschalten. Ich kann also keine unterschiedlichen Parameter angeben. Bitte schau mal in den Screenshot! Da fehlt das Feld für die Eingabe der Ausschalten URL.

Gruß, Norman

Von meinem iPhone gesendet

Am 27.03.2023 um 06:43 schrieb Axel Müller ***@***.***>:

﻿

Bei HTTP GET sind die Parameter Teil der URL.

Umrechungsfaktor ist eigentlich nicht relevant.

Im Docker-Container wird die eine War-Datei ausgetausch, sondern Du musst das Image in der richtigen Version verwenden. Allerdings scheint tatsächlich im Dockerfile noch die 2.1.0 zu stehen - ich muss das mal prüfen ...

**Comment by camueller** [comment]
Ja, weil Du "Parameter hinzufügen" gedrück hast statt "URL hinzufügen".

**Comment by normanth** [comment]
oh wie peinlich - danke!!
