### ISSUE TITLE
SG Ready startet einfach nicht. Settings falsch?

### ISSUE THREAD

**Issue by Exo84** [camueller/SmartApplianceEnabler#511]
System läuft ohne gemeldet Fahler seit Ende 2022. Version 2.2.2
Zunächst dachte ich, dass in den dunklen Monaten einfach zu wenig PV Energie kommt.
Im März gab es nun diverse Tage mit hohem PV Ertrag. Leider wurde der SG Ready Anschluss nicht geschaltet.
Wenn ich den Kontakt "manuel" über die Ampel schalte, funktioniert es und wird auch entsprechend im SMA Portal dargestellt.

Ich glaube, irgendwelche Settings passen einfach nicht.
Bitte um Unterstützung. 
Bitte keinen Verweis auf eine Erklärung. Ich habe die entsprechenden Seiten gefühlt 200 mal durchgelesen :-).

**Folgende Screenshots der aktuellen Settings:**

**SAE:**

![image](https://user-images.githubusercontent.com/116544659/229268448-a75f15c3-75de-4bdf-9204-389947c73351.png)

![image](https://user-images.githubusercontent.com/116544659/229268458-7fecbf5c-0332-4783-a446-f3744374ee70.png)

![image](https://user-images.githubusercontent.com/116544659/229268367-a0b0cf51-4af9-484a-8a25-c220eb587118.png)

![image](https://user-images.githubusercontent.com/116544659/229268374-b96f4a40-6591-4ef3-ae47-49610dc592d2.png)

![image](https://user-images.githubusercontent.com/116544659/229268389-010f5aff-0536-4331-a906-342905b5e753.png)

![image](https://user-images.githubusercontent.com/116544659/229268481-e02d6359-84c1-4eac-a482-687684e2a12c.png)

![image](https://user-images.githubusercontent.com/116544659/229268495-1f4cf7c4-31e0-45aa-b5b9-03780f37ab08.png)

![image](https://user-images.githubusercontent.com/116544659/229268507-3c19bd59-8b96-4fc5-800d-e888fa9933c1.png)

![image](https://user-images.githubusercontent.com/116544659/229268519-70e47b0e-e83c-48b0-949d-bec847310b82.png)

**Home Manager:**

Beispiel "guter" PV tag:
![image](https://user-images.githubusercontent.com/116544659/229268626-8f4e5fb8-6b73-41c9-b3c6-f8161a4e809c.png)

![image](https://user-images.githubusercontent.com/116544659/229268687-ea1168db-9a6c-447f-9890-c16992a86190.png)

Beispiel manuelles Starten via SAE:

![image](https://user-images.githubusercontent.com/116544659/229268769-0a283e90-61e2-4684-aef0-ce508f234f57.png)

**Comment by camueller** [comment]
Deine WP zieht wirklich 19,7 kW, wenn sie läuft?? Wenn Du nicht wenigstens 25 kW Überschuss hast, brauchst Du keinen Einschaltbefehl erwarten.

Ausserdem solltest Du die min. Einschaltdauer und max. Einschaltdauer erstmal nicht setzen, damit Du die Chance erhöhst, überhaupt einen Einschaltbefehl zu bekommen.

**Comment by Exo84** [comment]
Nein, sie läuft eigentlich nie mit 19,7 kW der Wert entspricht der maximalen Aufnahme lt. Typenschild. 
Ich folge bei dem Attribut der Beschreibung:

![image](https://user-images.githubusercontent.com/116544659/229270937-1c65ba4c-a3c1-419f-825b-6d556cb51173.png)

In der Regel läuft Sie mit ca. etwas über 2 kW an und läuft dann um die 1,4 kW weiter.

Ist der Wert der maximalen Leistung nun der wichtige Wert?
Wie wird der Wert berücksichtigt?

**Comment by camueller** [comment]
Der SHM benörigt die Information für die Planung und damit auch die Entscheidung, ob ein Einschaltbefehl gesendet wird. Du solltest für die max. Leistungsaufnahme den Wert angeben, den sie tatsächlich maximal zieht.

**Comment by Exo84** [comment]
Ok, ich stelle mal 1600 W ein und beobachtet es ein paar Tage.

**Comment by Exo84** [comment]
Der sonnige Tag geht zu Ende.

Leider wurde der Kontakt nicht geschlossen. Wir hatten zwischen 11 bis 15 Uhr permanent deutlich über 1600 W ins Netz gedrückt.

An was kann es den liegen?

Danke

**Comment by camueller** [comment]
Wieviel ist denn "deutlich über 1600W"? Du musst das ausprobieren mit verschiedenen Zahlen, nur Du kannst Dein Setup zum Laufen bekommen.

Ich hatte heute Einschalt-Befehle mit vergleichbarem Setup.

**Comment by Exo84** [comment]
Zwischen 11 bis 12 sind permanent 4 kW ins Netz gegangen.

Im sunny Portal Menüpunkt Verbrauchersteuerung und Planung gibt es ja unter den Verbrauchern eine kleine Tabelle(Verbraucherplanung).
Auch hier taucht nix auf. 
Kann es am sunny Portal liegen?

Das ich es zum laufen bringen muss ist klar, ich bin aber relativ ratlos.

**Comment by camueller** [comment]
Nach welcher Anleitung hast Du Dich denn gerichtet? Den Zusammenhang mit "SG Ready" habe ich nur bei der [Einschalt-Option](https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/SwitchOnOption_DE.md) dkomumentiert.
Diese hast Du laut Deinem Screenshot aber nicht aktiviert. Damit die Einschalt-Optiongut funktioniert, sollest Du mehrere Zeitfenster definieren, die jeweils eine Stunde dauern.

So sieht das bei mir aus:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/4489628/229532831-eb4d37c2-309a-4812-bf68-ff707ea04440.png">

Danach sollte Dein Sunny Portal so aussehen:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/4489628/229532627-8724d4c1-1883-4675-8576-6254b46685cf.png">

**Comment by Exo84** [comment]
Puh, es gibt wohl nicht die eine Beschreibung.

Ich Split mal die Zeiten auf.
Morgen soll es wieder sonnig werden.

Ist Ihm eigentlich der Leistungswert im Master Zähler Datensatz egal?

**Comment by camueller** [comment]
Die Zählerwerte sind für den Einschaltbefehl erstmal egal.

**Comment by Exo84** [comment]
ich meine den folgenden:

![image](https://user-images.githubusercontent.com/116544659/229536816-6cfa9811-fa05-45cc-b797-6378403ecdfd.png)

**Comment by camueller** [comment]
Hatte ich weiter oben schon beantwortet.

**Comment by Exo84** [comment]
Es ist leider nicht ganz klar für mich.

Ich habe hier zwei Geräte angelegt.

Bei der WP habe ich jetzt 1600 W drin sowie auch bei dem SG Ready "Gerät" 1600 W drin.
Saldiert er das ganze irgendwie und wartet auf 3200 W?

**Comment by camueller** [comment]
Für den SHM sind das zwei Geräte. Da wird nix saldiert. Über den Master-Slave-Zähler wird die Leistungsaufnahme einem der Geräte zugeordnet. Dementsprechend und weil das Master-Gerät als Schalter nur den "Zählerbasierten Zustandsmelder" hat, ist ja auch immer nur ein Gerät eingeschaltet.

**Comment by Exo84** [comment]
Es ist zum verrückten werden.

Seit 1,5 h 12 kW PV Leistung.
Verbrauch im Peak mal kurz 2 kW (Waschmaschine).

Der SG Kontakt bekommst kein Signal.

Times beim SG Ready habe ich gestern nach deinem Vorbild eingestellt.
Vier Blöcke start 10 bis 10:59 jeweils mit 0:43 min. Usw.

Leistungsmax. Steht auf 1000 W.

Ihr sehe aber die terminblöcke auch nicht im Sunny Portal. Es erscheint nur jeweils eine durchgezogen Linie.

**Comment by camueller** [comment]
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/QA_DE.md#semp3

**Comment by Exo84** [comment]
Problem gelöst. Lösung. SG Ready Geräte nochmal im Sunny Portal & SAE gelöscht. Gerät mit neuer ID im SAE angelegt und entsprechend im Sunny Portal eingebunden. Funktioniert! Settings des neuen Gerätes 100% Identisch wie vorher.

**Comment by camueller** [comment]
Sehr gut. Ich werde die Dokumentation erweiern bzgl. der stündlichen Zeitpläne.

**Comment by Exo84** [comment]
Glaube nicht das es daran lag. Nachdem es heute früh ging habe ich einen Termin eingestellt und es funktioniert super. (Ich steuere ja auch nur das eine Gerät)

Ich glaube eher, dass es daran lang das ich als erstes Gerät den SG Kontakt angelegt hatte. Dann irgendwann drauf gekommen bin das ich ja zwei Geräte anlegen muss. In Folge war dann das neue Gerät die WP mit dem Master Zähler. Und das erste Gerät der Slave.

Deswegen war wohl der Wurm drin.
