### ISSUE TITLE
Notifications werden nicht versendet, wenn Einstellung auf Standard-Wert "alle" steht

### ISSUE THREAD

**Issue by Nightstalker81** [camueller/SmartApplianceEnabler#524]
Wenn die Benachrichtigungen auf dem Standard-Wert "alle" (= keine Benachrichtigungen aktiviert) stehen, dann werden keine Benachrichtigungen versendet.
Grund hierfür ist eine Inkonsistenz bezüglich der Behandlung der "requestedNotifications" Variable des "NotificationHandler".
In der Methode "isRequestedNotification" wird nur dann "true" zurückgegeben, wenn auch mindestens eine "requestedNotification" gesetzt ist (Wert von "requestedNotifications" != NULL ).
In der Methode "setRequestedNotifications" wird für einen NULL-Wert aber davon ausgegangen, dass dies "Alle Benachrichtigungen aktiv" bedeutet.

In den Logs des SAE ist dies ersichtlich, da dort immer die Meldung "Ignoring notification of type X" auftaucht.

**Comment by Nightstalker81** [comment]
Habe hierzu bereits einen Fix erstellt und einen Pull request eingestellt:
https://github.com/camueller/SmartApplianceEnabler/pull/525

**Comment by Nightstalker81** [comment]
@camueller es gibt wohl noch ein weiteres Thema, welches sich auch auf die Benachrichtigungen bezieht.
Ich dachte erst ich hätte es falsch konfiguriert, aber es scheint wohl nur in Verbindung mit dem "StartingCurrentSwitch" aufzutreten.
Dieser sendet nie Benachrichtigungen, da eine abgefragte Bedingung nie eintreten kann:
![image](https://github.com/camueller/SmartApplianceEnabler/assets/36797373/ce7d5580-1e62-423d-9718-a2712bafb60f)

Der Wert "on" wird ein paar Zeilen vorher auf "switchOn" gesetzt und kann somit bei der Prüfung der Bedingung niemals abweichend sein.
Soll ich einen separaten Issue einstellen oder willst Du das auch hierüber behandeln?

Fix erstelle ich auf Basis dessen, wie es z.B. im HttpSwitch aussieht.
Pull Request folgt.

**Comment by Nightstalker81** [comment]
@camueller Pull Request ist erstellt: #527

**Comment by camueller** [comment]
Danke für die PRs!!

**Comment by camueller** [comment]
Nachdem ich Deinen PR gemergt habe und den darauf gebauten Stand einige Tage in Betrieb habe, ist mir aufgefallen, dass ich jetzt auch Benachrichtigungen bekomme, obwohl der Schalter ausgeschaltet ist.
Das liegt daran, dass durch Deinen ersten PR `isRequestedNotification` auch dann `true` liefert, wenn `requestedNotifications == null` ist.

Die Checkbox `Aktiviert` entspricht dem Vorhandensein eines XML-Elements `Notifications` innerhalb eines Schalters/Zählers. Wenn das nicht vorhanden ist, sollen `isRequestedNotification` den Wert `false` liefern und damit keine Notifications versenden.

Wenn alle Notifications gesendet werden sollten sorgt `this.requestedNotifications.getTypes() == null` in der Bedingung dafür, dass  `isRequestedNotification` den Wert `true` liefert.

Insofern werde ich Deine Änderungen aus dem ersten PR zurückrollen.
Was auch immer bei Dir nicht funktioniert hat, hat eine andere Ursache.

**Comment by Nightstalker81** [comment]
Sollte passen. Ursache bei mir war vermutlich der zweite Fall.
Ich setze die Notifications nur im Zusammenhang mit Schaltern mit Anlaufstromerkennung ein.
