### ISSUE TITLE
Temperature of hot water storage

### ISSUE THREAD

**Issue by biggestcrunch** [camueller/SmartApplianceEnabler#528]
I have connected the SAE via Modbus TCP to a Siemens LOGO 8.
The Logo is switching a 3 phase Heater via power relais.
I have collected the bottom and top temperature of the Storage via a PT100 connected to the Siemens LOGO. I can now read the register of the analag value via modbus.
It will be interesting to see this temperatur in the status bar of the SAE and it will be also interesting to see this temperature in the daily power curves of the Sunny Portal.

Do you think this might be possible?

Thank you very much!
Jens

**Comment by camueller** [comment]
No.
