### ISSUE TITLE
can't install it on a raspi 4

### ISSUE THREAD

**Issue by larschri15** [camueller/SmartApplianceEnabler#529]
this is what i got when i connect to ssh on the bottom are the errors :
pi@raspberrypi:~ $ sudo bash
root@raspberrypi:/home/pi#  curl -sSL https://raw.githubusercontent.com/camueller/SmartApplianceEnabler/master/install/setup.sh | sh
--2023-05-13 19:07:41--  https://raw.githubusercontent.com/camueller/SmartApplianceEnabler/master/install/install2.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6204 (6.1K) [text/plain]
Saving to: ‘/usr/local/bin/install2.sh.2’

install2.sh.2                          100%[============================================================================>]   6.06K  --.-KB/s    in 0.001s

2023-05-13 19:07:41 (5.37 MB/s) - ‘/usr/local/bin/install2.sh.2’ saved [6204/6204]

--2023-05-13 19:07:41--  https://raw.githubusercontent.com/camueller/SmartApplianceEnabler/master/install/install.config
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8000::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2144 (2.1K) [text/plain]
Saving to: ‘/usr/local/etc/install.config’

install.config                         100%[============================================================================>]   2.09K  --.-KB/s    in 0.003s

2023-05-13 19:07:42 (642 KB/s) - ‘/usr/local/etc/install.config’ saved [2144/2144]

+ CONFIG_FILE=/usr/local/etc/install.config
+ . /usr/local/etc/install.config
+ PASSWORD=sae
+ WIFI_SSID=
+ WIFI_PSK=
+ WIFI_COUNTRY=DE
+ TIMEZONE=Europe/Berlin
+ INSTALL_MBUSD=true
+ INSTALL_WEBMIN=true
+ LOG=/tmp/install.log
+ PREFIX=**********
+ PACKAGES=openjdk-11-jre-headless pigpiod jq mosquitto
+ WEBMIN_VERSION=2.001
+ PARENT_SCRIPT=/etc/rc.local
+ PARENT_SCRIPT_BACKUP=/etc/rc.local.bak
+ SCRIPT2=install2.sh
+ INSTALL_DIR=/usr/local/bin
+ SAE_HOME=/opt/sae
+ POWER_LED=/sys/class/leds/led1/brightness
+ [ true = true ]
+ PACKAGES=openjdk-11-jre-headless pigpiod jq mosquitto git cmake
+ [ true = true ]
+ PACKAGES=openjdk-11-jre-headless pigpiod jq mosquitto git cmake perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl shared-mime-info apt-show-versions python
+ [ -n  ]
+ echo ********** Waiting until boot is complete ...
+ sleep 30
+ echo ********** Update software catalog ...
+ apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

+ echo ********** Upgrading system ...
+ apt upgrade -y

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

+ echo Allow shared mounts by udevd (possibly reset by system upgrade) ...
+ sed -i s/PrivateMounts\=yes/PrivateMounts\=no/g /lib/systemd/system/systemd-udevd.service
+ echo ********** Setting time zone ...
+ echo Europe/Berlin
+ cat /etc/timezone
+ echo ********** Copy zoneinfo ...
+ cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
+ echo ********** Install required packages ...
+ apt install openjdk-11-jre-headless pigpiod jq mosquitto git cmake perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl shared-mime-info apt-show-versions python -y

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

+ echo ********** Install wiring-pi in order support SAE < 2.x ...
+ wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/wiringpi-latest.deb -P /tmp
+ dpkg -i /tmp/wiringpi-latest.deb
dpkg: error: cannot access archive '/tmp/wiringpi-latest.deb': No such file or directory
+ echo ********** Setting up pigpiod ...
+ sed -i s/ExecStart=\/usr\/bin\/pigpiod -l/ExecStart=\/usr\/bin\/pigpiod/g /lib/systemd/system/pigpiod.service
+ systemctl start pigpiod
Warning: The unit file, source configuration file or drop-ins of pigpiod.service changed on disk. Run 'systemctl daemon-reload' to reload units.
+ systemctl enable pigpiod
+ echo ********** Setting up mosquitto ...
+ sed -i s/persistence true/persistence false/g /etc/mosquitto/mosquitto.conf
+ echo listener 1883
+ echo allow_anonymous true
+ systemctl start mosquitto
+ systemctl enable mosquitto
Synchronizing state of mosquitto.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mosquitto
+ echo ********** Setting up user ...
+ mkdir /opt/sae
mkdir: cannot create directory ‘/opt/sae’: File exists
+ groupadd sae
groupadd: group 'sae' already exists
+ useradd -d /opt/sae -c SmartApplianceEnabler -g sae -M sae -s /bin/bash
useradd: user 'sae' already exists
+ usermod -a -G gpio,sudo sae
+ echo sae
+ echo sae
+ passwd sae
New password: Retype new password: passwd: password updated successfully
+ cp /home/pi/.profile /opt/sae
+ cp /home/pi/.bashrc /opt/sae
+ echo ********** Installing SAE ...
+ wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/smartapplianceenabler -P /opt/sae
+ chmod 755 /opt/sae/smartapplianceenabler
+ wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/etc/default/smartapplianceenabler -P /etc/default
+ chown root.root /etc/default/smartapplianceenabler
+ chmod 644 /etc/default/smartapplianceenabler
+ [ -n  ]
+ wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/logback-spring.xml -P /opt/sae
+ chmod 644 /opt/sae/logback-spring.xml
+ curl --no-progress-meter -H Accept: application/vnd.github.v3+json https://api.github.com/repos/camueller/SmartApplianceEnabler/releases
+ jq -c .[] | select( .prerelease == false) | .tag_name
+ head -n 1
+ tr -d "
+ SAE_VERSION=2.2.2
+ wget https://github.com/camueller/SmartApplianceEnabler/releases/download/2.2.2/SmartApplianceEnabler-2.2.2.war -P /opt/sae
+ chown -R sae:sae /opt/sae
+ echo ********** Configure systemd ...
+ wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/lib/systemd/system/smartapplianceenabler.service -P /lib/systemd/system
+ chown root.root /lib/systemd/system/smartapplianceenabler.service
+ chmod 755 /lib/systemd/system/smartapplianceenabler.service
+ systemctl enable smartapplianceenabler.service
+ systemctl daemon-reload
+ echo ********** Starting SAE ...
+ systemctl start smartapplianceenabler.service
+ [ true = true ]
+ echo ********** Installing Webmin ...
+ wget http://prdownloads.sourceforge.net/webadmin/webmin_2.001_all.deb -P /tmp
+ dpkg -i /tmp/webmin_2.001_all.deb
+ sudo systemctl start webmin.service
+ [ true = true ]
+ echo ********** Installing mbusd ...
+ cd /tmp
+ git clone https://github.com/camueller/mbusd.git
Cloning into 'mbusd'...
remote: Enumerating objects: 775, done.
remote: Total 775 (delta 0), reused 0 (delta 0), pack-reused 775
Receiving objects: 100% (775/775), 861.24 KiB | 2.63 MiB/s, done.
Resolving deltas: 100% (489/489), done.
+ cd mbusd
+ mkdir build
+ cd build
+ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
+ make
+ make install
+ systemctl daemon-reload
+ cp /etc/mbusd/mbusd.conf.example /etc/mbusd/mbusd-ttyUSB0.conf
+ echo ********** Clean up installation files ...
+ rm -v /etc/rc.local
rm: cannot remove '/etc/rc.local': No such file or directory
+ mv -v /etc/rc.local.bak /etc/rc.local
mv: cannot stat '/etc/rc.local.bak': No such file or directory
+ rm -v /usr/local/etc/install.config
+ echo ********** /usr/local/bin/install2.sh finished
/usr/local/bin/install2.sh: 143: cannot create /sys/class/leds/led1/brightness: Directory nonexistent
+ sleep 3600
/usr/local/bin/install2.sh: 145: cannot create /sys/class/leds/led1/brightness: Directory nonexistent
root@raspberrypi:/home/pi#

**Comment by camueller** [comment]
```
Saving to: ‘/usr/local/bin/install2.sh.2’
```
It had to name the downloaded file `install2.sh.2` because there was alreay another file named `install2.sh`
Your SD card is not emty.

**Comment by larschri15** [comment]
i tried again reinstaled it on sd card now getting this error:+ echo ********** Clean up installation files ...
+ rm -v /etc/rc.local
+ mv -v /etc/rc.local.bak /etc/rc.local
mv: cannot stat '/etc/rc.local.bak': No such file or directory
+ rm -v /usr/local/etc/install.config
+ echo ********** /usr/local/bin/install2.sh finished
/usr/local/bin/install2.sh: 143: cannot create /sys/class/leds/led1/brightness: Directory nonexistent
+ sleep 3600

**Comment by camueller** [comment]
I have not received any problem reports regarding installation recently. The log you posted initially and also the one posted now suggest that you are doing something wrong. I'm afraid I cannot help you.

**Comment by larschri15** [comment]
i got it installed after i installed the manual thanks for the good manual! i have 1 small question how can i set the so meter in the software because i can't find it anywhere

**Comment by camueller** [comment]
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/S0Meter_EN.md

**Comment by larschri15** [comment]
I have already read the page, but I do not understand how to get this screen: https://github.com/camueller/SmartApplianceEnabler/blob/master/pics/fe/S0Meter_EN.png
 i can only find the this one:
https://github.com/camueller/SmartApplianceEnabler/blob/master/pics/fe/ApplianceNew_EN.png

**Comment by camueller** [comment]
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Configuration_EN.md

**Comment by larschri15** [comment]
I am so sorry for all the questions, I finally got it fully installed thanks!

**Comment by camueller** [comment]
Glad you managed it.

BTW: Where do you live?

**Comment by larschri15** [comment]
Belgium

**Comment by larschri15** [comment]
A latst question how can i add a S0 meter in the software i can't find it  i also followed this manual :https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/S0Meter_EN.md but i can't pinpoint the type of meter can it be because i can't connect the sae to sunny portal?

**Comment by camueller** [comment]
Thanks for pointing this out. Should be fixed by now.
