### ISSUE TITLE
nicht erreichbarer HTTP-basierter Zähler zählt weiter

### ISSUE THREAD

**Issue by J0EK3R** [camueller/SmartApplianceEnabler#539]
Moinmoin Axel,

vielen Dank nochmal für Dein wunderbares kleines Stück Software, das problemlos seinen Dienst tut! :)

Ich verwende den TASMOTA-Zwischenstecker von [nous](https://nous.technology/smart/sockets/).

Ist der Zwischenstecker vom SAE per HTTP plötzlich nicht mehr erreichbar (z.B. weil er von einem Mitglied des Haushalts abgezogen wurde) und der SAE hatte bei der letzten erfolgreichen HTTP-Abfrage einen Energieverbrauch und damit eine Leistung ermittelt, dann wird die zuletzt erfolgreich berechnete Leistung weiterhin an den Homemanager geschickt bzw. nicht auf 0 zurückgesetzt.
Das hat zur Konsequenz, dass die Energieverbrauchskurve (also Leistungskurve) auf der SMA-Homepage weiterläuft...

Ich hätte erwartet, dass der SAE bei nicht erreichbaren Energiezählern eine Null-Leistung errechnet.

Bug, Feature oder Fehlkonfiguration meinerseits?

Die Einstellung für **Zähler** ist:
Typ: HTTP
Format: JSON
URL: http://nous03.fritz.box/cm?user=ich&password=geheim&cmnd=Status%208
Parameter: Zählerstand
Methode: GET
Pfad für Extraktion: $.StatusSNS.ENERGY.Total
Umrechnungsfaktor: 1

Die Einstellung für **Schalter** ist:
Typ: Zählerbasierter Zustandsmelder

**Comment by camueller** [comment]
Ist vermutlich bei der Umstellung auf MQTT kaputtgegangen.
Habe es gefixt und erfolgreich getestet hier. Du kannst diese modifizierte 2.3.0 ebenfalls testen und mir Feedback geben:
https://drive.google.com/file/d/16Iw7AvCzxvMuwRuKWpLKVVWXNqi8rQ7h/view?usp=sharing

**Comment by J0EK3R** [comment]
Moinmoin,

habe gerade die modifizierte Version getestet...
...und für **gut** befunden! ;)

Also:
Im SunnyPortal "Verbraucherbilanz und -steuerung", "Aktuell"
* Gerät, dessen Energiebezug über einen Zwischenstecker von "Nous" angebunden ist, hat einen "aktuellen Verbrauch" größer 0
* Zwischenstecker abgezogen -> HTTP-Requests vom SAE werden nicht mehr beantwortet
* Nach einer gewissen Zeit (1 oder 2 Minuten) fällt der "aktuelle Verbauch" auf 0

Test bestanden! ;)
