### ISSUE TITLE
SAE 1.3.48 Speichern von Min/Max Laufzeiten geht nicht

### ISSUE THREAD

**Issue by Wiki591** [camueller/SmartApplianceEnabler#54]
Ich hab die letzten paar Tage damit verbracht, mich in den SAE einzuaqrbeiten.

Beim Ausprobieren der Versionen 1.2.1 und 1.3.48 ist mir aufgefallen, daß unter 1.3.48 die Eingabe im Zeit für Min / Max Runtime nicht gespeichert wird

Vor Speichern:
![grafik](https://user-images.githubusercontent.com/38845308/63473941-90bd7b00-c477-11e9-8017-82851a0aa893.png)

Nach Speichern & erneutem Aufruf:

![grafik](https://user-images.githubusercontent.com/38845308/63474009-c4000a00-c477-11e9-9497-92ae0ca4faf8.png)

**Comment by camueller** [comment]
In der 1.2.1 gabe es ein Problem mit dem Browser-Caching, was in der 1.3.x gelöst wurde. Bei Dir zeigen beide Screenshots die 1.2.1 und auch die ist "kaputt", wie Du an einigen Feld-Beschriftungen sehen kannst. Eigentlich muss die 1.3.48 so aussehen (im Screenshot steht zwar 1.3.49, aber es gab keine Änderungen):

![image](https://user-images.githubusercontent.com/4489628/63633154-a8495f00-c643-11e9-8b4b-7e51989ac617.png)

Ich teste mit Chrome, aber Firefox sollte auch problemlos gehen. Zu anderen Browsern kann ich nichts sagen.
