### ISSUE TITLE
MQTT Schalter mit Anlaufstromerkennung schaltet direkt wieder ab

### ISSUE THREAD

**Issue by Nightstalker81** [camueller/SmartApplianceEnabler#547]
Nach Aktualisierung auf Version 2.3.0 habe ich die Schalter und Zähler soweit möglich gemäß Dokumentation auf MQTT Schalter/Zähler umgestellt.
Generell funktioniert dies auch gut, allerdings scheint es ein Problem bei MQTT Schaltern mit Anlaufstromerkennung zu geben.

Zur Ausgangssituation:

- Es existiert ein Gerät bei dem die Option "Unterbrechung erlaubt" aktiv ist.
- Das Gerät hat einen eingerichteten MQTT Schalter mit Anlaufstromerkennung, einen MQTT Zähler mit Parameter "Zählerstand", sowie einen Zeitplan vom Typ "Tagesplan" und "Laufzeit".
- Zusätzlich sind Benachrichtigungen über Telegram für alle Ereignisse des Gerätes aktiv.

Folgende Situation stellt sich dar:
Nach erkanntem Anlaufstrom wird eine Laufzeitanforderung eingestellt, die durch den Zeitplan erst für den nächsten Tag ist.
Nun wird sich entschieden, das Gerät doch noch am selben Tag laufen zu lassen.
Hierzu wird über die Ampel eine manuelle Anforderung eingestellt.
Sehr zeitnah nachdem die Anforderung manuell eingestellt worden ist und die Benachrichtigung über den Start des Geräts eingegangen ist, wird das Gerät durch den SAE direkt wieder ausgeschaltet.

Ich habe bereits eine kurze Analyse der Log-Datei durchgeführt.
Anscheinend wird sehr zeitnah nach dem manuellen Einschalten des Gerätes der Abschaltzustand erkannt.

Die Log-Datei (bereinigt auf das relevante Gerät) hängt an.
[rolling-2023-07-21.log](https://github.com/camueller/SmartApplianceEnabler/files/12134391/rolling-2023-07-21.log)

**Comment by Nightstalker81** [comment]
Habe mir noch einmal die Mühe gemacht und das Verhalten weiter nachvollzogen.
Ursache scheint eine abweichende Zeitzone zwischen dem Host des SAE (rPi4) und den Tasmota Geräten gewesen zu sein.

Die Standardinstallation scheint wohl mit Zeitzone UTC zu laufen (jedenfalls habe ich diese nicht verstellt).
Für die Tasmota MQTT Meter/Switches wurde aber in der Dokumentation die Einstellung zur Sommerzeit (Timezone 99) beschrieben.
Leider reicht diese Einstellung alleine aber nicht aus, da die Zeitzone des Host gleich der Zeitzone des Tasmota Geräte sein.
Ansonsten führt due Zeitverschiebung dazu, dass das von mir beschriebene Verhalten auftritt.

Nachdem ich die Zeitzonen angeglichen habe, funktioniert die Anlaufstromerkennung wieder wie erwartet.
Dies sollte in der Dokumentation für Tasmota und MQTT angepasst werden.

**Comment by camueller** [comment]
Bei der automatischen Installation passiert das automatisch und für die manuelle Installation [ist das bereits dokumentiert](https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/InstallationManual_DE.md#zeitzone-einstellen).

**Comment by Nightstalker81** [comment]
> Bei der automatischen Installation passiert das automatisch und für die manuelle Installation [ist das bereits dokumentiert](https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/InstallationManual_DE.md#zeitzone-einstellen).

Merkwürdig… ich hatte (zugegebenermaßen vor längerer Zeit) die automatische Installation gemacht, sodass die Zeitzone eigentlich passen müsste.
Wurde die Einstellung der Zeitzone ggf. in der Vergangenheit irgendwann nachträglich hinzugefügt?
Umgestellt hatte ich in dem Bereich nichts.

**Comment by camueller** [comment]
Da ist seit 4 Jahren nichts geändert wurden:
https://github.com/camueller/SmartApplianceEnabler/blob/255fc272eecd48b5e62d0874e73230f47979c951/install/install2.sh#L49

**Comment by Nightstalker81** [comment]
So lange war es jetzt noch nicht im Einsatz.
Wie dem auch sei… das Thema ist erledigt.
Kann man maximal in die Doku oder FAQ aufnehmen. 🤷🏻‍♂️
