### ISSUE TITLE
Echten Status des Http-Schalters abfragen

### ISSUE THREAD

**Issue by Wiki591** [camueller/SmartApplianceEnabler#55]
Bei Integration des SAE in mein bestehendes Smarthome Netz hat sich herausgestellt, daß SAE ohne Weiteres die Änderung eines Schaltzustandes nicht bemerkt.

Zumindest für die schon implementierten Tasmota-Geräte wäre es ein Leichtes, direkt bei der Abfrage zur Identifikation/Übersetzung der gemessenen Leistung auch gleichzeitig den Schaltzustand mit abzufragen und diesen mit in die Schnittstelle zu SMA zu kommunizieren.

Inwiefern in dem Fall, daß der Schaltzustand von irgendetwas anderem (Smarthome-System, Druck auf den Schaltknopf etc.) gleichzeitig noch Parameter gesetzt werden sollten wie zB EMSignalsAccepted wäre allerdings noch zu überlegen.

**Comment by camueller** [comment]
Momentan reportet der SAE bei HttpSchaltern den Status, den erst selbst gesetzt hat, d.h. der Schalter wird nicht abgefragt. Dieses Verhalten wurde so in der Anfangszeit des SAE implementiert. Eigentlich spricht nichts dagegen, den echten Schaltzustand abzufragen, zumal das bei GPIO-Schaltern bereits auch so implementiert ist.

**Comment by camueller** [comment]
Für die Abfrage des Schaltzustandes muss eine URL angegeben werden können und ggf. eine Regex zum Auswerten.

**Comment by F-L-0** [comment]
Hallo Axel,

über dieses Feature würde ich mich auch freuen, trifft genau auf mein Setup mit fhem zu. Benefit wäre, das der Verbrauch im Portal auch dann erfasst wird wenn SAE nicht eingeschalten hat (sondern zB direkt am Gerät oder einem Gateway dazwischen).

VG
Flo

**Comment by camueller** [comment]
Implementiert: Man kann jetzt eine URL angeben zur Abfrage des Status, wobei wie gewohnt eine Regex angegeben werden kann. Wenn diese matcht, wird der Status als "ON" interpretiert.
Ergänzend kann auch JSON als Content-Typ angegeben werden und ein Pfad zum geweiligen Attribut.
Wird keine URL zur Status-Abfrage angegeben, entspricht das Verhalten des Http-Schalters dem bisherigen Verhalten.
Getestet mit Tasmota-basiertem Plug.

**Comment by camueller** [comment]
Implemented in version 1.4.16.
