### ISSUE TITLE
Verschobene Datei

### ISSUE THREAD

**Issue by Hallows94** [camueller/SmartApplianceEnabler#557]
Bei der Installation mit docker-compose, unter dem Schritt:

systemd mit docker-compose: 
https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/Docker_DE.md#systemd-mit-docker-compose

die Datei "smartapplianceenabler-docker-compose.service" mit dem Befehl:

sudo wget https://github.com/camueller/SmartApplianceEnabler/raw/master/run/etc/systemd/system/smartapplianceenabler-docker-compose.service \
    -P /etc/systemd/system

geladen werden.

Hier meldet der RPi 404 - not found.

Die Datei ist verschoben, der Command muss wie folgt geändert werden:

sudo wget https://github.com/camueller/SmartApplianceEnabler/blob/master/run/lib/systemd/system/smartapplianceenabler-docker-compose.service \
    -P /etc/systemd/system

geladen werden. Danach klappt es einwandfrei.

Danke!

System: RPi 4 - 2GB Ram, docker

![image](https://github.com/camueller/SmartApplianceEnabler/assets/112979848/bc21dd62-f922-492b-9bf4-43eae41d2771)

**Comment by camueller** [comment]
Vielen Dank für den Hinweis! Habe noch ein paar weitere Links gefixt.
