### ISSUE TITLE
Wallbox: Angabe einer Mindestlaufzeit

### ISSUE THREAD

**Issue by jual01** [camueller/SmartApplianceEnabler#566]
Ich habe am WE erfolgreich den GoE Charger eingebunden. Mit dieser Wallbox wird in erster Linie unser VW eUp! geladen. VW hat leider ein kleines Problem beim Überschußladen. Sobald 10 Ladevorgänge statt gefunden haben, wird kein erneuter Ladevorgang freigegeben. Im Auto gibt es wohl einen Zähler, der bei 10 sagt: "da scheint es ein Problem zu geben". Meines Wissens wurde dieser Zähler bei den ID-Modellen erhöht. Sobald die Grenze erreicht ist, kann man den Zähler quasi nur durch Starten des Autos wieder auf 0 setzen.

Das Problem ist nun, dass bei entsprechend schlechtem Wetter 10 Ladevorgänge relativ schnell mit kurzen Laufzeiten von Homemanager angestossen werden und dann nicht weiter geladen wird, wobei sehr wenig Strom geladen wurde.

Lösungsidee:
In meiner bisherigen Lösung mit einem 230V Ladegerät habe ich im SMA Portal immer eine Mindestlaufzeit von beispielsweise 30 Minuten angegeben. Dann wird das Auto bei 10 Ladevorgängen mindesten 300 Minuten geladen. Bei einer Wallbox gibt es eine solche Einstellung aber nicht über das SMA Portal. Daher wäre die Frage, ob sich so etwas im SAE abbilden lässt.

Also eine Angabe, wie lange die Wallbox laufen sollte, wenn sie eingeschaltet wird. Wenn dann ein Signal von SMA kommt, dass die Wallbox auszuschalten wäre, würde SAE den eigentlichen Ausschaltvorgang erst nach X Minuten Laufzeit durchführen. Zusätzlich müsste natürlich auf erneute Einschaltanforderungen aus dem SMA Portal reagiert werden und die Laufzeit in diesem Fall neu gestartet werden.

**Comment by camueller** [comment]
Das kann man im SAE in den Einstellungen als "Min. Einschaltdauern" setzen. Wenn man das tut, ist es natürlich weniger wahrscheintlich, dass man einen Einschaltbefehl bekommt. Und wenn eine Wolke vor die Sonne zieht, wird dann halt mit Netzbezug weitergeladen.

Bitte nicht nach Code-Anpassungen im SAE fragen, nur weil die Software im Auto schlecht implementiert ist.

**Comment by jual01** [comment]
Danke für die schnelle Rückmeldung. Die Einstellung hatte ich zunächst nicht gesehen, weil ich "Unterbrechung erlaubt" nicht abgeklickt hatte. Damit würde sich mein Ansatz dann wahrscheinlich umsetzen lassen.
