### ISSUE TITLE
Keine Live Daten im ennexOS Portal

### ISSUE THREAD

**Issue by humi208** [camueller/SmartApplianceEnabler#601]
Ich nutze den SHM bereits im ennexOS Portal und den SAE auf dem Raspi 5 um den Verbrauch der go-e Gemini 22kW Wallbox in das SMA System zu bekommen. 

Problem: Seitdem der SAE die Date der go-e Wallbox an den Home Manger liefert werden in der ennexOS Portal statt eines grünen Punktes ein gelber Punkt angezeigt mit der Info, dass nicht alle Geräte Live Daten liefern.

![ennexOS Portal Übersicht](https://github.com/camueller/SmartApplianceEnabler/assets/125356628/d389914f-4099-49a3-b1fc-35896c755c67)

Das Problem kommt von dem go-e Wallbox Charger, den SAE über den SHM2 anlegt, Laut Portal liefert dieses gerät keine Live Daten und der Punkt dieses Gerätes ist somit rot. Das ist so während des Ladens, obwohl die Liestung angezeigt wird, wie auch ohne Ladevorgang.

![ennexOS Portal Wallbox Ansicht](https://github.com/camueller/SmartApplianceEnabler/assets/125356628/008e12fa-0cfd-4839-98b8-3c6b51fac93a)

Wäre es möglich die Daten so zu liefern, dass der Staus der Wallbox grün ist (Live Daten liefert) und somit die Anlage auch einen grünen Status aufweist?
Liegt es eventuell daran, dass die Daten nur jede Minute an den SHM gesendet werden? Zumindest zeigt die Anzeige im Portal immer vor einer Minute für die Daten an.

**Comment by camueller** [comment]
Der SAE liefert die Daten an den Sunny Home Manager, wie im SEMP-Protokoll von SMA spezifiziert. Auf die Art und Weise der Anzeige im Sunny Portal oder Ennex Portal hat der SAE keinen Einfluss.

**Comment by humi208** [comment]
Einen Zusammenhang muss es ja geben. Die anderen Geräte werden auch korrekt mit grünem Status angezeigt. Wie oft werden die Leistungsdaten am den SHM vom SAE gesendet? 
Im Portal kommen sie wohl nur im Minutentakt an und dann neue Portal sieht das wohl als nicht live an...

**Comment by camueller** [comment]
Der Home Manger fragt den Status beim SAE ab, insofern bestimmt er die Abfrage-Häufigkeit. Sie ist in der Tat aber 60s. Deshalb rechnet der SAE auch nicht genauer.
