### ISSUE TITLE
PV-Überschuss für Mindestlaufzeit berücksichtigen

### ISSUE THREAD

**Issue by Devirex** [camueller/SmartApplianceEnabler#626]
Hallo,

ich habe eine frage zu folgendem Szenario:
Ich habe einen Kühlschrank mit der Mindestlaufzeit 01:00 Stunden.
Der Plan sieht vor dass das Gerät zwischen 08:00 und 22:00 Uhr laufen kann.
Maximal soll der Kühlschrank 08:00 Stunden laufen.
Im Sunnyportal steht das Gerät auf 100% PV.
Nun startet das Gerät aber unabhängig von der PV-Erzeugung um 08:00 und läuft die Mindestlaufzeit.

Wünschenswert wäre für mich folgende Option:
Das Gerät sollte nicht um 8 Uhr starten und die Mindestlaufzeit laufen, sondern für den start auf PV-Überschuss warten. Danach wird die Zeit gezählt die das Gerät gelaufen ist und von der Mindestlaufzeit abgezogen. Vor Planende (22:00 - verbleibende Mindestlaufzeit) kann das Gerät dann zur Not eingeschaltet werden ohne auf Überschuss Rücksicht zu nehmen um die Mindestlaufzeit zu erfüllen.

Gibt es diese Möglichekit schon oder wäre das ein neues Feature?

**Comment by camueller** [comment]
Das gewünschte Verhalten wird vom SAE ujterstützt. Vermutlich liegt ein Konfigurationsfehler vor.
Siehe https://github.com/camueller/SmartApplianceEnabler/blob/master/doc/QA_DE.md

**Comment by tuv-fabian-kirchschlager** [comment]
@camueller Danke für schnelle Rückmeldung. Ich hatte die Betriebszeiten auf 06:00 bis 22:00 uhr erweitert und bis jetzt das Problem dass der Sunny Home Manager das Gerät immer in der früh zwischen 6 und 7 eingeschaltet hatte obwohl dort keine PV-Leistung zur Verfügung stand. Im Sunnyportal habe ich Strompreise, Priorität, PV Bezug geprüft und nichts gefunden was den frühen Start erklären könnte. Gestern Abend habe ich dann per Zufall gesehen, dass in der SMA Energy App keine Strompreise gesetzt waren. Nachdem ich diese gesetzt habe, wird jetzt mit dem Einschalten tatsächlich gewartet bis die PV-Leistung da ist und das Gerät wurde heute erst um 09:08 gestartet. Möglicherweise Zufall aber es sieht so aus als wäre das gewünschte Verhalten jetzt da. Nichts desto trotz geht der Fehler vom Sunny Portal bzw dem Sunny Home Manager aus und wird nicht durch den SAE verursacht. Vielleicht hilft diese Information jemandem der das gleiche Problem hat.

**Comment by Devirex** [comment]
@camueller Danke für schnelle Rückmeldung. Ich hatte die Betriebszeiten auf 06:00 bis 22:00 uhr erweitert und bis jetzt das Problem, dass der Sunny Home Manager das Gerät immer in der früh zwischen 6 und 7 eingeschaltet hatte, obwohl dort keine PV-Leistung zur Verfügung stand. Im Sunnyportal habe ich Strompreise, Priorität, PV Bezug geprüft und nichts gefunden, dass den frühen Start erklären könnte. Gestern Abend habe ich dann per Zufall gesehen, dass in der SMA Energy App keine Strompreise gesetzt waren. Nachdem ich diese gesetzt habe, wird jetzt mit dem Einschalten tatsächlich gewartet bis die PV-Leistung da ist und das Gerät wurde heute erst um 09:08 gestartet. Nichts desto trotz geht der Fehler vom Sunny Portal bzw dem Sunny Home Manager aus und wird nicht durch den SAE verursacht. Vielleicht hilft diese Information jemandem der das gleiche Problem hat.

**Comment by camueller** [comment]
Danke für die Info, ich werde das mal in die Dokumentation aufnehmen.
