### ISSUE TITLE
Bug Speichern Button bei Http-Schaltern

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#71]
Der Test erfolge mit SAE 1.4.17 auf einem Debian Buster LXC Container mit Oracle Java 1.8.0_65.

Bei Http-Schaltern wird der Speichern Button erst aktiv wenn eine Status Abfrage URL eingetragen wird. Ohne die URL kann man in der 1.4.17-er Version keine neuen Schalter Speichern bzw. an einem Schalter Änderungen vornehmen.

**Comment by camueller** [comment]
Fixed for 1.4.18.
