### ISSUE TITLE
Bei Http-Zählern und -Schaltern werden unter bestimmten Umständen nicht die richtigen Daten angezeigt

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#73]
Der Test erfolge mit SAE 1.4.17 auf einem Debian Buster LXC Container mit Oracle Java 1.8.0_65

Habe mehrere Gosund SP1 Steckdosen und habe folgendes Problem festgestellt.

Wenn man den Zähler vom ersten Gerät auswählt und danach auf das zweite Gerät auf Zähler klickt, wird die Anzeige nicht aktualisiert und immer noch die Daten vom ersten Gerät angezeigt. Man muss aber von einem Zähler direkt auf den nächsten Zähler klicken um das Verhalten zu sehen. 

Das gleich Verhalten gilt auch für die **Schalter Anzeige für Http-Schalter**. 

Das ganze hat auch nichts mit dem Cache vom Browser zu tun, habe ich mehrfach und unter verschiedenen Browsern getestet.

![zaehler1](https://user-images.githubusercontent.com/1628654/68546595-3a0d7080-03d8-11ea-9a98-0ffb04186136.png)
![zaehler2](https://user-images.githubusercontent.com/1628654/68546598-3d086100-03d8-11ea-95ed-394f0210b20d.png)
![zaehler3](https://user-images.githubusercontent.com/1628654/68546599-3f6abb00-03d8-11ea-9576-1f386d35bd12.png)

**Comment by camueller** [comment]
Da hast Du mich auf einen sehr interessanten Fehler aufmerksam gemacht :-)
Ich habe bestimmte Aktionen in einer falschen Lifecycle-Function von Angular implementiert, konsequenterweise in alle Komponenten ...
Den Http-Schalter habe ich testweise schon gefixt, da klappt jetzt die Aktualisierung beim Wechseln zwischen verschieden Http-Schaltern. Alledings muss ich alle Komoponenten diesbezüglich fixen ...
