### ISSUE TITLE
EV-Charger Schalter Einstellungen

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#75]
In 1.4.18 werden die Einstellungen für Spannung, Phasenzahl usw im Schalter zwar gespeichert (in Appliance.xml, aber dann nicht mehr angezeigt. Beim erneuten speichern werden dann die Werte gelöscht.

**Comment by camueller** [comment]
Fehlermeldung von User webwanze:
> ich kann die Anzahl der Phasen beim EV-Charger nicht speichern. Sowohl beim Charger selbst, als auch beim E-Auto.
>Wenn ich diese Daten direkt in die Appliances.xml reinschreibe, dann
>- werden beim EV-Charger immer noch die Standardwerte in der GUI (ausgedimmt) angezeigt.
(evtl. nicht korrekt in die Appliances.xml eingetragen? Habe das vom Release 1.3.50 rüberkopiert...)
>- beim E-Auto die korrekten Werte angezeigt und auch beim Laden berücksichtigt.

**Comment by camueller** [comment]
Gefixt für 1.4.19.
