### ISSUE TITLE
Zeitplan - überlagerte/falsche Beschriftung

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#76]
siehe Screenshot, Browser Chrome
![Unbenannt](https://user-images.githubusercontent.com/19900958/69937021-c55ebb00-14d9-11ea-9e0b-899c74bb9170.PNG)

**Comment by camueller** [comment]
Das ist ein Browser-Caching-Problem. CTRL-Reload ...

**Comment by Maverick78de** [comment]
Danke, war noch zu früh am morgen
