### ISSUE TITLE
Anzeige geplanter Timeframe nach Stop durch SHM

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#77]
(1.4.18)
Wenn durch den SHM ein Laufender Timeframe unterbrochen wird springt die zu ladende Energiemenge auf '0'. Dies ist aber nur in der WebUI so, der Planningrequest wird korrekt abgesetzt.

![Unbenannt](https://user-images.githubusercontent.com/19900958/69950317-85a4cd00-14f3-11ea-8de0-df73021c85be.PNG)

**Comment by camueller** [comment]
Fehler tritt mit Version 1.5.4 (vermutlich schon ab Version 1.5.2) nicht mehr auf.
