### ISSUE TITLE
kein Rückfall auf überschußladen

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#78]
1.4.18
Nachdem ein Ladevorgang abgeschlossen wurden, fällt der SAE nicht zurück auf  Überschußladen und reportet negative Werte
![Unbenannt](https://user-images.githubusercontent.com/19900958/69964800-59994400-1513-11ea-8a9a-48c4d26bd3d2.PNG)

**Comment by camueller** [comment]
Der Fehler kann meiner Meinung nach nicht in der 1.4.18 hinzugekommen sein. Kannst Du das bestätigen?

**Comment by Maverick78de** [comment]
Eindeutig 1.4.18
nach dem neustarten des SAE wird gar kein Timeframe mehr angezeigt, obwohl der Überschuß sagt bis 90% zu laden.

![Unbenannt](https://user-images.githubusercontent.com/19900958/69983905-18fff180-1538-11ea-8596-387f9d3ca9c1.PNG)

**Comment by camueller** [comment]
Deinen letzten Kommentar verstehe ich trotz der Screenshots nicht.
Mein Code-Änderungen für 1.4.18 in diesem Bereich betreffen nur Energiemengen-Anforderung und Soc-Anforderungen. Die Änderungen sind überschaubar. Ich habe sie mir gerade angesehen, aber kann mir nicht erklären, wie es zu dem von Dir beschriebenen Verhalten kommen soll.

Ich habe es auch gerade selbst erfolglos nachgestellt: 
Ausgangsitution: Fahrzeug verbuunden, Timeframe für optionale Ernergie vorhanden
Ladevorgang über Ampel getriggert auf aktuellen SOC + 2%: Timeframe für optionale Energie nicht vorhanden, dafür Timeframe für Energiemenge in Höhe von 2%
Endsituation nach Ladeende: Timeframe für optionale Ernergie wieder vorhanden

Kannst Du mir beschreiben, wie ich den Fehler nachstellen kann?

**Comment by Maverick78de** [comment]
Ich nutze vorgegeben Timeframes. Mein Verständnis ist so, das ich per Timeframe auf einen vorgegebenen Wert lade, wenn dieser erreicht wurde und Überschuß vorhanden soll er Überschuß weiter laden.
Anbei meine Config mit den Timeframes.
[app.zip](https://github.com/camueller/SmartApplianceEnabler/files/3914934/app.zip)

**Comment by camueller** [comment]
Ich habe mir Deine Appliances.xml angesehen - Du verwendest SocRequest mit DayTimeframe.
Das habe ich gerade nachgestellt mit meiner Wallbox mit folgendem Schedule:
```
        <Schedule>
            <SocRequest evId="1" soc="2"/>
            <DayTimeframe>
                <Start hour="1" minute="0" second="0"/>
                <End hour="19" minute="0" second="0"/>
            </DayTimeframe>
        </Schedule>
```
Ich habe eine SOC von 2% vorgegeben, da die SOC-Abfrage gerade nicht funktioniert und damit der aktuelle SOC=0% ist. Er hat dann für den Test knapp eine 1 kWh geladen.
Nachdem um 19 Uhr der Timeframe deaktiviert worden ist, wurde wieder ein Timeframe for optionale Energie aktiviert (außerdem sind noch die Timeframes für die nächsten 48 Stunden enthalten):
```
<PlanningRequest>
  <Timeframe>
    <DeviceId>F-00000001-000000000019-00</DeviceId>
    <EarliestStart>0</EarliestStart>
    <LatestEnd>21099</LatestEnd>
    <MinEnergy>0</MinEnergy>
    <MaxEnergy>44235</MaxEnergy>
  </Timeframe>
  <Timeframe>
    <DeviceId>F-00000001-000000000019-00</DeviceId>
    <EarliestStart>21100</EarliestStart>
    <LatestEnd>85900</LatestEnd>
    <MinEnergy>895</MinEnergy>
    <MaxEnergy>895</MaxEnergy>
  </Timeframe>
  <Timeframe>
    <DeviceId>F-00000001-000000000019-00</DeviceId>
    <EarliestStart>107500</EarliestStart>
    <LatestEnd>172300</LatestEnd>
    <MinEnergy>895</MinEnergy>
    <MaxEnergy>895</MaxEnergy>
  </Timeframe>
</PlanningRequest>
```
Auch für Soc-Requests scheint aus meiner Sicht alles zu funktionieren, wie es soll.

**Comment by Maverick78de** [comment]
Er sollte aber nachdem er die 2% erreicht hat sofort auf Überschußladen zurück fallen, nur so macht das ganze Sinn um z.b. einen Mindestladestand zu gewährleisten und dann bei genug Überschuß auch weiter zu laden. Nicht erst nach Ablauf des Timeframes.

**Comment by camueller** [comment]
Damit nach Erreichen des Ladeziels nicht innerhalb des aktiven Timeframes erneut eingeplant wird, wurde das am 12.03.19 dahingehend geändert, dass die Timeframes bis zum Zeitablauf stehenbleiben.
Am 24.11. habe ich ausserdem folgende Änderung gemacht (für Deine Fehlermeldung in https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet/?postID=1876650#post1876650)
"Don't create energy request with maxEnergy=0 for socRequests with current soc > requested soc". 
Aus Deiner Appliance.xml ergibt sich, dass Du DayTimeframes mit 24h Laufzeit definierst. Damit sind bei Dir immer Timeframes aktiv, was eigentlich so nicht gedacht ist. Warum setzt Du nicht sinnvolle Werte für die DayTimeFrames? Dann kann in der verbleibenden Zeit das Überschußladen erfolgen.

**Comment by Maverick78de** [comment]
Dieses Verhalten ergibt mMn keinen praxisnahen Sinn. Ich arbeite heute mal ein Flow-Chart aus wie das mMn aussehen sollte. Warum soll man einen Timeframe bis zum Ende stehen lassen wenn der Zielwert erreicht wurde und die nächsten 3 bleiben auch stehen. 
Hier erwarte ich, das ein Fallback auf Überschußladen stattfindet, wenn der geplante SoC erreicht ist. Hier ein Beispiel, mindestladestand von 33% erreicht (hier gibt es wohl einen Rundungsfehler), um 8 Uhr begann der nächste Timeframe, aber er hat den SoC ja schon, also bleibt er einfach stehen. Kein Überschußladen, nix :(

![image](https://user-images.githubusercontent.com/19900958/70134472-75722680-1688-11ea-9434-4c443c252077.png)

**Comment by Maverick78de** [comment]
Ich hab mal einen möglichen Ablauf im Zug zusammen gepinselt wie ich das meine. Ich hoffe das ist verständlich. Timeframes mit 0 (Null) bis zum Ende der Laufzeit drin stehen zu lassen macht einfach keinen Sinn.

![image](https://user-images.githubusercontent.com/19900958/70165118-a66f4d00-16c2-11ea-903e-445791e92249.png)

**Comment by camueller** [comment]
Ich schaue mir die Implementierung am Wochenende nochmal genauer an.

**Comment by camueller** [comment]
Ich denke, dass ich eine Lösung gefunden habe - Test steht noch aus.
Unabhängig davon plane ich einen komplette Überholung der Timeframe-Logik in Version 1.5:
https://github.com/camueller/SmartApplianceEnabler/issues/82

**Comment by camueller** [comment]
Zu früh gefreut, die Änderung hat Seitenwirkungen und wenn ich die beheben würde, ist das Risiko zu groß, dass es andere Seitenwirkungen hat. Leider ist die aktuelle Implementierung nicht so geradlinig, wie es Dein Flow-Chart suggertiert - das wird erst durch #82 gelöst.
Es gibt aus meiner Sicht jetzt zwei Möglilchkeiten:

- wir lassen den Stand von 1.4.18
- wir gehen bzgl. Timeframes zurück auf den Stand von 1.4.17

**Comment by Maverick78de** [comment]
Die Entscheidung überlasse ich dir. Ich habe an der 1.4.18 bis auf die genannten Sachen nicht auszusetzen

**Comment by camueller** [comment]
Dann lasse ich den Zustand wie 1.4.18, zumal ich im Januar die Umsetzung von #82 beginnen will.
Damit wird dieser Issue erst in 1.5.x gefixt.

**Comment by camueller** [comment]
Sollte in Version 1.5.3 funktionieren.
