### ISSUE TITLE
Sofortstart über Änderung des Schalterstatus

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#79]
Das Erkennen eines Sofortstarts könnte so erfolgen, dass nach einem Abschalten des Gerätes aufgrund der Anlaufstromerkennung die Abfrage des Schalterzustandes signalisiert, dass das Gerät wieder eingeschaltet wurde. Als Laufzeit könnte man dann tatsächlich einfach die Minimale Einschaltdauer verwenden, die dann konfiguriert sein müßte.

Hintergrund:
Bei einer Anlaufstromerkennung würde ich folgendes Verhalten erwarten:
- Tasmota Schalter ist an, sonst ist keine Anlaufstromerkennung möglich (Ampel aus da keine Bedarfsanforderung)
- Verbraucher (z.B. Waschmaschine) wird eingeschaltet und die Anlaufstromerkennung des SAE schaltet dann den Tasmota Schalter ab (Ampel sprint auf gelb)
- Bisher ist alles ok und das was jeder erwarten würde.
- Jetzt möchte ich jedoch dass der Verbraucher sofort läuft und nicht erst wenn SHM sein OK gibt.
- Dafür drücke ich den Taster am Tasmota Schalter und würde jetzt erwarten, dass SAE die Ampel auf grün stellt und der Verbraucher dann sein Programm sofort durchlaufen kann.

Siehe: https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet/?postID=1884737#post1884737

**Comment by camueller** [comment]
Implemented for version 1.5.4

**Comment by reneschuster** [comment]
Heute beim ersten Gerät getestet und es funktioniert.

Vielen Dank Axel
