### ISSUE TITLE
Checkbox in Firefox verschoben

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#80]
Habe heute auch mal den Firefox benutzt und da passen die Checkboxen für die Anlaufstromerkennung nicht. Browser-Cache wurde geleert bzw. auch im Inkognito Modus getestet.

![Checkbox_Firefox](https://user-images.githubusercontent.com/1628654/69987957-edcdd000-1540-11ea-83ad-c41c409d6f91.png)

**Comment by camueller** [comment]
Aktuell teste ich nur mit Chrome, aber Firefox sollte ich auch mal testen ...

**Comment by camueller** [comment]
Gefixt für 1.4.19. Hat alle Checkboxen in Firefox betroffen.
