### ISSUE TITLE
Bug Inputfelder Anlaufstromerkennung

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#83]
Habe einen neuen Bug bei http Schaltern festgestellt.

Auf das erste Gerät ins Menü Schalter gehen, stehen die Werte drin.

![http1](https://user-images.githubusercontent.com/1628654/70388250-6d2f2980-19af-11ea-9ecc-43ef95ea3e45.PNG)

Dann direkt ohne Umwege auf das Menü Schalter des zweiten Gerätes, keine Einträge zu sehen, obwohl welche hinterlegt sind.

![http2_empty](https://user-images.githubusercontent.com/1628654/70388615-85557780-19b4-11ea-9421-84460f167bd2.PNG)

Zurück auf das erste Gerät auch keine Einträge drin, obwohl welche hinterlegt sind.

![http1_empty](https://user-images.githubusercontent.com/1628654/70388594-50492500-19b4-11ea-8c0d-220dacbef59c.PNG)

Hier das zweite Gerät mit Werten, nach einem Refresh.

![http2_refresh](https://user-images.githubusercontent.com/1628654/70388255-74563780-19af-11ea-9eee-73b7acdcae45.PNG)

**Comment by camueller** [comment]
Gefixt für 1.4.19.
Fehler auch gefixt für Content-Type/Benutzername/Passwort bei HTTP-basierten Geräten.
