### ISSUE TITLE
Timeframe Setup Fehler

### ISSUE THREAD

**Issue by Maverick78de** [camueller/SmartApplianceEnabler#84]
1.4.19:
Beim erstellen eines Timeframes mit Laufzeit wird die Max Laufzeit in der Maske auf 0 gesetzt und läßt sich auch speichern. Das akzeptiert der SHM nicht. Hier sollte die max Laufzeit immer >= der Min Laufzeit sein.

![image](https://user-images.githubusercontent.com/19900958/71329442-a5914480-2525-11ea-8dc9-705009ca90f2.png)

**Comment by camueller** [comment]
Sollte ab Version 1.5.2 gefixt sein.
