### ISSUE TITLE
Schaltzeiten: Maximale Laufzeit darf nicht NULL sein

### ISSUE THREAD

**Issue by F-L-0** [camueller/SmartApplianceEnabler#88]
Im Zeitplan darf das Feld "Maximale Laufzeit" nicht leer sein - ansonsten führt das dazu das remainingMaxRunningTime nicht befüllt ist (NULL) und dadurch das Gerät am Ende der per /semp gemeldeten Laufzeit vom SAE nicht abgeschalten wird und so lange weiter läuft bis das Ende des kompletten Timeframe erreicht ist.

**Comment by camueller** [comment]
Solle mit Version 1.5.2 behoben sein.
