### ISSUE TITLE
Leistungswerte bei Zählern ohne Pulsezählung zeitnaher liefern

### ISSUE THREAD

**Issue by camueller** [camueller/SmartApplianceEnabler#92]
Durch Durchnittbildung werden die Leistungsdaten verzögert an den SHM gemeldet.
Zumindest für Zähler ohne Pulszählung sollte eine zeitnahere Meldung der Leistungswerte an den SHM erfolgen.

**Comment by premultiply** [comment]
Bei Zählern mit Pulszählung ergibt sich automatisch eine verzögerungsfrei Durchschnittsbildung wenn man über eine Minute integriert, sprich die eingehenden Impule in diesem Intervall zählt.
Bei auslesbaren Zählern (MODBUS etc.) kann man analog einmal pro Minute den Zählerstand ablesen und aus dessen Differenz die durchschnittliche Leistung über die letzte Minute verzögerungsfrei erhalten. Da zählt der Zähler quasi nur schon mal intern vor.

**Comment by camueller** [comment]
> Bei Zählern mit Pulszählung ergibt sich automatisch eine verzögerungsfrei Durchschnittsbildung wenn man über eine Minute integriert, sprich die eingehenden Impule in diesem Intervall zählt.

So funktioniert das aktuell schon. Schwieriger machen es gringe Verbräuche, wenn länger als 60s kein Impuls kommt.

**Comment by premultiply** [comment]
Das ist richtig. Da würde man dann besser die Zeiten zwischen den Impulsen bzw. dessen Interrupts messen. Aber das ist oft ein eher theoretischer Weg, denn z. B. bei Zählern mit nur 1000 imp/kWh und Leistungen < 250 Watt passt halt einfach der Anwendungsfall, die Auflösung und auch die Toleranz nicht zusammen.

**Comment by chris-et** [comment]
Die ermittelten Werte bei S0-Zählern im Bereich kleiner Leistung würden sich massiv verbessern, wenn bei jedem Eintreffen eines S0-Impulses die aktuelle Leistung durch Erfassen der Zeit zur HIGH-Flanke vom Vorgänger-Impuls und Berechnung nach der Formel   (akt. Leistung) = (Energiemenge eines S0-Impulses) / (Zeitdifferenz zum vorangegangenen Impuls)   erfolgen würde. Dabei wäre die  (Energiemenge eines S0-Impulses) = 1 kWh / (Impulse/kWh) .
Nach dem Start des SAE würden dann auch für alle S0-Zähler bereits nach dem jeweils 2. Impuls jedes Zählers sinnvolle Leistungs-Werte bereitstehen und man hätte nicht die aktuell recht große Quantisierung (insbesondere bei Zählern mit nur 100 Impulsen/kWh).
Einziger Nachteil, den ich sehen würde, wäre im Bereich hoher und schnell wechselnder Leistung. Würde z.B. ein Verbraucher direkt nach einem Auslesen durch den SHM seine Leistung stark hochfahren (auf z.B. 11kW) um dann nach 50 Sekunden auf 1kW herunterzuschalten, dann wäre der letzte gemessene Wert vor erneutem Auslesen durch den SHM 1kW und die kurzzeitig gezogene hohe Leistung würde nicht detektiert werden. In diesem Fall wäre die derzeit verwendete Methode, das Zählen der Impulse über eine definierte Zeit die bessere Methode. Falls man diesen (eher konstruierten Fall) auch abdecken wollte, könnte man zwischen den beiden Verfahren wechseln und z.B. im Moment der SHM-Abfrage bei weniger als 20 Impulsen innerhalb der letzten Minute das Zeitdifferenz-Verfahren anwenden und den durch Zeitdifferenz-Verfahren ermittelten Wert statt dem aus der Impulszählung erhaltenen Wert angeben. Eine weitere Möglichkeit der Verbesserung des Zeitdifferenz-Wertes wäre einen gleitenden Durchschnitt über die innerhalb der letzten Minute errechneten Leistungswerte aus der Zeitdifferenz zu ermitteln. Dazu müssten die direkt aus der Zeitdifferenz errechneten Leistungswerte mit einem Zeitstempel versehen werden. Dann würden bei hoher Impulsrate (also schon bei mehr als 1 Impuls/Minute und erst recht bei wirklich höheren Impulsraten) bessere Durchschnittswerte entstehen. Bei < 1 Impuls / Minute würde dann natürlich keine Durchschnittsbildung stattfinden aber immer noch die beste mögliche Genauigkeit einer Leistungsangabe ohne zeitlichen Versatz (außer dem durch das geringe Abfrageinterfall des SHM von 1 Minute) erzielt werden.

**Comment by premultiply** [comment]
Das Problem ist, dass die Impulse bei kleinen Leistungen so weit auseinander liegen, dass man
a) sehr lange warten muss (z. B. > 10 Minuten bei 5 Watt an einem 1000 Imp/kWh-Zähler)
b) trotzdem ein Timeout erforderlich ist (Ab wann interpretiert man 0 Watt?)
c) ggf. auch Störeinstreungen von einzelnen Impulsen zu deutlichen Mess- bzw. Ablesefehlern führen

Fazit: Das derzeitige 1 Minuten-Fenster-Verfahren ist nicht so schlecht, sehr einfach umzusetzen und für niedrigere Leistungen braucht man im Zweifelsfall Zähler mit höherer Auflösung oder noch besser wo möglich direkt auslesbare Modbus-Zähler.

Eine Alternative wäre noch optional das Messfenster auf 10 Minuten zu erweitern (oder zusätzlich auszuwerten - ggf. auch per Sliding Window) und damit die Auflösung bedarfsweise um den Faktor 10 zu steigern.

**Comment by chris-et** [comment]
Bei weit auseinander liegenden Impulsen kommt man durch Rundung ohnehin auf 0, bis zwei Impulse von einem Zähler eingetroffen sind, wäre der Initialwert ohnehin 0. Und wenn zwei Impulse bei einem 100 Imp/kWh wirklich mal 10h auseinanderliegen dann wäre eine Angabe von 1W doch völlig i.O. und besser als die Angabe 0W. Falls Störeinflüsse wirklich einen relevanten Einfluss haben, kann man diese durch Erhöhen der Ströme bei einem Impuls und ggfs. einem Entstörkondensator (10-100nF sollten bei den Zeitkonstanten >50ms) funktionieren. Ich z.B. habe insg. 1 kOhm im Strompfad mit der S0-Schnittstelle bei 5V (also 5mA) und habe mit Oszi am RPI-Eingang sehr schöne Rechtecksignale mit Rauschen <<50mV. Dabei habe ich noch gar keinen Kondensator verbaut. Auch in mehreren Posts wurde das Thema mit der geringen Auflösung angesprochen (z.B. StandBy-Verbrauch WP).
Vielleicht könnte man in einem ersten Schritt das Zeitdifferenz-Verfahren testen ohne die ganzen o.g. Optimierungen mit Durchschnittsbildung oder Umschalten zwischen den Verfahren? z.B. durch Auswahl der Verfahren per Checkbox o.ä. im UI?
Ich setze derzeit 4 S0-Zähler ein und habe als Messfenster (angepasst an die zu detektierende Minimalleistung) 600, 900, 300 und 120 Sekunden. Das mach die Anzeige aber natürlich extrem Träge bei weiterhin nur mäßiger Auflösung.
Bedingt durch die geringe Impulsrate habe ich trotz der hohen Messfenster gelegentlich nur 1 Impuls in dem genannten Messfenster, dann wird eine Warnung im Log ausgegeben und interessanterweise nicht der für 1 Impuls korrekte Wert, sondern 0W an den SHM übermittelt. Würde hier der für 1 Impuls korrekte Wert übermittelt, würde dies seitens des SHM dann im 15Min-Raster ausgemittelt werden.
Ein Sliding-Window ist aktuell doch ohnehin bereits implementiert? Interressant wäre sowas wie ein adaptives Zeitfenster, je nach aktueller Leistung. So könnte bei kleineren Leistungen das Zeitfenster vergrößert werden. Damit würde man sich dem Zeitdifferenz-Verfahren dann annähern, läge dann aber immer noch schlechter und hätte wahrscheinlich nicht weniger Aufwand als durch die Ermittlung der Leistung mittels Zeitdifferenz-Bestimmung.

**Comment by premultiply** [comment]
Schaltvorgänge mit hoher Leistung oder auch simple Leuchtstofflampen beim Start führen zu massiven Netzstörungen die gerne mal zu Fehlimpulsregistrierungen führen.

Problem bei Zeitmessung:
Wenn man einen Verbraucher ausschaltet ist der Wert 0 und die Zeit bis zum nächsten Impuls unendlich. Daraus kann man keinen Mittelwert berechnen. Mittelwerte benötigen immer ein definiertes Zeitfenster.

Problem bei Impulszählung:
Aus nur einem Impuls pro Zeitfenster kann man keine Momentanleistung ableiten, da nicht bekannt ist ob und wann es zuvor schon einen Impuls gab oder danach geben wird. Man benötigt also mindestens 2 Impulse pro Zeitfenster als Minimalwert.

Nur weil bei einem 100 Imp/kWh-Zähler innerhalb einer Woche mal irgendwo mal ein Impuls registriert wird heisst das ja nicht dass zu diesem Zeitpunkt eine mittlere Leistung von z B. 166 Watt innerhalb des Messzeitfensters angelegen hat. Es könnten auch im Schnitt 333 Watt oder nur 19 Watt oder auch fast 0 über einen sehr langen Zeitraum (oder eine Störeinstrahlung) gewesen sein.
Ab zwei Impulsen pro Intervall kann man sich hingegen relativ sicher sein dass es einen definierten Verbrauch innerhalb eines genau definierten Fensters gegeben hat.

Wenn man sich mal die Grenzfälle ansieht stellt man schnell fest, dass das alles nicht so trivial oder im Endeffekt Kaffeesatzlerei ist bzw. in Software nicht umzusetzen ist.

Man muss sich immer vor Augen halten dass die Impuse quasi nur die elektronische Übermittlung des ablesbaren Rollenzählwerks für den Energieverbrauch sind. Wenn man dies in Software als Variable mitführt und regelmäßig "abließt" und die Differenz zur vorherigen Ablesung bildet hat man quasi schon alles gemacht was man mit diesen Daten tun kann.

**Comment by chris-et** [comment]
Natürlich sind Störeinflüsse unerwünscht und verfälschen das Messergebnis, egal bei welcher Technik zur Bestimmung der aktuellen Leistung. Mit den o.g. Möglichkeiten (und noch vielen weiteren, wie abgeschirmte kurze Leitungen usw.) kann man versuchen, diese gering zu halten.

Bei der Zeitmessung:
Ausschalten eines Verbrauchers und somit Leistung von 0W:
Völlig richtig, dass dies zu einem absolut unerwünschten Verhalten führt, bei dem die zuletzt (vor dem Ausschalten) vom angeschlossenen Verbraucher abgerufene Leistung dauerhaft an den SHM weitergegeben wird. Das hatte ich nicht bedacht.
Eine mögliche Abhilfe könnte sein, die aktuelle Leistung im Minutentakt so zu verringern, als wäre zum Zeitpunkt der SHM-Abfrage ein neuer Impuls eingegangen, diesen aber natürlich nicht für Folgeberechnungen verwenden. Somit würde sich im o.g. Fall (Ausschalten eines Verbrauchers und gar kein weiterer Verbrauch auf dem Zähler) eine anfangs steil, später immer flacher abfallende Kurve der aktuellen Leistung ergeben. Dies würde wiederum im SHM durch die Integration über die abgerufenen Leistungsdaten dann eine falsche (zu hohe) Energiemenge für den Zähler verursachen. Somit müsste zwingend eine Minimalleistung angegeben werden, unter welcher der SAE 0W an den SHM weitergibt. Damit könnte der Fehler wohl auf ein erträgliches Maß reduziert werden. Inbesondere beim Anwendungsfall "ganze Wohnung" bzw. "ganzes Stockwerk" am Zähler wäre dies nicht sonderlich kritisch, da dort immer von einer gewissen Grundlast ausgegangen werden kann. Für die Anwendung "einzelnes Gerät am Zähler" wäre dann ggfs. die Impulszählung die bessere Lösung.

Bei der Impulszählung:
Jeder Impuls entspricht einer Energiemenge (welche z.B. ja auch bezahlt werden muss).
In einem Fall, bei dem nur alle paar Minuten ein einzelner Impuls detektiert wird, kann natürlich nicht bestimmt werden, ob ein Verbraucher dauerhaft eine sehr geringe Leistung oder zyklisch kurzzeitig eine höhere Leistung abgerufen hatte. Dennoch sollte diese Leistung nicht völlig unberücksichtigt bleiben. (Macht der Energieversorger auch nicht...)
Somit sehe ich keinen Grund, warum man bei zwei Impulsen je Messzeitfenster anders verfahren sollte als bei einem Impuls. Jeder Impuls entspricht einer Energiemenge, welche durch das Messzeitfenster dividiert wird, um die aktuelle Leistung zu ermitteln. Diese ist bei der Impulszählung vor allem bei kleinen Leistungen und/oder Zählern mit kleiner Impulszahl je kWh leider sehr stark quantisiert, aber hier erst bei zwei kleinsten Einheiten zu beginnen führt durch die Integration vom SHM zu falschen gezählten Energiemengen. (Hier ist die gezählte Energiemenge dann offensichtlich zu gering)

**Comment by premultiply** [comment]
> Somit sehe ich keinen Grund, warum man bei zwei Impulsen je Messzeitfenster anders verfahren sollte als bei einem Impuls. Jeder Impuls entspricht einer Energiemenge, welche durch das Messzeitfenster dividiert wird, um die aktuelle Leistung zu ermitteln. Diese ist bei der Impulszählung vor allem bei kleinen Leistungen und/oder Zählern mit kleiner Impulszahl je kWh leider sehr stark quantisiert, aber hier erst bei zwei kleinsten Einheiten zu beginnen führt durch die Integration vom SHM zu falschen gezählten Energiemengen. (Hier ist die gezählte Energiemenge dann offensichtlich zu gering)

Das Fortschreiten der gezählten Energiemenge um eine Einheit sagt aber nichts über den Zeitraum aus in der diese durch den Zähler geflossen ist! Leistung ist Energie(einheiten) pro Zeit.
Die Impulse sind eben KEIN Abtastwert sondern der Abtastwert ergibt sich erst durch die Integration über einen definierten Zeitraum. Hier ist die Zeit das Abtastraster und die Summe der Impulse in einem Intervall ist der Abtastwert.

Wenn du dir vorstellst dass für eine Woche lange jede Minute (die Zeiteinheiten sind hier willkürlich gewählt) 0 Impulse eingehen mit der Ausnahme einer einzigen Minute wo 1 Impuls detektiert wird:
Was sagt das über die Momentanleistung während dieser Minute aus?

Treten in dieser Minute aber zwei Impulse auf kann man daraus dann im Gegensatz zu einem Impuls aber was schließen? Tipp: Grenzfall betrachten. Ein Impuls direkt am Anfang der Minute, der nächste ganz knapp vor dem Beginn der nächsten Minute.

Ich nehm das Ergebnis vorweg: Im letzten Fall wird genau EINE Energieeinheit verbraucht, die Leistung beträgt 1 Einheit pro Intervall (und eben nicht zwei).

Der nächste Grenzfall tritt auf wenn gerade so noch nicht 3 Impulse pro Intervall gezählt werden - der nächste (3.) Impuls kommt zu Beginn des nachfolgenden Intervalls: Hier Beträgt die Momentanleistung (im Durchschnitt) < 2 Energieeinheiten pro Intervall.

Fazit: Ab zwei Impulsen pro Intervall wurde also mindestens Eine aber noch keine zwei Energieeinheiten verbraucht. Ganzzahlig abgerundet: 1 Energieeinheit pro Intervall.

Nochmal der Gegencheck:
Bei nur einem Impuls pro Intervall sind es hingegen 0 bis noch keine ganze Energieeinheit pro Intervall. Ganzahlig abgerundet: Null.

Notfalls mal aufmalen ;-)

**Comment by premultiply** [comment]
Aber eigentlich geht es hier auch um Zähler OHNE Pulszählung also mit MODBUS etc. ;-)

**Comment by chris-et** [comment]
Hier ein anderes Beispiel, welches zeigt, dass bei jedem Impuls auch wirklich eine Energiemenge geflossen ist:
Nehmen wir ein Zähler mit 1 Imp / kWh.
In jeder Stunde gibt dieser einen Impuls ab. (Der interessiert sich nicht wirklich dafür, was für ein Messfenster der SAE dahinter gesetzt hat)
Dann muss ich jeden Tag 24 kWh an meinen EVU bezahlen, völlig egal ob ich mir nun ein Messfenster von 24h definiere (in dem ich 24 Impulse zähle) oder ein Messfenster von 1 Minute (hier detektiere ich in allen 1440 Messfenstern mit Ausnahme von 24 Stück keinen Impuls)
Lege ich nun fest, dass ich einen Impuls im Messfenster kategorisch ignoriere, sehe ich im SHM keinen Stromverbrauch (cool 24 kWh gespart...) -> würde man aber nun in den 24 Messfenstern, in denen ein Impuls detektiert wurde, die rechnerisch richtige Leistung von 60 kW an dem SHM übermitteln, wird dieser diese Leistung in ein 15-Minuten-Intervall aufintegrieren und speichern. Es würde also ein Abruf von 4kW über 15 Minuten gespeichert werden und die darauffolgenden 45 Minuten 0W. Über die Stunde gemittelt gibt das die gewünschte Leistung von 1kW und über einen Tag die verbrauchten 24 kWh.

**Comment by chris-et** [comment]
Oh, wäre es sinnvoll ein neues Issue "Optimierung Genauigkeit von S0-Zählern" zu erstellen?

**Comment by premultiply** [comment]
Eigentlich ist dazu alles gesagt. Kurz: Es geht nicht.
Zur weiteren Lektüre: https://de.wikipedia.org/wiki/Nyquist-Shannon-Abtasttheorem


Solange der SAE jeden S0-Impuls intern dazu verwendet um eine Variable zu inkrementieren (Zählerstand) und dann im Minutentakt eine Differenz aus deren aktuellen Wert und Vorgängerwert zur Berechnung der Momentanleistung zu bilden ist alles super.
Bei MODBUS-Zählern kann man sich dabei lediglich das Inkrementieren der Variable sparen sondern muss stattdessen dort direkt den Zählerstand als Datum übernehmen. Der Rest sollte dann identisch sein.

**Comment by chris-et** [comment]
Wir sind ja nun hier auf zwei unterschiedliche Aspekte gestoßen:

Zum einen der Programmfehler, dass bei geringer Impulsrate Impulse nicht berücksichtigt werden.
Ich denke meine Ausführungen im letzten Post beschreiben diesen Fehler und dessen Auswirkungen doch ausführlich genug und eine Behebung dieses sollte mit minimalem Aufwand möglich sein. Die Fehlerbehebung hat keinerlei negative Auswirkungen auf andere Programmteile und verbessert die Genauigkeit der vom SHM gezählten Energie maßgeblich.

Zum anderen eine in mehreren Posts beschriebene mögliche Erweiterung der Funktionsweise, welche natürlich von irgendjemandem umgesetzt werden könnte oder auch nicht. Ich könnte mir die Programmlogik gerne mal genauer ansehen und hier einen Teil der Arbeit übernehmen. Dazu wäre es sehr hilfreich ein paar Stichworte zu den verwendeten Programmteilen zu erhalten, damit ich nicht bei Null beginnen muss.
Der Hinweis mit Nyquist-Shannon-Abtasttheorem passt hier interessanterweise mal wirklich sehr gut, wenngleich hier die variable Abtastrate gleich die abzutastende Information enthält...

**Comment by chris-et** [comment]
Ich hab mir mal kurz die PulsePowerMeter.java angesehen und bin wirklich schwer beeindruckt. Dort ist soweit ich gesehen habe, nahezu alles o.g. bereits implementiert. Z.B. die Funktion getPower returned die aktuelle Leistung basierend auf den Zeitdifferenzen. Auch das Abschalten eines Gerätes und die daraufhin große Verlängerung der Zeitabstände der Impulse ist berücksichtigt (allerdings nicht im Zusammenhang mit der Funktion getPower?). Weiterhin existiert eine Liste mit den Zeitstempeln der Impulse. (von der letzten Stunde) Ich werde mir das die nächsten Tage mal näher ansehen.

**Comment by camueller** [comment]
Ich finde es toll, wie detailliert ihr hier über das Auswerten der Zähler im SAE diskutiert. Für Version 1.6.x würde ich gern das Zählerverhalten verbessern und greife dazu gern auf Eure Ideen oder im Idealfalls sogar Pull Request von Euch zurück. In den nächsten Wochen habe ich selbst noch keine Zeit für das Thema, da ich derzeit (auch schon für 1.6.x) die Web-Oberfläche grundlegend überarbeite.

**Comment by camueller** [comment]
Neu-Implementierung ist in SAE 1.6.1 enthalten.
