### ISSUE TITLE
http-schalter soll unabhängig vom Gerätestatus am Ende des Timeframe ausgeschalten werden

### ISSUE THREAD

**Issue by F-L-0** [camueller/SmartApplianceEnabler#93]
Hallo Axel,

ich hätte da einen Feature Request:

Wenn bei einem Gerät Status über HTTP abfragen konfiguriert ist wird am Ende des aktiven Timeframe überprüft ob das Gerät eingeschalten ist. Wenn dies nicht der Fall ist wird dem Gerät kein Ausschaltbefehl geschickt.

Das klingt erstmal logisch, hat bei mir (und evtl. anderen Usern mit ähnlichem Use Case) aber folgendes Problem:

Mit dem Schalter schalte ich per http-Request die Solltemperatur der Wärmepumpe. Der Status Request prüft aber nicht die Solltemperatur, sondern den aktuellen tatsächlichen Betriebszustand der Wärmepumpe.

Ablauf ist dann wie folgt:

- SHM sendet Einschaltbefehl
- SAE setzt per http-Request die WW-Solltemperatur von 10 auf 47grad
- Wärmepumpe läuft los, der Betriebszustand (Status über http abfragen) wechselt von Aus nach An
- Wärmepumpe ist fertig, der Betriebszustand (Status über http abfragen) wechselt von An nach Aus
- am Ende des Timeframe wird die WW-Solltemperatur nicht mehr auf 10 Grad zurück gesetzt da der Betriebszustand schon Aus ist
- Wärmepumpe läuft dann ggf. außerhalb des Timeframe wieder an

Schön wäre wenn am Ende des Timeframe/Laufzeit unabhängig vom zurück gelieferten Wert (Status über http abfragen) das Gerät ausgeschalten wird. Falls das in anderen Use Cases nicht sinnvoll ist wäre es gut wenn man das Optional konfigurieren kann (Erzwinge Ausschalten Checkbox).

**Comment by camueller** [comment]
Kommt mit Version 1.5.5.
