### ISSUE TITLE
SOC, Restdauer & Co. für Renault-ZE-Fahrzeuge

### ISSUE THREAD

**Issue by premultiply** [camueller/SmartApplianceEnabler#97]
Für Renault-ZE-Fahrzeuge (z. B. ZOE) gibt es ebenfalls eine API mit zugehörigem Script unter https://github.com/jamesremuscat/pyze

Hier wird neben dem SOC auch unter anderem die vom Fahrzeug berechnete Restladedauer abhängig von den internen Batteriedaten (bis voll) übermittelt.

Sollte sich mindestens analog der anderen SOC-Scripts einbinden lassen.

**Comment by camueller** [comment]
Die SOC-Scripts sollten von Usern erstellt werden, die daran interessiert sind.
Dann einen Merge-Request erstellen, damit ich Script und Doku in das Projekt übernehmen kann.
Ansonsten kann/werde ich zu diesem Thema nichts machen.
